<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="it" xml:lang="it"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Margherita Calderan">

<title>Modelli lineari</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-cbd6adc4ec99144a4fc140fff8794b38.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nessun risultato",
    "search-matching-documents-text": "documenti trovati",
    "search-copy-link-title": "Copiare il link nella ricerca",
    "search-hide-matches-text": "Nascondere i risultati aggiuntivi",
    "search-more-match-text": "ci sono altri risultati in questo documento",
    "search-more-matches-text": "ulteriori risultati in questo documento",
    "search-clear-button-title": "Pulire",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancellare",
    "search-submit-button-title": "Inviare",
    "search-label": "Ricerca"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Ricerca"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Attiva/disattiva la navigazione" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./modelli-lineari.html"> 
<span class="menu-text">LM</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./bayes.html" aria-current="page"> 
<span class="menu-text">Bayes</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenuti</h2>
   
  <ul>
  <li><a href="#il-modello-lineare" id="toc-il-modello-lineare" class="nav-link active" data-scroll-target="#il-modello-lineare"><span class="header-section-number">1</span> Il modello lineare</a>
  <ul class="collapse">
  <li><a href="#sec-assunzioni" id="toc-sec-assunzioni" class="nav-link" data-scroll-target="#sec-assunzioni"><span class="header-section-number">1.1</span> Le assunzioni del modello di regressione</a></li>
  </ul></li>
  <li><a href="#la-regressione-lineare-semplice" id="toc-la-regressione-lineare-semplice" class="nav-link" data-scroll-target="#la-regressione-lineare-semplice"><span class="header-section-number">2</span> La regressione lineare semplice</a>
  <ul class="collapse">
  <li><a href="#un-solo-predittore-quantitativo-o-categoriale" id="toc-un-solo-predittore-quantitativo-o-categoriale" class="nav-link" data-scroll-target="#un-solo-predittore-quantitativo-o-categoriale"><span class="header-section-number">2.1</span> Un solo predittore: quantitativo o categoriale</a></li>
  <li><a href="#sec-dati" id="toc-sec-dati" class="nav-link" data-scroll-target="#sec-dati"><span class="header-section-number">2.2</span> I dati: <code>kidiq</code></a></li>
  <li><a href="#sec-numerico" id="toc-sec-numerico" class="nav-link" data-scroll-target="#sec-numerico"><span class="header-section-number">2.3</span> Un predittore numerico</a></li>
  <li><a href="#sec-summary" id="toc-sec-summary" class="nav-link" data-scroll-target="#sec-summary"><span class="header-section-number">2.4</span> La valutazione delle stime: <code>summary()</code></a></li>
  <li><a href="#sec-diagnostica" id="toc-sec-diagnostica" class="nav-link" data-scroll-target="#sec-diagnostica"><span class="header-section-number">2.5</span> La diagnostica grafica</a></li>
  <li><a href="#sec-dicotomico" id="toc-sec-dicotomico" class="nav-link" data-scroll-target="#sec-dicotomico"><span class="header-section-number">2.6</span> Un predittore dicotomico</a></li>
  </ul></li>
  <li><a href="#la-regressione-multipla" id="toc-la-regressione-multipla" class="nav-link" data-scroll-target="#la-regressione-multipla"><span class="header-section-number">3</span> La regressione multipla</a>
  <ul class="collapse">
  <li><a href="#un-esempio-con-due-predittori" id="toc-un-esempio-con-due-predittori" class="nav-link" data-scroll-target="#un-esempio-con-due-predittori"><span class="header-section-number">3.1</span> Un esempio con due predittori</a></li>
  <li><a href="#lanalisi-degli-effetti" id="toc-lanalisi-degli-effetti" class="nav-link" data-scroll-target="#lanalisi-degli-effetti"><span class="header-section-number">3.2</span> L’analisi degli effetti</a></li>
  <li><a href="#la-rappresentazione-grafica-degli-effetti" id="toc-la-rappresentazione-grafica-degli-effetti" class="nav-link" data-scroll-target="#la-rappresentazione-grafica-degli-effetti"><span class="header-section-number">3.3</span> La rappresentazione grafica degli effetti</a></li>
  </ul></li>
  <li><a href="#gli-effetti-di-interazione" id="toc-gli-effetti-di-interazione" class="nav-link" data-scroll-target="#gli-effetti-di-interazione"><span class="header-section-number">4</span> Gli effetti di interazione</a>
  <ul class="collapse">
  <li><a href="#lanalisi-degli-effetti-1" id="toc-lanalisi-degli-effetti-1" class="nav-link" data-scroll-target="#lanalisi-degli-effetti-1"><span class="header-section-number">4.1</span> L’analisi degli effetti</a></li>
  <li><a href="#la-rappresentazione-grafica" id="toc-la-rappresentazione-grafica" class="nav-link" data-scroll-target="#la-rappresentazione-grafica"><span class="header-section-number">4.2</span> La rappresentazione grafica</a></li>
  </ul></li>
  <li><a href="#sec-adattamento" id="toc-sec-adattamento" class="nav-link" data-scroll-target="#sec-adattamento"><span class="header-section-number">5</span> La valutazione dell’adattamento</a>
  <ul class="collapse">
  <li><a href="#i-residui-del-modello-gli-scarti" id="toc-i-residui-del-modello-gli-scarti" class="nav-link" data-scroll-target="#i-residui-del-modello-gli-scarti"><span class="header-section-number">5.1</span> I residui del modello: gli scarti</a></li>
  <li><a href="#le-devianze" id="toc-le-devianze" class="nav-link" data-scroll-target="#le-devianze"><span class="header-section-number">5.2</span> Le devianze</a></li>
  <li><a href="#la-valutazione-dei-residui" id="toc-la-valutazione-dei-residui" class="nav-link" data-scroll-target="#la-valutazione-dei-residui"><span class="header-section-number">5.3</span> La valutazione dei residui</a></li>
  <li><a href="#sec-anomali" id="toc-sec-anomali" class="nav-link" data-scroll-target="#sec-anomali"><span class="header-section-number">5.4</span> Casi anomali e casi influenti</a></li>
  <li><a href="#il-predictive-check" id="toc-il-predictive-check" class="nav-link" data-scroll-target="#il-predictive-check"><span class="header-section-number">5.5</span> Il predictive check</a></li>
  <li><a href="#sec-variabilita" id="toc-sec-variabilita" class="nav-link" data-scroll-target="#sec-variabilita"><span class="header-section-number">5.6</span> Variabilità residua e variabilità spiegata</a>
  <ul class="collapse">
  <li><a href="#la-variabilità-residua-sigma" id="toc-la-variabilità-residua-sigma" class="nav-link" data-scroll-target="#la-variabilità-residua-sigma"><span class="header-section-number">5.6.1</span> La variabilità residua: <span class="math inline">\(\sigma\)</span></a></li>
  <li><a href="#la-variabilità-spiegata-r2-e-eta2" id="toc-la-variabilità-spiegata-r2-e-eta2" class="nav-link" data-scroll-target="#la-variabilità-spiegata-r2-e-eta2"><span class="header-section-number">5.6.2</span> La variabilità spiegata: <span class="math inline">\(R^2\)</span> e <span class="math inline">\(\eta^2\)</span></a></li>
  <li><a href="#due-casi-particolari" id="toc-due-casi-particolari" class="nav-link" data-scroll-target="#due-casi-particolari"><span class="header-section-number">5.6.3</span> Due casi particolari</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#confronto-e-selezione-di-modelli" id="toc-confronto-e-selezione-di-modelli" class="nav-link" data-scroll-target="#confronto-e-selezione-di-modelli"><span class="header-section-number">6</span> Confronto e selezione di modelli</a>
  <ul class="collapse">
  <li><a href="#i-problemi" id="toc-i-problemi" class="nav-link" data-scroll-target="#i-problemi"><span class="header-section-number">6.1</span> I problemi</a></li>
  <li><a href="#loverfitting" id="toc-loverfitting" class="nav-link" data-scroll-target="#loverfitting"><span class="header-section-number">6.2</span> L’overfitting</a></li>
  <li><a href="#il-confronto-mediante-anova" id="toc-il-confronto-mediante-anova" class="nav-link" data-scroll-target="#il-confronto-mediante-anova"><span class="header-section-number">6.3</span> Il confronto mediante ANOVA</a></li>
  <li><a href="#aic-e-bic" id="toc-aic-e-bic" class="nav-link" data-scroll-target="#aic-e-bic"><span class="header-section-number">6.4</span> AIC e BIC</a></li>
  <li><a href="#la-quantificazione-dellevidenza" id="toc-la-quantificazione-dellevidenza" class="nav-link" data-scroll-target="#la-quantificazione-dellevidenza"><span class="header-section-number">6.5</span> La quantificazione dell’evidenza</a></li>
  <li><a href="#verosimiglianza-relativa-e-pesi-di-akaike" id="toc-verosimiglianza-relativa-e-pesi-di-akaike" class="nav-link" data-scroll-target="#verosimiglianza-relativa-e-pesi-di-akaike"><span class="header-section-number">6.6</span> Verosimiglianza relativa e pesi di Akaike</a></li>
  <li><a href="#il-pacchetto-mumin" id="toc-il-pacchetto-mumin" class="nav-link" data-scroll-target="#il-pacchetto-mumin"><span class="header-section-number">6.7</span> Il pacchetto MuMIn</a></li>
  <li><a href="#i-vantaggi-dei-criteri-di-informazione" id="toc-i-vantaggi-dei-criteri-di-informazione" class="nav-link" data-scroll-target="#i-vantaggi-dei-criteri-di-informazione"><span class="header-section-number">6.8</span> I vantaggi dei criteri di informazione</a></li>
  </ul></li>
  <li><a href="#riferimenti-bibliografici" id="toc-riferimenti-bibliografici" class="nav-link" data-scroll-target="#riferimenti-bibliografici"><span class="header-section-number">7</span> Riferimenti bibliografici</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Modelli lineari</h1>
<p class="subtitle lead">Dispensa del corso</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autore/Autrice</div>
    <div class="quarto-title-meta-contents">
             <p>Margherita Calderan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data di Pubblicazione</div>
    <div class="quarto-title-meta-contents">
      <p class="date">14 giugno 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-tip no-icon callout-titled" title="📌 Come usare questa dispensa">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
📌 Come usare questa dispensa
</div>
</div>
<div class="callout-body-container callout-body">
<p>Questo documento raccoglie tutto il materiale della lezione (circa 7 ore) e va letto con <strong>R aperto accanto</strong>: il modo migliore per imparare è eseguire il codice man mano che lo incontrate, modificarlo e osservare che cosa cambia.</p>
<p>Lungo il percorso troverete degli <strong>esercizi</strong> (riquadri azzurri ✏️): provate a risolverli da soli prima di aprire la soluzione (riquadri verdi, chiusi di default).</p>
<p>Prima di iniziare:</p>
<ol type="1">
<li>installate i pacchetti necessari: <code>install.packages(c("ggplot2", "sjPlot", "effects", "performance", "MuMIn"))</code></li>
<li>scaricate il file <a href="dati/kidiq.csv">kidiq.csv</a> e salvatelo in una cartella <code>dati</code> dentro la vostra cartella di lavoro.</li>
</ol>
</div>
</div>
<section id="il-modello-lineare" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Il modello lineare</h1>
<p>Un <strong>modello lineare</strong> è un modello statistico della forma</p>
<p><span class="math display">\[
Y = X\beta + \epsilon
\]</span></p>
<p>dove <span class="math inline">\(Y\)</span> è la <strong>variabile risposta</strong> (o variabile dipendente), <span class="math inline">\(X\)</span> è un insieme di <strong>predittori</strong> (o variabili indipendenti) e <span class="math inline">\(\epsilon\)</span> è la <strong>componente d’errore</strong>, cioè la parte di <span class="math inline">\(Y\)</span> che il modello non spiega.</p>
<p>Con <span class="math inline">\(\beta\)</span> indichiamo i <strong>coefficienti di regressione</strong>: lo scopo del modello è proprio stimare questi parametri a partire dai dati osservati.</p>
<p>Questi modelli si chiamano <em>lineari</em> perché la relazione ipotizzata tra i predittori e la variabile dipendente è assunta essere lineare: ogni predittore contribuisce alla previsione di <span class="math inline">\(Y\)</span> in modo additivo, moltiplicato per il proprio coefficiente.</p>
<p>I predittori possono essere <strong>quantitativi</strong> (es. età, QI) oppure <strong>categoriali</strong> (es. genere, gruppo sperimentale): vedremo che il modello lineare li gestisce entrambi, ed è proprio questa flessibilità a renderlo lo strumento di base dell’analisi dei dati in psicologia e non solo.</p>
<section id="sec-assunzioni" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="sec-assunzioni"><span class="header-section-number">1.1</span> Le assunzioni del modello di regressione</h2>
<p>Perché le stime e le inferenze del modello siano valide, il modello di regressione si fonda su alcune assunzioni:</p>
<p><strong>1. Indipendenza tra <span class="math inline">\(X\)</span> ed errore.</strong> La variabile <span class="math inline">\(X\)</span> e l’errore sono indipendenti nella popolazione: i predittori non contengono informazione sull’errore.</p>
<p><strong>2. Indipendenza degli errori.</strong> Ogni coppia di errori <span class="math inline">\(\epsilon_i\)</span> e <span class="math inline">\(\epsilon_j\)</span> è indipendente, per <span class="math inline">\(i \neq j\)</span>: l’errore di un’osservazione non dice nulla sull’errore di un’altra (questa assunzione cade, ad esempio, con misure ripetute sugli stessi soggetti).</p>
<p><strong>3. Linearità.</strong> Il valore atteso dell’errore, dato il valore di <span class="math inline">\(X\)</span>, è zero: <span class="math inline">\(E(\epsilon_i) = E(\epsilon\,|\,x_i) = 0\)</span>. In altre parole, la relazione tra <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> è davvero una retta: il modello non sbaglia <em>sistematicamente</em> in nessuna zona di <span class="math inline">\(X\)</span>.</p>
<p><strong>4. Omoschedasticità (varianza costante).</strong> La varianza degli errori è la stessa per qualunque valore di <span class="math inline">\(X\)</span>: <span class="math inline">\(V(\epsilon\,|\,x_i) = \sigma^2\)</span>.</p>
<p><strong>5. Normalità.</strong> Gli errori si distribuiscono normalmente: <span class="math inline">\(\epsilon_i \sim \mathcal{N}(0, \sigma^2)\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Le assunzioni riguardano <strong>gli errori</strong>, non la variabile <span class="math inline">\(Y\)</span> di per sé: non serve che <span class="math inline">\(Y\)</span> sia normale, serve che lo siano i residui del modello. Torneremo su questo punto nella <a href="#sec-adattamento" class="quarto-xref">Sezione&nbsp;5</a>, quando impareremo a <em>verificare</em> queste assunzioni con la diagnostica grafica.</p>
</div>
</div>
</section>
</section>
<section id="la-regressione-lineare-semplice" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> La regressione lineare semplice</h1>
<p>Un modello con <strong>un solo predittore</strong> <span class="math inline">\(X\)</span> e una variabile dipendente <span class="math inline">\(Y\)</span> quantitativa si chiama <strong>regressione lineare semplice</strong>.</p>
<section id="un-solo-predittore-quantitativo-o-categoriale" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="un-solo-predittore-quantitativo-o-categoriale"><span class="header-section-number">2.1</span> Un solo predittore: quantitativo o categoriale</h2>
<p>Con un solo predittore, la formulazione del modello cambia a seconda del tipo di variabile:</p>
<p><strong>1. Se <span class="math inline">\(X\)</span> è continua/quantitativa:</strong></p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 X + \epsilon
\]</span></p>
<p>dove <span class="math inline">\(\beta_0\)</span> è l’<strong>intercetta</strong> (il valore atteso di <span class="math inline">\(Y\)</span> quando <span class="math inline">\(X = 0\)</span>) e <span class="math inline">\(\beta_1\)</span> è la <strong>pendenza</strong> (di quanto cambia, in media, <span class="math inline">\(Y\)</span> quando <span class="math inline">\(X\)</span> aumenta di una unità).</p>
<p><strong>2. Se <span class="math inline">\(X\)</span> è categoriale con <span class="math inline">\(k\)</span> categorie:</strong></p>
<p><span class="math display">\[
Y = \beta_0 + \sum_{j=1}^{k-1} \beta_j D_j + \epsilon
\]</span></p>
<p>dove le <span class="math inline">\(D_j\)</span> sono <strong>variabili dummy</strong> che assumono solo i valori 0 e 1.</p>
<p>Per esempio, con <span class="math inline">\(k = 2\)</span> categorie serve una sola dummy:</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 D_1 + \epsilon
\]</span></p>
<p>mentre con <span class="math inline">\(k = 3\)</span> categorie ne servono due:</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 D_1 + \beta_2 D_2 + \epsilon
\]</span></p>
<p>Per fortuna <strong>non dobbiamo occuparci noi della ricodifica</strong>: R la fa automaticamente quando il predittore è un <code>factor</code>. Quello che dobbiamo capire bene è il <em>significato</em> della ricodifica, per poter interpretare correttamente i parametri stimati: la categoria di riferimento (quella con tutte le dummy a 0) finisce nell’intercetta, e ciascun <span class="math inline">\(\beta_j\)</span> esprime la differenza tra la categoria <span class="math inline">\(j\)</span> e quella di riferimento.</p>
</section>
<section id="sec-dati" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="sec-dati"><span class="header-section-number">2.2</span> I dati: <code>kidiq</code></h2>
<p>In tutta la dispensa useremo un dataset classico (Gelman &amp; Hill), che contiene le seguenti variabili relative a un campione di bambini di 3–4 anni:</p>
<ul>
<li><code>kid_score</code>: punteggio del bambino in un test cognitivo;</li>
<li><code>mom_hs</code>: istruzione della madre (1 = diplomata, 0 = non diplomata);</li>
<li><code>mom_iq</code>: QI della madre;</li>
<li><code>mom_work</code>: condizione lavorativa della madre nei primi anni di vita del bambino (4 categorie);</li>
<li><code>mom_age</code>: età della madre.</li>
</ul>
<p>Carichiamo i dati e sistemiamo le variabili categoriali, che nel file sono codificate come numeri:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>kidiq <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"dati/kidiq.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>kidiq<span class="sc">$</span>mom_hs   <span class="ot">&lt;-</span> <span class="fu">factor</span>(kidiq<span class="sc">$</span>mom_hs)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>kidiq<span class="sc">$</span>mom_work <span class="ot">&lt;-</span> <span class="fu">factor</span>(kidiq<span class="sc">$</span>mom_work)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(kidiq)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   434 obs. of  5 variables:
 $ kid_score: int  65 98 85 83 115 98 69 106 102 95 ...
 $ mom_hs   : Factor w/ 2 levels "0","1": 2 2 2 2 2 1 2 2 2 2 ...
 $ mom_iq   : num  121.1 89.4 115.4 99.4 92.7 ...
 $ mom_work : Factor w/ 4 levels "1","2","3","4": 4 4 4 3 4 1 4 3 1 1 ...
 $ mom_age  : int  27 25 27 25 27 18 20 23 24 19 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(kidiq)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  kid_score mom_hs    mom_iq mom_work mom_age
1        65      1 121.11753        4      27
2        98      1  89.36188        4      25
3        85      1 115.44316        4      27
4        83      1  99.44964        3      25
5       115      1  92.74571        4      27
6        98      0 107.90184        1      18</code></pre>
</div>
</div>
<p>Abbiamo 434 osservazioni e 5 variabili. Notate che <code>mom_hs</code> e <code>mom_work</code> ora sono <code>factor</code>: è così che R sa che deve trattarle come categoriali (e costruire le dummy al posto nostro).</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="✏️ Esercizio 1 — Esplorare i dati">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✏️ Esercizio 1 — Esplorare i dati
</div>
</div>
<div class="callout-body-container callout-body">
<p>Prima di stimare qualsiasi modello, è buona pratica guardare i dati. Con i comandi di base di R:</p>
<ol type="a">
<li>quante madri sono diplomate e quante no?</li>
<li>calcolate media e deviazione standard di <code>kid_score</code>;</li>
<li>disegnate l’istogramma di <code>kid_score</code>: la distribuzione vi sembra simmetrica?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Soluzione — Esercizio 1">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Soluzione — Esercizio 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(kidiq<span class="sc">$</span>mom_hs)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
 93 341 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(kidiq<span class="sc">$</span>kid_score)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 86.79724</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(kidiq<span class="sc">$</span>kid_score)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 20.41069</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(kidiq<span class="sc">$</span>kid_score, <span class="at">main =</span> <span class="st">""</span>, <span class="at">xlab =</span> <span class="st">"Punteggio del bambino"</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/sol-es1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Le madri diplomate sono 341, le non diplomate 93. Il punteggio medio dei bambini è circa 87, con deviazione standard di circa 20 punti. L’istogramma mostra una distribuzione leggermente asimmetrica a sinistra (qualche punteggio molto basso), ma nulla di drammatico. Ricordate comunque che le assunzioni del modello riguardano i <strong>residui</strong>, non la distribuzione di <span class="math inline">\(Y\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="sec-numerico" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="sec-numerico"><span class="header-section-number">2.3</span> Un predittore numerico</h2>
<p>Vogliamo valutare se il <strong>QI della madre</strong> è predittivo del punteggio del bambino. Stimiamo il modello con la funzione <code>lm()</code> (<em>linear model</em>), la cui sintassi è <code>lm(risposta ~ predittore, data = dati)</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> mom_iq, <span class="at">data =</span> kidiq)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kid_score <span class="sc">~</span> mom_iq, <span class="at">data =</span> kidiq,</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"QI della madre"</span>, <span class="at">ylab =</span> <span class="st">"Punteggio del bambino"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(m1, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/m1-scatter-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I coefficienti stimati sono:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m1)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)      mom_iq 
 25.7997778   0.6099746 </code></pre>
</div>
</div>
<p>L’equazione di regressione è dunque</p>
<p><span class="math display">\[
\hat{Y} = 25.8 + 0.61 X
\]</span></p>
<p>dove il “cappello” su <span class="math inline">\(Y\)</span> indica che si tratta dei valori <em>previsti</em> dal modello. Come si leggono i coefficienti?</p>
<ul>
<li><span class="math inline">\(\beta_1 = 0.61\)</span>: per ogni punto di QI in più della madre, il punteggio atteso del bambino aumenta in media di 0.61 punti;</li>
<li><span class="math inline">\(\beta_0 = 25.8\)</span>: è il punteggio atteso di un bambino la cui madre ha QI pari a zero. Un valore privo di senso! L’intercetta serve al modello, ma non sempre ha un’interpretazione sostantiva: per renderla interpretabile si può <em>centrare</em> il predittore (es. <code>mom_iq - 100</code>), così l’intercetta diventa il punteggio atteso per una madre con QI = 100.</li>
</ul>
</section>
<section id="sec-summary" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="sec-summary"><span class="header-section-number">2.4</span> La valutazione delle stime: <code>summary()</code></h2>
<p>La funzione <code>summary()</code> restituisce il quadro completo del modello:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kid_score ~ mom_iq, data = kidiq)

Residuals:
    Min      1Q  Median      3Q     Max 
-56.753 -12.074   2.217  11.710  47.691 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 25.79978    5.91741    4.36 1.63e-05 ***
mom_iq       0.60997    0.05852   10.42  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.27 on 432 degrees of freedom
Multiple R-squared:  0.201, Adjusted R-squared:  0.1991 
F-statistic: 108.6 on 1 and 432 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Leggiamo l’output pezzo per pezzo:</p>
<ul>
<li><strong><code>Residuals</code></strong>: la distribuzione dei residui (osservato − previsto). Se il modello è adeguato, mediana vicina a 0 e quartili circa simmetrici.</li>
<li><strong><code>Estimate</code></strong>: le stime dei coefficienti, già viste con <code>coef()</code>.</li>
<li><strong><code>Std. Error</code></strong>: l’errore standard di ciascuna stima, cioè la sua incertezza: con campioni diversi otterremmo stime un po’ diverse, e l’errore standard ne quantifica la variabilità.</li>
<li><strong><code>t value</code> e <code>Pr(&gt;|t|)</code></strong>: la statistica <span class="math inline">\(t\)</span> (stima / errore standard) e il relativo p-value per l’ipotesi nulla <span class="math inline">\(\beta = 0\)</span>. Qui il test su <code>mom_iq</code> è altamente significativo: il QI della madre predice il punteggio del bambino.</li>
<li><strong><code>Residual standard error</code></strong> (<span class="math inline">\(\sigma\)</span>): la deviazione standard dei residui, circa 18.3 punti. Ci dice di quanto, in media, il modello “sbaglia” le previsioni.</li>
<li><strong><code>Multiple R-squared</code></strong>: la proporzione di variabilità di <span class="math inline">\(Y\)</span> spiegata dal modello, qui circa il 20%. Ne riparleremo nella <a href="#sec-variabilita" class="quarto-xref">Sezione&nbsp;5.6</a>.</li>
<li><strong><code>F-statistic</code></strong>: il test globale del modello contro il modello nullo (solo intercetta).</li>
</ul>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="✏️ Esercizio 2 — La vostra prima regressione">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✏️ Esercizio 2 — La vostra prima regressione
</div>
</div>
<div class="callout-body-container callout-body">
<p>Stimate un modello in cui il punteggio del bambino è predetto dall’<strong>età della madre</strong> (<code>mom_age</code>).</p>
<ol type="a">
<li>Scrivete l’equazione di regressione stimata.</li>
<li>Come interpretate la pendenza?</li>
<li>Qual è il punteggio previsto per un bambino la cui madre ha 20 anni? E 30 anni?</li>
<li>Guardando <span class="math inline">\(R^2\)</span>, l’età della madre vi sembra un buon predittore?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Soluzione — Esercizio 2">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Soluzione — Esercizio 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>m_age <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> mom_age, <span class="at">data =</span> kidiq)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m_age)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)     mom_age 
 70.9569209   0.6951862 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_age)<span class="sc">$</span>r.squared</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.008463666</code></pre>
</div>
</div>
<ol type="a">
<li><span class="math inline">\(\hat{Y} = 70.96 + 0.70 \cdot \text{mom\_age}\)</span>.</li>
<li>Per ogni anno in più della madre, il punteggio atteso del bambino aumenta in media di 0.70 punti.</li>
<li>Possiamo calcolarli a mano oppure, meglio, con <code>predict()</code>:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m_age, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">mom_age =</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">30</span>)))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2 
84.86064 91.81251 </code></pre>
</div>
</div>
<ol start="4" type="a">
<li><span class="math inline">\(R^2 \approx 0.009\)</span>: l’età della madre spiega meno dell’1% della variabilità dei punteggi. La pendenza è positiva ma il predittore, da solo, è debolissimo — un buon promemoria del fatto che un coefficiente “significativo o quasi” non implica un modello <em>utile</em>.</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="✏️ Esercizio 3 — Intervalli di confidenza">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✏️ Esercizio 3 — Intervalli di confidenza
</div>
</div>
<div class="callout-body-container callout-body">
<p>Il p-value non è l’unico modo (e nemmeno il migliore) per quantificare l’incertezza. Con la funzione <code>confint()</code> calcolate l’intervallo di confidenza al 95% per i coefficienti di <code>m1</code>. Come lo interpretate, in particolare per <code>mom_iq</code>? L’intervallo contiene lo zero?</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Soluzione — Esercizio 3">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Soluzione — Esercizio 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m1)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %     97.5 %
(Intercept) 14.1692789 37.4302768
mom_iq       0.4949534  0.7249957</code></pre>
</div>
</div>
<p>L’intervallo per <code>mom_iq</code> va da circa 0.50 a 0.73: i dati sono compatibili con un effetto del QI della madre compreso tra mezzo punto e tre quarti di punto per ogni punto di QI. Lo zero è ben lontano dall’intervallo, coerentemente con il p-value piccolissimo visto nel <code>summary()</code>. Notate quanto è più informativo dell’enunciato “p &lt; .05”: l’intervallo ci dice <em>quanto grande</em> è plausibilmente l’effetto.</p>
</div>
</div>
</div>
</section>
<section id="sec-diagnostica" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="sec-diagnostica"><span class="header-section-number">2.5</span> La diagnostica grafica</h2>
<p>Applicando <code>plot()</code> a un oggetto <code>lm</code> otteniamo quattro grafici diagnostici, che servono a controllare le assunzioni della <a href="#sec-assunzioni" class="quarto-xref">Sezione&nbsp;1.1</a>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m1)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/m1-diag-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><strong>Residuals vs Fitted</strong>: i residui contro i valori previsti. Se la relazione è davvero lineare, i punti si dispongono <em>a caso</em> attorno allo zero, senza curvature (linearità) né forme a imbuto (omoschedasticità).</li>
<li><strong>Normal Q-Q</strong>: confronta i quantili dei residui standardizzati con quelli di una normale; se l’assunzione di normalità regge, i punti stanno sulla diagonale.</li>
<li><strong>Scale-Location</strong>: versione “stabilizzata” del primo grafico, utile per vedere se la variabilità dei residui cresce con i valori previsti (eteroschedasticità).</li>
<li><strong>Residuals vs Leverage</strong>: evidenzia osservazioni con grande <em>leva</em> e grande residuo, cioè i potenziali <strong>casi influenti</strong> (ne parleremo nella <a href="#sec-anomali" class="quarto-xref">Sezione&nbsp;5.4</a>, insieme alla distanza di Cook).</li>
</ul>
<p>R etichetta automaticamente i casi più estremi (qui 87, 273, 286): non sono necessariamente un problema, ma meritano un’occhiata.</p>
</section>
<section id="sec-dicotomico" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="sec-dicotomico"><span class="header-section-number">2.6</span> Un predittore dicotomico</h2>
<p>Vogliamo ora valutare se il <strong>livello di istruzione della madre</strong> (diplomata o no) è predittivo del punteggio del bambino. Il predittore è un <code>factor</code> con due livelli, quindi R costruisce per noi la dummy <span class="math inline">\(D\)</span> (0 = non diplomata, 1 = diplomata):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> mom_hs, <span class="at">data =</span> kidiq)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kid_score <span class="sc">~</span> mom_hs, <span class="at">data =</span> kidiq,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Diploma della madre"</span>, <span class="at">ylab =</span> <span class="st">"Punteggio del bambino"</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/m2-boxplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>(Con un predittore <code>factor</code>, <code>plot()</code> produce automaticamente dei boxplot.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m2)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)     mom_hs1 
   77.54839    11.77126 </code></pre>
</div>
</div>
<p>L’equazione di regressione è</p>
<p><span class="math display">\[
\hat{Y} = 77.55 + 11.77 D
\]</span></p>
<p>L’interpretazione, con una dummy, è in termini di <strong>medie di gruppo</strong>:</p>
<ul>
<li><span class="math inline">\(\beta_0 = 77.55\)</span>: punteggio medio previsto quando <span class="math inline">\(D = 0\)</span>, cioè la media dei bambini con madre <strong>non</strong> diplomata;</li>
<li><span class="math inline">\(\beta_1 = 11.77\)</span>: la <strong>differenza</strong> tra le medie dei due gruppi. I figli di madri diplomate ottengono in media 11.77 punti in più (<span class="math inline">\(77.55 + 11.77 = 89.32\)</span>).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = kid_score ~ mom_hs, data = kidiq)

Residuals:
   Min     1Q Median     3Q    Max 
-57.55 -13.32   2.68  14.68  58.45 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   77.548      2.059  37.670  &lt; 2e-16 ***
mom_hs1       11.771      2.322   5.069 5.96e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 19.85 on 432 degrees of freedom
Multiple R-squared:  0.05613,   Adjusted R-squared:  0.05394 
F-statistic: 25.69 on 1 and 432 DF,  p-value: 5.957e-07</code></pre>
</div>
</div>
<p>Il test <span class="math inline">\(t\)</span> su <code>mom_hs1</code> ci dice che la differenza tra i due gruppi è statisticamente significativa, ma <span class="math inline">\(R^2 \approx 0.056\)</span>: il diploma della madre, da solo, spiega poco della variabilità dei punteggi.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="✏️ Esercizio 4 — Regressione e medie di gruppo">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✏️ Esercizio 4 — Regressione e medie di gruppo
</div>
</div>
<div class="callout-body-container callout-body">
<p>Verificate “a mano” l’interpretazione dei coefficienti di <code>m2</code>:</p>
<ol type="a">
<li>calcolate la media di <code>kid_score</code> separatamente per i due gruppi di <code>mom_hs</code> (suggerimento: <code>tapply()</code>);</li>
<li>confrontate le medie ottenute con i coefficienti del modello;</li>
<li>(extra) confrontate l’output di <code>summary(m2)</code> con quello di un test <span class="math inline">\(t\)</span> a varianze uguali: <code>t.test(kid_score ~ mom_hs, data = kidiq, var.equal = TRUE)</code>. Che cosa notate?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Soluzione — Esercizio 4">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Soluzione — Esercizio 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>medie <span class="ot">&lt;-</span> <span class="fu">tapply</span>(kidiq<span class="sc">$</span>kid_score, kidiq<span class="sc">$</span>mom_hs, mean)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>medie</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       0        1 
77.54839 89.31965 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>medie[<span class="dv">2</span>] <span class="sc">-</span> medie[<span class="dv">1</span>]</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
11.77126 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m2)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)     mom_hs1 
   77.54839    11.77126 </code></pre>
</div>
</div>
<p>La media del gruppo 0 (77.55) coincide con l’intercetta e la differenza tra le medie (11.77) coincide con il coefficiente della dummy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(kid_score <span class="sc">~</span> mom_hs, <span class="at">data =</span> kidiq, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  kid_score by mom_hs
t = -5.0685, df = 432, p-value = 5.957e-07
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -16.335924  -7.206598
sample estimates:
mean in group 0 mean in group 1 
       77.54839        89.31965 </code></pre>
</div>
</div>
<p>La statistica <span class="math inline">\(t\)</span> e il p-value sono identici (a parte il segno, che dipende solo dall’ordine dei gruppi) a quelli del coefficiente <code>mom_hs1</code> nel <code>summary(m2)</code>: il test <span class="math inline">\(t\)</span> per due gruppi indipendenti <strong>è</strong> un modello lineare con un predittore dicotomico. Molti dei test “classici” sono casi particolari del modello lineare.</p>
</div>
</div>
</div>
</section>
</section>
<section id="la-regressione-multipla" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> La regressione multipla</h1>
<p>Quando il modello ha più predittori, la formulazione può essere scritta:</p>
<p><strong>1. in forma matriciale:</strong></p>
<p><span class="math display">\[
Y = X\beta + \epsilon
\]</span></p>
<p><strong>2. in forma estesa:</strong></p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \ldots + \beta_k X_k + \epsilon
\]</span></p>
<p>Quando il modello ha più predittori (quantitativi e/o categoriali) e una sola variabile dipendente quantitativa <span class="math inline">\(Y\)</span>, si parla di <strong>regressione lineare multipla</strong>.</p>
<section id="un-esempio-con-due-predittori" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="un-esempio-con-due-predittori"><span class="header-section-number">3.1</span> Un esempio con due predittori</h2>
<p>Consideriamo un modello che predice il punteggio del bambino a partire dal QI <strong>e</strong> dal livello di istruzione della madre. In R basta sommare i predittori nella formula:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> mom_iq <span class="sc">+</span> mom_hs, <span class="at">data =</span> kidiq)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m3)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)      mom_iq     mom_hs1 
  25.731538    0.563906    5.950117 </code></pre>
</div>
</div>
<p>L’equazione di regressione è</p>
<p><span class="math display">\[
\hat{Y} = 25.73 + 0.56 X + 5.95 D
\]</span></p>
<p>Poiché <span class="math inline">\(D \in \{0, 1\}\)</span>, graficamente otteniamo <strong>due rette parallele</strong>: stessa pendenza (0.56), intercette diverse (25.73 per le madri non diplomate, <span class="math inline">\(25.73 +
5.95 = 31.68\)</span> per le diplomate):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>cf <span class="ot">&lt;-</span> <span class="fu">coef</span>(m3)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(kidiq, <span class="fu">aes</span>(<span class="at">x =</span> mom_iq, <span class="at">y =</span> kid_score, <span class="at">colour =</span> mom_hs)) <span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> cf[<span class="dv">1</span>],         <span class="at">slope =</span> cf[<span class="dv">2</span>], <span class="at">colour =</span> <span class="st">"#F8766D"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> cf[<span class="dv">1</span>] <span class="sc">+</span> cf[<span class="dv">3</span>], <span class="at">slope =</span> cf[<span class="dv">2</span>], <span class="at">colour =</span> <span class="st">"#00BFC4"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"QI della madre"</span>, <span class="at">y =</span> <span class="st">"Punteggio del bambino"</span>, <span class="at">colour =</span> <span class="st">"Diploma"</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/m3-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>L’interpretazione dei coefficienti cambia in modo sottile ma importante: ogni coefficiente esprime l’effetto di quel predittore <strong>a parità degli altri</strong>. Ad esempio, <span class="math inline">\(\beta_1 = 0.56\)</span> è l’effetto del QI della madre <em>a parità di livello di istruzione</em>.</p>
</section>
<section id="lanalisi-degli-effetti" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="lanalisi-degli-effetti"><span class="header-section-number">3.2</span> L’analisi degli effetti</h2>
<p>Con <code>anova()</code> otteniamo la scomposizione della variabilità spiegata dai singoli effetti del modello:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m3)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: kid_score
           Df Sum Sq Mean Sq  F value    Pr(&gt;F)    
mom_iq      1  36249   36249 110.2114 &lt; 2.2e-16 ***
mom_hs      1   2380    2380   7.2369  0.007419 ** 
Residuals 431 141757     329                       
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)<span class="sc">$</span>r.squared</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2141465</code></pre>
</div>
</div>
<p>Entrambi gli effetti risultano significativi e il modello spiega circa il 21.4% della variabilità dei punteggi (era il 20.1% con il solo QI: l’istruzione della madre aggiunge poco, una volta tenuto conto del QI).</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Avviso
</div>
</div>
<div class="callout-body-container callout-body">
<p>Attenzione: <code>anova()</code> usa somme dei quadrati <strong>sequenziali</strong> (Tipo I): l’ordine in cui i predittori entrano nella formula può cambiare i risultati, quando i predittori sono correlati tra loro.</p>
</div>
</div>
</section>
<section id="la-rappresentazione-grafica-degli-effetti" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="la-rappresentazione-grafica-degli-effetti"><span class="header-section-number">3.3</span> La rappresentazione grafica degli effetti</h2>
<p>Per visualizzare gli effetti stimati dal modello esistono comodi pacchetti dedicati. Con <strong>sjPlot</strong>:</p>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m3, <span class="at">type =</span> <span class="st">"eff"</span>, <span class="at">terms =</span> <span class="st">"mom_iq"</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m3, <span class="at">type =</span> <span class="st">"eff"</span>, <span class="at">terms =</span> <span class="st">"mom_hs"</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="bayes_files/figure-html/m3-sjplot-1.png" class="img-fluid" width="672"></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="bayes_files/figure-html/m3-sjplot-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<p>Con <strong>effects</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">allEffects</span>(m3))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/m3-effects-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Entrambi mostrano l’effetto di ciascun predittore <em>tenendo gli altri fissi</em> (ai loro valori medi o di riferimento), con le relative bande di confidenza.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="✏️ Esercizio 5 — Regressione multipla">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✏️ Esercizio 5 — Regressione multipla
</div>
</div>
<div class="callout-body-container callout-body">
<p>Stimate un modello con <code>mom_iq</code> e <code>mom_age</code> come predittori di <code>kid_score</code>.</p>
<ol type="a">
<li>Scrivete l’equazione di regressione.</li>
<li>Confrontate il coefficiente di <code>mom_iq</code> con quello che aveva nel modello semplice <code>m1</code>: è cambiato molto?</li>
<li>Confrontate l’<span class="math inline">\(R^2\)</span> con quello di <code>m1</code>: quanto aggiunge l’età della madre?</li>
<li>Disegnate gli effetti del modello con <code>plot(allEffects(...))</code>.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Soluzione — Esercizio 5">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Soluzione — Esercizio 5
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>m5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> mom_iq <span class="sc">+</span> mom_age, <span class="at">data =</span> kidiq)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m5)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)      mom_iq     mom_age 
 17.5962491   0.6035720   0.3881286 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m5)<span class="sc">$</span>r.squared</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2035673</code></pre>
</div>
</div>
<ol type="a">
<li><span class="math inline">\(\hat{Y} = 17.60 + 0.60 \cdot \text{mom\_iq} + 0.39 \cdot \text{mom\_age}\)</span>.</li>
<li>Il coefficiente di <code>mom_iq</code> passa da 0.610 a 0.604: praticamente invariato (QI ed età della madre sono poco correlati, quindi i loro effetti non si “rubano” variabilità a vicenda).</li>
<li><span class="math inline">\(R^2\)</span> passa da 0.201 a 0.204: l’età della madre, a parità di QI, aggiunge pochissimo.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">allEffects</span>(m5))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/sol-es5-eff-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Notate la diversa ampiezza delle bande di confidenza: l’effetto del QI è stimato con molta più precisione di quello dell’età.</p>
</div>
</div>
</div>
</section>
</section>
<section id="gli-effetti-di-interazione" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Gli effetti di interazione</h1>
<p>Nel modello <code>m3</code> abbiamo imposto che l’effetto del QI fosse <strong>lo stesso</strong> nei due gruppi di madri (rette parallele). Ma potrebbe non essere così: introduciamo allora l’<strong>interazione</strong> tra i predittori, che in R si indica con <code>*</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> mom_iq <span class="sc">*</span> mom_hs, <span class="at">data =</span> kidiq)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m4)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept)         mom_iq        mom_hs1 mom_iq:mom_hs1 
   -11.4820211      0.9688892     51.2682234     -0.4842747 </code></pre>
</div>
</div>
<p>La formula <code>mom_iq * mom_hs</code> è una scorciatoia per <code>mom_iq + mom_hs + mom_iq:mom_hs</code>: effetti principali <strong>più</strong> interazione. L’equazione di regressione diventa</p>
<p><span class="math display">\[
\hat{Y} = -11.48 + 0.97 X + 51.27 D - 0.48\, DX
\]</span></p>
<p>Il termine <span class="math inline">\(DX\)</span> (prodotto tra dummy e QI) permette alle due rette di avere <strong>pendenze diverse</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(kidiq, <span class="fu">aes</span>(<span class="at">x =</span> mom_iq, <span class="at">y =</span> kid_score, <span class="at">colour =</span> mom_hs)) <span class="sc">+</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"QI della madre"</span>, <span class="at">y =</span> <span class="st">"Punteggio del bambino"</span>, <span class="at">colour =</span> <span class="st">"Diploma"</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/m4-plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Sostituendo i valori di <span class="math inline">\(D\)</span> si ottengono le equazioni delle due rette:</p>
<ul>
<li>madri non diplomate (<span class="math inline">\(D = 0\)</span>): <span class="math inline">\(\hat{Y} = -11.48 + 0.97 X\)</span></li>
<li>madri diplomate (<span class="math inline">\(D = 1\)</span>): <span class="math inline">\(\hat{Y} = (-11.48 + 51.27) + (0.97 - 0.48) X = 39.79 + 0.49 X\)</span></li>
</ul>
<p>L’interpretazione: tra le madri non diplomate il QI “pesa” molto di più (quasi un punto per punto di QI), mentre tra le diplomate la relazione è circa la metà. Con un’interazione, gli effetti principali <strong>non si interpretano più da soli</strong>: l’effetto di un predittore dipende dal livello dell’altro.</p>
<section id="lanalisi-degli-effetti-1" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="lanalisi-degli-effetti-1"><span class="header-section-number">4.1</span> L’analisi degli effetti</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m4)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: kid_score
               Df Sum Sq Mean Sq  F value    Pr(&gt;F)    
mom_iq          1  36249   36249 112.2346 &lt; 2.2e-16 ***
mom_hs          1   2380    2380   7.3698  0.006900 ** 
mom_iq:mom_hs   1   2878    2878   8.9123  0.002994 ** 
Residuals     430 138879     323                       
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m4)<span class="sc">$</span>r.squared</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2301036</code></pre>
</div>
</div>
<p>Anche l’interazione risulta significativa, e il modello spiega circa il 23% della variabilità.</p>
</section>
<section id="la-rappresentazione-grafica" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="la-rappresentazione-grafica"><span class="header-section-number">4.2</span> La rappresentazione grafica</h2>
<p>Con <strong>sjPlot</strong> (<code>type = "int"</code> mostra proprio l’interazione):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m4, <span class="at">type =</span> <span class="st">"int"</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/m4-sjplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Con <strong>effects</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">allEffects</span>(m4))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/m4-effects-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="✏️ Esercizio 6 — Interpretare un'interazione">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✏️ Esercizio 6 — Interpretare un’interazione
</div>
</div>
<div class="callout-body-container callout-body">
<p>Usando i coefficienti di <code>m4</code> (senza usare <code>predict()</code>, prima):</p>
<ol type="a">
<li>calcolate il punteggio previsto per un bambino con madre <strong>non diplomata</strong> con QI = 100;</li>
<li>idem, ma con madre <strong>diplomata</strong> con QI = 100;</li>
<li>verificate i risultati con <code>predict()</code>;</li>
<li>per quale valore di QI le due rette si incrociano?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Soluzione — Esercizio 6">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Soluzione — Esercizio 6
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><span class="math inline">\(D = 0\)</span>: <span class="math inline">\(\hat{Y} = -11.48 + 0.97 \cdot 100 = 85.4\)</span>.</li>
<li><span class="math inline">\(D = 1\)</span>: <span class="math inline">\(\hat{Y} = 39.79 + 0.49 \cdot 100 = 88.3\)</span>.</li>
<li>Con <code>predict()</code>:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m4, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">mom_iq =</span> <span class="fu">c</span>(<span class="dv">100</span>, <span class="dv">100</span>),</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">mom_hs =</span> <span class="fu">factor</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2 
85.40690 88.24766 </code></pre>
</div>
</div>
<ol start="4" type="a">
<li>Le rette si incrociano dove <span class="math inline">\(-11.48 + 0.97X = 39.79 + 0.49X\)</span>, cioè <span class="math inline">\(X = 51.27 / 0.48 \approx 106\)</span> (provate a ricavarlo: è il rapporto tra il coefficiente della dummy e quello dell’interazione, cambiato di segno). Sotto QI ≈ 106 i figli di madri diplomate hanno punteggi attesi più alti, sopra la relazione si inverte — anche se, guardando il grafico, le due rette oltre quel punto sono molto vicine e le bande di confidenza si sovrappongono.</li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="sec-adattamento" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> La valutazione dell’adattamento</h1>
<p>Stimare un modello è facile; la domanda successiva è: <strong>quanto è buono?</strong> In questa sezione vediamo tre strumenti complementari: l’analisi dei residui, il <em>predictive check</em> e gli indici di variabilità spiegata.</p>
<section id="i-residui-del-modello-gli-scarti" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="i-residui-del-modello-gli-scarti"><span class="header-section-number">5.1</span> I residui del modello: gli scarti</h2>
<p>Per ragionare sull’adattamento conviene partire da un piccolo esempio simulato: una misura di stile genitoriale (<code>ParSty</code>) e una di comportamento del bambino (<code>ChildBeh</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">8</span>)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>ParSty   <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">20</span>, <span class="dv">5</span>, <span class="dv">20</span>)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>ChildBeh <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">+</span> <span class="fl">1.1</span> <span class="sc">*</span> ParSty <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">20</span>, <span class="dv">0</span>, <span class="fl">2.5</span>)</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(ChildBeh <span class="sc">~</span> ParSty)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Data l’osservazione empirica <span class="math inline">\(y_i\)</span>, possiamo individuare <strong>tre tipi di deviazione o scarti</strong>:</p>
<ol type="1">
<li>lo scarto del punto osservato <span class="math inline">\(y_i\)</span> dalla media dei punteggi <span class="math inline">\(\bar{y}\)</span>: <span class="math inline">\(\;y_i - \bar{y}\)</span>;</li>
<li>lo scarto del punto teorico <span class="math inline">\(\hat{y}_i\)</span> (sulla retta) dalla media <span class="math inline">\(\bar{y}\)</span>: <span class="math inline">\(\;\hat{y}_i - \bar{y}\)</span>;</li>
<li>lo scarto del punto osservato <span class="math inline">\(y_i\)</span> dal suo corrispondente teorico sulla retta di regressione: <span class="math inline">\(\;y_i - \hat{y}_i\)</span> — questo è il <strong>residuo</strong>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">1</span>))</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>titoli <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">expression</span>(y[i] <span class="sc">-</span> <span class="fu">bar</span>(y)),</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">expression</span>(<span class="fu">hat</span>(y)[i] <span class="sc">-</span> <span class="fu">bar</span>(y)),</span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>            <span class="fu">expression</span>(y[i] <span class="sc">-</span> <span class="fu">hat</span>(y)[i]))</span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (tipo <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) {</span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(ParSty, ChildBeh, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"grey40"</span>, <span class="at">main =</span> titoli[tipo])</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">mean</span>(ChildBeh), <span class="at">lty =</span> <span class="dv">2</span>)          <span class="co"># media di Y</span></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(mod, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)           <span class="co"># retta di regressione</span></span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (tipo <span class="sc">==</span> <span class="dv">1</span>) <span class="fu">segments</span>(ParSty, <span class="fu">mean</span>(ChildBeh), ParSty, ChildBeh,      <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (tipo <span class="sc">==</span> <span class="dv">2</span>) <span class="fu">segments</span>(ParSty, <span class="fu">mean</span>(ChildBeh), ParSty, <span class="fu">fitted</span>(mod),   <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (tipo <span class="sc">==</span> <span class="dv">3</span>) <span class="fu">segments</span>(ParSty, <span class="fu">fitted</span>(mod),   ParSty, ChildBeh,       <span class="at">col =</span> <span class="st">"red"</span>)</span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/scarti-plot-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nel primo pannello gli scarti ignorano completamente il modello (distanze dalla media); nel secondo ci sono le distanze <em>spiegate</em> dalla retta; nel terzo ciò che resta: i residui.</p>
<p>In R i residui di un modello si ottengono con <code>residuals()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">residuals</span>(mod), <span class="dv">3</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     1      2      3      4      5      6      7      8      9     10     11 
-2.102 -0.177  1.760 -2.933 -0.424 -1.546  3.096  0.389  4.519 -0.310  2.980 
    12     13     14     15     16     17     18     19     20 
-1.254 -1.295  0.067  3.260 -1.712 -4.122  4.125  0.787 -5.105 </code></pre>
</div>
</div>
</section>
<section id="le-devianze" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="le-devianze"><span class="header-section-number">5.2</span> Le devianze</h2>
<p>Sommando i quadrati degli scarti otteniamo tre nuove quantità:</p>
<ul>
<li><strong>Devianza totale</strong>: somma dei quadrati degli scarti delle osservazioni dalla media <span class="math display">\[\text{SS}_{T} = \sum_i (y_i - \bar{y})^2\]</span></li>
<li><strong>Devianza di regressione</strong> (o spiegata): somma dei quadrati degli scarti dei punti sulla retta dalla media <span class="math display">\[\text{SS}_{R} = \sum_i (\hat{y}_i - \bar{y})^2\]</span></li>
<li><strong>Devianza residua</strong>: somma dei quadrati degli scarti delle osservazioni dai punti sulla retta <span class="math display">\[\text{SS}_{E} = \sum_i (y_i - \hat{y}_i)^2\]</span></li>
</ul>
<p>È facile verificare che</p>
<p><span class="math display">\[
\sum_i (\hat{y}_i - \bar{y})^2 + \sum_i (y_i - \hat{y}_i)^2 = \sum_i (y_i - \bar{y})^2
\]</span></p>
<p>ossia che la <strong>devianza totale è la somma delle altre due</strong>: <span class="math inline">\(\text{SS}_T = \text{SS}_R + \text{SS}_E\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>L’algoritmo di stima dei parametri <span class="math inline">\(\beta_0\)</span> e <span class="math inline">\(\beta_1\)</span> (il metodo dei <strong>minimi quadrati</strong>, <em>Ordinary Least Squares</em>) ha come obiettivo proprio la minimizzazione della devianza residua: tra tutte le rette possibili, <code>lm()</code> sceglie quella che rende minima <span class="math inline">\(\sum_i (y_i - \hat{y}_i)^2\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="✏️ Esercizio 7 — Verificare la scomposizione della devianza">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✏️ Esercizio 7 — Verificare la scomposizione della devianza
</div>
</div>
<div class="callout-body-container callout-body">
<p>Torniamo al modello <code>m1</code> (<code>kid_score ~ mom_iq</code>).</p>
<ol type="a">
<li>Calcolate i residui “a mano” come <code>kidiq$kid_score - fitted(m1)</code> e verificate che coincidono con <code>residuals(m1)</code>.</li>
<li>Calcolate le tre devianze e verificate che <span class="math inline">\(\text{SS}_T = \text{SS}_R + \text{SS}_E\)</span>.</li>
<li>Calcolate <span class="math inline">\(R^2 = \text{SS}_R / \text{SS}_T\)</span> e confrontatelo con <code>summary(m1)$r.squared</code>.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Soluzione — Esercizio 7">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Soluzione — Esercizio 7
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>res_mano <span class="ot">&lt;-</span> kidiq<span class="sc">$</span>kid_score <span class="sc">-</span> <span class="fu">fitted</span>(m1)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(res_mano, <span class="fu">residuals</span>(m1))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>SST <span class="ot">&lt;-</span> <span class="fu">sum</span>((kidiq<span class="sc">$</span>kid_score <span class="sc">-</span> <span class="fu">mean</span>(kidiq<span class="sc">$</span>kid_score))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>SSR <span class="ot">&lt;-</span> <span class="fu">sum</span>((<span class="fu">fitted</span>(m1) <span class="sc">-</span> <span class="fu">mean</span>(kidiq<span class="sc">$</span>kid_score))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">residuals</span>(m1)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">SST =</span> SST, <span class="at">SSR =</span> SSR, <span class="at">SSE =</span> SSE)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      SST       SSR       SSE 
180386.16  36248.82 144137.34 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>SSR <span class="sc">+</span> SSE        <span class="co"># = SST</span></span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 180386.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>SSR <span class="sc">/</span> SST</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2009512</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)<span class="sc">$</span>r.squared</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2009512</code></pre>
</div>
</div>
<p>Tutto torna: i residui coincidono, la devianza totale è la somma delle altre due e il rapporto <span class="math inline">\(\text{SS}_R / \text{SS}_T\)</span> è esattamente l’<span class="math inline">\(R^2\)</span> riportato da <code>summary()</code>.</p>
</div>
</div>
</div>
</section>
<section id="la-valutazione-dei-residui" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="la-valutazione-dei-residui"><span class="header-section-number">5.3</span> La valutazione dei residui</h2>
<p>I residui del modello rappresentano le differenze tra i valori osservati (<span class="math inline">\(y\)</span>) e i valori attesi dal modello (<span class="math inline">\(\hat{y}\)</span>, sulla retta):</p>
<p><span class="math display">\[
r_i = y_i - X_i\hat{\beta}
\]</span></p>
<p>Rappresentando graficamente la distribuzione dei residui possiamo valutare la bontà del modello. La regola d’oro:</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>Se il modello è buono, i residui devono distribuirsi <strong>a caso</strong>: nessuna struttura, nessuna curvatura, nessun imbuto, nessun gruppo di punti che si comporta in modo diverso dagli altri. Qualsiasi <em>pattern</em> nei residui è informazione che il modello non ha catturato.</p>
</div>
</div>
</section>
<section id="sec-anomali" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="sec-anomali"><span class="header-section-number">5.4</span> Casi anomali e casi influenti</h2>
<p>Non tutte le osservazioni “strane” sono uguali. Conviene distinguere:</p>
<ul>
<li><strong>outlier</strong>: un’osservazione con <span class="math inline">\(Y\)</span> anomalo rispetto a ciò che il modello prevede per il suo <span class="math inline">\(X\)</span> (residuo grande);</li>
<li><strong>caso a leva alta</strong> (<em>leverage</em>): un’osservazione con <span class="math inline">\(X\)</span> estremo, lontano dal grosso dei dati — <em>potenzialmente</em> influente;</li>
<li><strong>caso influente</strong>: un’osservazione che, da sola, <strong>cambia sensibilmente le stime</strong> del modello. Tipicamente: leva alta <strong>e</strong> residuo grande insieme.</li>
</ul>
<p>Vediamolo con dati simulati: in ciascun pannello aggiungiamo ai dati (grigi) un solo punto rosso e confrontiamo la retta stimata con il punto (rossa, continua) e senza (nera, tratteggiata):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20</span>)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">25</span>, <span class="dv">10</span>, <span class="fl">1.5</span>)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">+</span> x <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">25</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>extra  <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">22</span>),   <span class="co"># outlier: X centrale, Y anomalo</span></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>                <span class="fu">c</span>(<span class="dv">18</span>, <span class="dv">20</span>),   <span class="co"># leva alta: X estremo, Y coerente</span></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>                <span class="fu">c</span>(<span class="dv">18</span>, <span class="dv">9</span>))    <span class="co"># outlier influente: X estremo, Y anomalo</span></span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>titoli <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Outlier"</span>, <span class="st">"Caso a leva alta"</span>, <span class="st">"Outlier influente"</span>)</span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">1</span>))</span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) {</span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a>  xx <span class="ot">&lt;-</span> <span class="fu">c</span>(x, extra[i, <span class="dv">1</span>]); yy <span class="ot">&lt;-</span> <span class="fu">c</span>(y, extra[i, <span class="dv">2</span>])</span>
<span id="cb80-13"><a href="#cb80-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(xx, yy, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"grey60"</span>, <span class="dv">25</span>), <span class="st">"red"</span>),</span>
<span id="cb80-14"><a href="#cb80-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"X"</span>, <span class="at">ylab =</span> <span class="st">"Y"</span>, <span class="at">main =</span> titoli[i])</span>
<span id="cb80-15"><a href="#cb80-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x),   <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)               <span class="co"># senza il punto</span></span>
<span id="cb80-16"><a href="#cb80-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="fu">lm</span>(yy <span class="sc">~</span> xx), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)           <span class="co"># con il punto</span></span>
<span id="cb80-17"><a href="#cb80-17" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/anomali-plot-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>l’<strong>outlier</strong> con <span class="math inline">\(X\)</span> centrale sposta un po’ l’intercetta ma quasi per niente la pendenza;</li>
<li>il caso a <strong>leva alta</strong> ma coerente con la retta non cambia praticamente nulla (anzi, “stabilizza” la stima);</li>
<li>l’<strong>outlier influente</strong> (X estremo + Y anomalo) ruota vistosamente la retta: è questo il caso davvero pericoloso.</li>
</ul>
<p>Il quarto pannello della diagnostica (<code>Residuals vs Leverage</code>, con la <strong>distanza di Cook</strong>) serve proprio a individuare questi casi. Guardiamo la diagnostica completa del modello con interazione:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m4)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/m4-diag-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="il-predictive-check" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="il-predictive-check"><span class="header-section-number">5.5</span> Il predictive check</h2>
<p>Il metodo più importante per valutare l’adattamento di un modello consiste nel <strong>simulare dati dal modello</strong> e confrontarli con i dati osservati:</p>
<ul>
<li>se il modello è buono, i dati simulati dovrebbero assomigliare a quelli osservati;</li>
<li>viceversa, se il modello genera dati molto diversi da quelli osservati, non è un buon modello per quei dati.</li>
</ul>
<p>Il pacchetto <strong>performance</strong> rende l’operazione immediata:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">check_predictions</span>(m4)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/m4-ppcheck-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ogni curva sottile è la distribuzione di un dataset <em>simulato</em> dal modello; la curva in evidenza è quella dei dati osservati. Qui le curve simulate ricalcano abbastanza bene quella osservata: il modello riproduce in modo ragionevole la forma della distribuzione dei punteggi.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="✏️ Esercizio 8 — Predictive check a confronto">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✏️ Esercizio 8 — Predictive check a confronto
</div>
</div>
<div class="callout-body-container callout-body">
<p>Eseguite <code>check_predictions()</code> sul modello <code>m2</code> (solo <code>mom_hs</code>) e sul modello <code>m4</code> (QI × diploma). Quale dei due riproduce meglio i dati osservati? Era prevedibile, guardando gli <span class="math inline">\(R^2\)</span>?</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Soluzione — Esercizio 8">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Soluzione — Esercizio 8
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_predictions</span>(m2)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/sol-es8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Con il solo diploma della madre il modello può prevedere solo <strong>due</strong> valori attesi (uno per gruppo): le distribuzioni simulate risultano più “lisce” e meno capaci di seguire la forma dei dati osservati rispetto a <code>m4</code>, che usando anche il QI genera una gamma di previsioni molto più ricca. Coerente con gli <span class="math inline">\(R^2\)</span>: 0.056 contro 0.230. Il predictive check rende <em>visibile</em> quello che gli indici riassumono in un numero.</p>
</div>
</div>
</div>
</section>
<section id="sec-variabilita" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="sec-variabilita"><span class="header-section-number">5.6</span> Variabilità residua e variabilità spiegata</h2>
<section id="la-variabilità-residua-sigma" class="level3" data-number="5.6.1">
<h3 data-number="5.6.1" class="anchored" data-anchor-id="la-variabilità-residua-sigma"><span class="header-section-number">5.6.1</span> La variabilità residua: <span class="math inline">\(\sigma\)</span></h3>
<p>Il parametro <span class="math inline">\(\sigma\)</span> (<strong>Residual standard error</strong> nell’output di <code>summary()</code>) esprime la variabilità dei residui.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sigma</span>(m4)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 17.97147</code></pre>
</div>
</div>
<p>Nel modello <code>m4</code>, <span class="math inline">\(\sigma \approx 18\)</span> significa che il modello predice la variabile dipendente con un’accuratezza media di circa 18 punti: di tanto, in media, i punteggi osservati si discostano da quelli attesi. Sta a noi giudicare se, sulla scala della variabile, è una precisione accettabile.</p>
</section>
<section id="la-variabilità-spiegata-r2-e-eta2" class="level3" data-number="5.6.2">
<h3 data-number="5.6.2" class="anchored" data-anchor-id="la-variabilità-spiegata-r2-e-eta2"><span class="header-section-number">5.6.2</span> La variabilità spiegata: <span class="math inline">\(R^2\)</span> e <span class="math inline">\(\eta^2\)</span></h3>
<p>Il fit del modello può essere riassunto sfruttando la relazione tra devianza residua e devianza totale:</p>
<p><span class="math display">\[
R^2 = \frac{\text{SS}_R}{\text{SS}_T} = 1 - \frac{\text{SS}_E}{\text{SS}_T}
\]</span></p>
<ul>
<li>la proporzione di variabilità spiegata <strong>dal modello nel suo complesso</strong> è il <strong>coefficiente di determinazione</strong> <span class="math inline">\(R^2\)</span>;</li>
<li>la proporzione di variabilità spiegata <strong>da ciascun effetto</strong> si stima con <span class="math inline">\(\eta^2\)</span> (rapporto tra la devianza dell’effetto e quella totale), calcolabile dalla tabella ANOVA:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">anova</span>(m4)</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>eta2 <span class="ot">&lt;-</span> a<span class="sc">$</span><span class="st">"Sum Sq"</span> <span class="sc">/</span> <span class="fu">sum</span>(a<span class="sc">$</span><span class="st">"Sum Sq"</span>)</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">effetto =</span> <span class="fu">rownames</span>(a), <span class="at">eta2 =</span> <span class="fu">round</span>(eta2, <span class="dv">3</span>))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        effetto  eta2
1        mom_iq 0.201
2        mom_hs 0.013
3 mom_iq:mom_hs 0.016
4     Residuals 0.770</code></pre>
</div>
</div>
</section>
<section id="due-casi-particolari" class="level3" data-number="5.6.3">
<h3 data-number="5.6.3" class="anchored" data-anchor-id="due-casi-particolari"><span class="header-section-number">5.6.3</span> Due casi particolari</h3>
<p><strong>Caso 1: dipendenza funzionale perfetta.</strong> Tutti i punti giacciono esattamente sulla retta di regressione: tutte le differenze <span class="math inline">\(y_i - \hat{y}_i\)</span> sono nulle, quindi la devianza residua è zero e la devianza totale coincide con quella di regressione. <span class="math inline">\(R^2 = 1\)</span>.</p>
<p><strong>Caso 2: indipendenza.</strong> La retta di regressione coincide con la media di <span class="math inline">\(Y\)</span> (pendenza nulla): sono nulle tutte le differenze <span class="math inline">\(\hat{y}_i - \bar{y}\)</span>, la devianza di regressione è zero e la devianza totale coincide con quella residua. <span class="math inline">\(R^2 \approx 0\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>x  <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">30</span>, <span class="dv">5</span>, <span class="dv">20</span>)</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>y_perf <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">+</span> x                          <span class="co"># caso 1: nessun errore</span></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>y_indip <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">30</span>, <span class="dv">10</span>, <span class="dv">5</span>)              <span class="co"># caso 2: Y non dipende da X</span></span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">1</span>))</span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, y_perf, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">main =</span> <span class="fu">expression</span>(R<span class="sc">^</span><span class="dv">2</span> <span class="sc">==</span> <span class="dv">1</span>), <span class="at">xlab =</span> <span class="st">"X"</span>, <span class="at">ylab =</span> <span class="st">"Y"</span>)</span>
<span id="cb90-8"><a href="#cb90-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y_perf <span class="sc">~</span> x), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb90-9"><a href="#cb90-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, y_indip, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">main =</span> <span class="fu">expression</span>(R<span class="sc">^</span><span class="dv">2</span> <span class="sc">%~~%</span> <span class="dv">0</span>), <span class="at">xlab =</span> <span class="st">"X"</span>, <span class="at">ylab =</span> <span class="st">"Y"</span>)</span>
<span id="cb90-10"><a href="#cb90-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y_indip <span class="sc">~</span> x), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb90-11"><a href="#cb90-11" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">mean</span>(y_indip), <span class="at">lty =</span> <span class="dv">2</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/casi-particolari-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="✏️ Esercizio 9 — Da che cosa dipende R²?">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✏️ Esercizio 9 — Da che cosa dipende R²?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Simulate due dataset con la <strong>stessa</strong> relazione <span class="math inline">\(y = 2 + 0.5x + \epsilon\)</span> (<span class="math inline">\(n = 200\)</span>, <span class="math inline">\(x \sim \mathcal{N}(0,1)\)</span>), ma errori con deviazione standard diversa: <span class="math inline">\(\sigma = 0.5\)</span> nel primo e <span class="math inline">\(\sigma = 3\)</span> nel secondo.</p>
<ol type="a">
<li>Stimate i due modelli: le stime di <span class="math inline">\(\beta_1\)</span> sono simili?</li>
<li>Confrontate gli <span class="math inline">\(R^2\)</span>. Che cosa concludete sul rapporto tra “forza dell’effetto” e <span class="math inline">\(R^2\)</span>?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Soluzione — Esercizio 9">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Soluzione — Esercizio 9
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">200</span></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>y_preciso <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> x <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="fl">0.5</span>)</span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>y_rumoroso <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">+</span> <span class="fl">0.5</span> <span class="sc">*</span> x <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">3</span>)</span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a>mp <span class="ot">&lt;-</span> <span class="fu">lm</span>(y_preciso <span class="sc">~</span> x)</span>
<span id="cb92-8"><a href="#cb92-8" aria-hidden="true" tabindex="-1"></a>mr <span class="ot">&lt;-</span> <span class="fu">lm</span>(y_rumoroso <span class="sc">~</span> x)</span>
<span id="cb92-9"><a href="#cb92-9" aria-hidden="true" tabindex="-1"></a><span class="fu">rbind</span>(<span class="at">preciso  =</span> <span class="fu">c</span>(<span class="fu">coef</span>(mp), <span class="at">R2 =</span> <span class="fu">summary</span>(mp)<span class="sc">$</span>r.squared),</span>
<span id="cb92-10"><a href="#cb92-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">rumoroso =</span> <span class="fu">c</span>(<span class="fu">coef</span>(mr), <span class="at">R2 =</span> <span class="fu">summary</span>(mr)<span class="sc">$</span>r.squared))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         (Intercept)         x         R2
preciso     2.020935 0.4853728 0.45822805
rumoroso    2.094531 0.4072209 0.01731883</code></pre>
</div>
</div>
<p>Le stime di <span class="math inline">\(\beta_1\)</span> sono vicine al vero valore 0.5 in entrambi i casi, ma <span class="math inline">\(R^2\)</span> crolla da circa 0.46 a circa 0.02. <strong>Lo stesso effetto</strong> può produrre <span class="math inline">\(R^2\)</span> altissimi o bassissimi a seconda della variabilità residua: <span class="math inline">\(R^2\)</span> misura quanto il modello “copre” la variabilità di <span class="math inline">\(Y\)</span>, non quanto è grande o importante un coefficiente.</p>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="confronto-e-selezione-di-modelli" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Confronto e selezione di modelli</h1>
<blockquote class="blockquote">
<p><em>All models are wrong, but some are useful.</em> — George E. P. Box</p>
</blockquote>
<p>Lo scopo di un modello statistico è essenzialmente questo: a partire da un insieme di dati osservati, identificare il processo latente sottostante che li ha generati. L’obiettivo del ricercatore è individuare il modello migliore.</p>
<section id="i-problemi" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="i-problemi"><span class="header-section-number">6.1</span> I problemi</h2>
<p>Sembra semplice, ma:</p>
<ul>
<li>possono esistere <strong>molti modelli</strong> che spiegano gli stessi dati;</li>
<li>le <strong>variazioni casuali</strong> rendono difficile identificare il modello;</li>
<li>il <strong>modello vero potrebbe non essere</strong> tra quelli effettivamente messi alla prova.</li>
</ul>
<p>Un obiettivo realistico, quindi, è identificare il modello che rappresenta la <strong>migliore approssimazione</strong> al modello vero.</p>
</section>
<section id="loverfitting" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="loverfitting"><span class="header-section-number">6.2</span> L’overfitting</h2>
<p>C’è una tensione fondamentale tra due proprietà di un modello:</p>
<ul>
<li>la <strong>bontà di adattamento</strong> (<em>goodness of fit</em>): quanto bene il modello riproduce i dati <em>osservati</em> — e questa <strong>cresce sempre</strong> all’aumentare della complessità del modello;</li>
<li>la <strong>generalizzabilità</strong>: quanto bene il modello prevede dati <em>nuovi</em> — e questa cresce fino a un certo punto, poi peggiora (curva a U rovesciata; Pitt, Myung &amp; Zhang, 2002).</li>
</ul>
<p>Un modello troppo complesso finisce per adattarsi anche al <strong>rumore</strong> dei dati: è il fenomeno dell’<strong>overfitting</strong>.</p>
<blockquote class="blockquote">
<p><em>…fitting is easy; prediction is hard.</em> — Richard McElreath</p>
</blockquote>
<p>Vediamolo con un esempio classico (McElreath): volume cranico e massa corporea di sette specie di ominidi. Con 7 punti, un polinomio di grado 6 passa <em>esattamente</em> per tutti i punti:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>ominidi <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">specie   =</span> <span class="fu">c</span>(<span class="st">"afarensis"</span>, <span class="st">"africanus"</span>, <span class="st">"habilis"</span>, <span class="st">"boisei"</span>,</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>               <span class="st">"rudolfensis"</span>, <span class="st">"ergaster"</span>, <span class="st">"sapiens"</span>),</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">massa    =</span> <span class="fu">c</span>(<span class="fl">37.0</span>, <span class="fl">35.5</span>, <span class="fl">34.5</span>, <span class="fl">41.5</span>, <span class="fl">55.5</span>, <span class="fl">61.0</span>, <span class="fl">53.5</span>),</span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">cervello =</span> <span class="fu">c</span>(<span class="dv">438</span>, <span class="dv">452</span>, <span class="dv">612</span>, <span class="dv">521</span>, <span class="dv">752</span>, <span class="dv">871</span>, <span class="dv">1350</span>))</span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>r2 <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>, <span class="cf">function</span>(g)</span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>(<span class="fu">lm</span>(cervello <span class="sc">~</span> <span class="fu">poly</span>(massa, g), <span class="at">data =</span> ominidi))<span class="sc">$</span>r.squared)</span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(r2, <span class="dv">2</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.49 0.54 0.68 0.81 0.99 1.00</code></pre>
</div>
</div>
<p>L’<span class="math inline">\(R^2\)</span> sale monotonicamente con il grado del polinomio, fino a 1. Ma guardate <em>come</em> lo fa:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>griglia <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">massa =</span> <span class="fu">seq</span>(<span class="fl">34.5</span>, <span class="dv">61</span>, <span class="at">length.out =</span> <span class="dv">200</span>))</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">1</span>))</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (g <span class="cf">in</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">6</span>)) {</span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>  m <span class="ot">&lt;-</span> <span class="fu">lm</span>(cervello <span class="sc">~</span> <span class="fu">poly</span>(massa, g), <span class="at">data =</span> ominidi)</span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(cervello <span class="sc">~</span> massa, <span class="at">data =</span> ominidi, <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">500</span>, <span class="dv">1600</span>),</span>
<span id="cb96-7"><a href="#cb96-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"Massa corporea (kg)"</span>, <span class="at">ylab =</span> <span class="st">"Volume cranico (cc)"</span>,</span>
<span id="cb96-8"><a href="#cb96-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">paste0</span>(<span class="st">"Grado "</span>, g, <span class="st">" — R² = "</span>, <span class="fu">round</span>(<span class="fu">summary</span>(m)<span class="sc">$</span>r.squared, <span class="dv">2</span>)))</span>
<span id="cb96-9"><a href="#cb96-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(griglia<span class="sc">$</span>massa, <span class="fu">predict</span>(m, <span class="at">newdata =</span> griglia), <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb96-10"><a href="#cb96-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>, <span class="at">lty =</span> <span class="dv">3</span>)</span>
<span id="cb96-11"><a href="#cb96-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/overfit-plot-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Il polinomio di grado 6 ha <span class="math inline">\(R^2 = 1\)</span> ma, tra un punto e l’altro, arriva a prevedere un volume cranico <strong>negativo</strong>: si è adattato perfettamente ai dati e ha perso ogni capacità di generalizzare. Massimizzare il fit non è il criterio giusto per scegliere un modello: servono criteri che tengano conto anche della complessità.</p>
</section>
<section id="il-confronto-mediante-anova" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="il-confronto-mediante-anova"><span class="header-section-number">6.3</span> Il confronto mediante ANOVA</h2>
<p>Costruiamo una serie di modelli per i dati <code>kidiq</code>, dal modello <strong>nullo</strong> (solo intercetta) al modello con interazione:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>m0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> <span class="dv">1</span>,               <span class="at">data =</span> kidiq)</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> mom_iq,          <span class="at">data =</span> kidiq)</span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> mom_hs,          <span class="at">data =</span> kidiq)</span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> mom_iq <span class="sc">+</span> mom_hs, <span class="at">data =</span> kidiq)</span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> mom_iq <span class="sc">*</span> mom_hs, <span class="at">data =</span> kidiq)</span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m0, m1, m2, m3, m4)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: kid_score ~ 1
Model 2: kid_score ~ mom_iq
Model 3: kid_score ~ mom_hs
Model 4: kid_score ~ mom_iq + mom_hs
Model 5: kid_score ~ mom_iq * mom_hs
  Res.Df    RSS Df Sum of Sq        F    Pr(&gt;F)    
1    433 180386                                    
2    432 144137  1     36249 112.2346 &lt; 2.2e-16 ***
3    432 170261  0    -26124                       
4    431 141757  1     28504  88.2552 &lt; 2.2e-16 ***
5    430 138879  1      2878   8.9123  0.002994 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p><code>anova()</code> confronta ogni modello con il precedente tramite test <span class="math inline">\(F\)</span>: l’aggiunta di parametri riduce significativamente la devianza residua?</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Avviso
</div>
</div>
<div class="callout-body-container callout-body">
<p>Questo approccio funziona solo per modelli <strong>annidati</strong> (ogni modello deve essere un caso particolare del successivo). Guardate la terza riga: confrontando <code>m2</code> con <code>m1</code> otteniamo <code>Df = 0</code> e una somma dei quadrati <em>negativa</em> — un confronto privo di senso, perché <code>m1</code> e <code>m2</code> non sono annidati (nessuno dei due contiene l’altro). R esegue il calcolo lo stesso: sta a noi accorgerci del problema.</p>
</div>
</div>
</section>
<section id="aic-e-bic" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="aic-e-bic"><span class="header-section-number">6.4</span> AIC e BIC</h2>
<p>Due indici molto usati per il confronto fra modelli sono <strong>AIC</strong> (<em>Akaike Information Criterion</em>; Akaike, 1974) e <strong>BIC</strong> (<em>Bayesian Information Criterion</em>; Schwarz, 1978):</p>
<p><span class="math display">\[
\text{AIC} = -2\log\mathcal{L} + 2k
\qquad
\text{BIC} = -2\log\mathcal{L} + k\log n
\]</span></p>
<p>dove <span class="math inline">\(\mathcal{L}\)</span> è la verosimiglianza del modello, <span class="math inline">\(k\)</span> il numero di parametri e <span class="math inline">\(n\)</span> il numero di osservazioni. Entrambi premiano il fit (primo termine) e <strong>penalizzano la complessità</strong> (secondo termine): misurano l’efficienza del modello in termini di <em>previsione</em> dei dati, proprio quello che l’overfitting comprometteva.</p>
<p>Dati <span class="math inline">\(k\)</span> valori di AIC/BIC per <span class="math inline">\(k\)</span> modelli diversi, <strong>si preferisce il modello con il valore più basso</strong>. Due vantaggi pratici rispetto all’ANOVA: i modelli non devono essere annidati, e non c’è nessun p-value di mezzo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">AIC</span>(m0, m1, m2, m3, m4)</span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>A[<span class="fu">order</span>(A<span class="sc">$</span>AIC), ]</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   df      AIC
m4  5 3745.086
m3  4 3751.989
m1  3 3757.216
m2  3 3829.506
m0  2 3852.576</code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">BIC</span>(m0, m1, m2, m3, m4)</span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>B[<span class="fu">order</span>(B<span class="sc">$</span>BIC), ]</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   df      BIC
m4  5 3765.451
m3  4 3768.281
m1  3 3769.435
m2  3 3841.725
m0  2 3860.723</code></pre>
</div>
</div>
<p>Sia per AIC sia per BIC il modello preferito è <code>m4</code>, quello con l’interazione.</p>
</section>
<section id="la-quantificazione-dellevidenza" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="la-quantificazione-dellevidenza"><span class="header-section-number">6.5</span> La quantificazione dell’evidenza</h2>
<p>Un grande vantaggio di AIC/BIC è la possibilità di stimare la <strong>plausibilità relativa</strong> di un modello rispetto a un altro, evitando tutti i problemi associati al p-value. Il calcolo dell’<strong>evidenza relativa</strong> (<em>evidence ratio</em>) è molto semplice:</p>
<ol type="1">
<li>sia <span class="math inline">\(\Delta\)</span> la differenza tra i valori di AIC (o BIC) dei due modelli;</li>
<li>si calcola <span class="math inline">\(\ell = e^{\Delta/2}\)</span>.</li>
</ol>
<p>Confrontiamo ad esempio il modello con interazione (<code>m4</code>) con quello senza (<code>m3</code>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>(DAIC <span class="ot">&lt;-</span> <span class="fu">AIC</span>(m3) <span class="sc">-</span> <span class="fu">AIC</span>(m4))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.903268</code></pre>
</div>
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(DAIC <span class="sc">/</span> <span class="dv">2</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 31.55191</code></pre>
</div>
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>(DBIC <span class="ot">&lt;-</span> <span class="fu">BIC</span>(m3) <span class="sc">-</span> <span class="fu">BIC</span>(m4))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.830223</code></pre>
</div>
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(DBIC <span class="sc">/</span> <span class="dv">2</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.116947</code></pre>
</div>
</div>
<ul>
<li><strong>Conclusione con AIC</strong>: il modello con interazione è circa <strong>32 volte più plausibile</strong> di quello senza interazione.</li>
<li><strong>Conclusione con BIC</strong>: il modello con interazione è circa <strong>4 volte più plausibile</strong> di quello senza.</li>
</ul>
<p>(Il BIC penalizza la complessità più severamente dell’AIC, da cui la differenza.)</p>
</section>
<section id="verosimiglianza-relativa-e-pesi-di-akaike" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="verosimiglianza-relativa-e-pesi-di-akaike"><span class="header-section-number">6.6</span> Verosimiglianza relativa e pesi di Akaike</h2>
<p>Possiamo estendere il ragionamento a tutti i modelli insieme, calcolando per ciascuno la verosimiglianza relativa rispetto al modello peggiore (qui il nullo):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">AIC</span>(m0, m1, m2, m3, m4)</span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>A<span class="sc">$</span>delta <span class="ot">&lt;-</span> <span class="fu">max</span>(A<span class="sc">$</span>AIC) <span class="sc">-</span> A<span class="sc">$</span>AIC</span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a>A<span class="sc">$</span>rl    <span class="ot">&lt;-</span> <span class="fu">exp</span>(A<span class="sc">$</span>delta <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a>A[<span class="fu">order</span>(A<span class="sc">$</span>AIC), ]</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   df      AIC     delta           rl
m4  5 3745.086 107.49072 2.194387e+23
m3  4 3751.989 100.58745 6.954849e+21
m1  3 3757.216  95.36065 5.096855e+20
m2  3 3829.506  23.07053 1.022590e+05
m0  2 3852.576   0.00000 1.000000e+00</code></pre>
</div>
</div>
<p>Il modello <code>m4</code> (<code>kid_score ~ mom_iq * mom_hs</code>) risulta circa <span class="math inline">\(2.19 \times 10^{23}\)</span> volte più verosimile del modello nullo.</p>
<p>Infine, possiamo <strong>normalizzare</strong> le verosimiglianze relative per ottenere i <strong>pesi di Akaike</strong>, interpretabili come la probabilità di ciascun modello <span class="math inline">\(M_i\)</span>, dati i dati e l’insieme dei modelli considerati <span class="math inline">\(\mathcal{M}\)</span>:</p>
<p><span class="math display">\[
w_i = \text{Prob}(M_i \,|\, \text{dati}, \mathcal{M}) =
\frac{\ell_i}{\sum_{j=1}^{J} \ell_j}
\]</span></p>
<p>dove <span class="math inline">\(J\)</span> è il numero di modelli considerati (nel nostro caso <span class="math inline">\(J = 5\)</span>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>A<span class="sc">$</span>w <span class="ot">&lt;-</span> A<span class="sc">$</span>rl <span class="sc">/</span> <span class="fu">sum</span>(A<span class="sc">$</span>rl)</span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(A<span class="sc">$</span>w, <span class="at">names.arg =</span> <span class="fu">rownames</span>(A), <span class="at">xlab =</span> <span class="st">"modelli"</span>, <span class="at">ylab =</span> <span class="st">"peso di Akaike"</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/akaike-weights-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Praticamente tutto il peso va a <code>m4</code>: dato questo insieme di modelli, è di gran lunga il candidato migliore.</p>
</section>
<section id="il-pacchetto-mumin" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="il-pacchetto-mumin"><span class="header-section-number">6.7</span> Il pacchetto MuMIn</h2>
<p>Il pacchetto <strong>MuMIn</strong> automatizza l’intera procedura e produce una tabella di selezione completa (stime, gradi di libertà, log-verosimiglianza, AIC, delta e pesi):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MuMIn)</span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>(AICtable <span class="ot">&lt;-</span> <span class="fu">model.sel</span>(m0, m1, m2, m3, m4, <span class="at">rank =</span> AIC))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model selection table 
    (Int) mom_iq mom_hs mom_hs:mom_iq df    logLik    AIC  delta weight
m4 -11.48 0.9689      +             +  5 -1867.543 3745.1   0.00  0.967
m3  25.73 0.5639      +                4 -1871.995 3752.0   6.90  0.031
m1  25.80 0.6100                       3 -1875.608 3757.2  12.13  0.002
m2  77.55             +                3 -1911.753 3829.5  84.42  0.000
m0  86.80                              2 -1924.288 3852.6 107.49  0.000
Models ranked by AIC(x) </code></pre>
</div>
</div>
<p>E per i confronti a coppie possiamo costruire la matrice delle evidenze relative (in scala logaritmica, per leggibilità):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>ER <span class="ot">&lt;-</span> <span class="fu">outer</span>(A<span class="sc">$</span>rl, A<span class="sc">$</span>rl, <span class="st">"/"</span>)</span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(ER) <span class="ot">&lt;-</span> <span class="fu">colnames</span>(ER) <span class="ot">&lt;-</span> <span class="fu">rownames</span>(A)</span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">log</span>(ER), <span class="dv">1</span>)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     m0    m1    m2    m3    m4
m0  0.0 -47.7 -11.5 -50.3 -53.7
m1 47.7   0.0  36.1  -2.6  -6.1
m2 11.5 -36.1   0.0 -38.8 -42.2
m3 50.3   2.6  38.8   0.0  -3.5
m4 53.7   6.1  42.2   3.5   0.0</code></pre>
</div>
</div>
<p>Ogni cella riporta il logaritmo dell’evidenza del modello di riga rispetto al modello di colonna: valori positivi favoriscono il modello di riga (es. <code>m4</code> vs <code>m3</code>: <span class="math inline">\(\log \ell = 3.5\)</span>, cioè <span class="math inline">\(\ell \approx 32\)</span>, come calcolato prima).</p>
</section>
<section id="i-vantaggi-dei-criteri-di-informazione" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="i-vantaggi-dei-criteri-di-informazione"><span class="header-section-number">6.8</span> I vantaggi dei criteri di informazione</h2>
<p>Riassumendo, rispetto al confronto basato su test e p-value:</p>
<ul>
<li>si possono confrontare <strong>tutti i modelli</strong> che condividono lo stesso modello nullo, anche non annidati;</li>
<li>i valori di AIC/BIC calcolati sono <strong>indipendenti dall’ordine e dal numero</strong> dei modelli considerati;</li>
<li>evidenze relative e pesi di Akaike danno al lettore un quadro molto più ricco dei meriti relativi dei modelli in competizione, quantificando la fiducia statistica nel modello con l’AIC più basso (Burnham &amp; Anderson, 2002; Wagenmakers &amp; Farrell, 2004).</li>
</ul>
<p>Esempio di frase per un articolo: “il modello <code>m4</code> risulta circa <span class="math inline">\(2.19 \times
10^{23}\)</span> volte più verosimile del modello nullo, con peso di Akaike <span class="math inline">\(w = 0.97\)</span> nell’insieme dei cinque modelli considerati”.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled" title="✏️ Esercizio 10 — Un'analisi completa">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
✏️ Esercizio 10 — Un’analisi completa
</div>
</div>
<div class="callout-body-container callout-body">
<p>Mettiamo insieme tutto quello che abbiamo visto. Partendo dal modello <code>m4</code> (<code>kid_score ~ mom_iq * mom_hs</code>), chiedetevi se vale la pena aggiungere le altre variabili disponibili:</p>
<ol type="a">
<li>stimate i modelli che aggiungono a <code>m4</code>: l’età della madre (<code>mom_age</code>); la condizione lavorativa (<code>mom_work</code>); entrambe;</li>
<li>costruite la tabella di confronto con AIC, delta e pesi di Akaike (a mano o con <code>model.sel()</code>);</li>
<li>quale modello scegliete? Con quanta fiducia?</li>
<li>controllate la diagnostica e il predictive check del modello scelto;</li>
<li>scrivete due righe di conclusione “da articolo”.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Soluzione — Esercizio 10">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Soluzione — Esercizio 10
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a>mA <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> mom_iq <span class="sc">*</span> mom_hs,                      <span class="at">data =</span> kidiq)</span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a>mB <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> mom_iq <span class="sc">*</span> mom_hs <span class="sc">+</span> mom_age,            <span class="at">data =</span> kidiq)</span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a>mC <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> mom_iq <span class="sc">*</span> mom_hs <span class="sc">+</span> mom_work,           <span class="at">data =</span> kidiq)</span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a>mD <span class="ot">&lt;-</span> <span class="fu">lm</span>(kid_score <span class="sc">~</span> mom_iq <span class="sc">*</span> mom_hs <span class="sc">+</span> mom_age <span class="sc">+</span> mom_work, <span class="at">data =</span> kidiq)</span>
<span id="cb119-5"><a href="#cb119-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-6"><a href="#cb119-6" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">AIC</span>(mA, mB, mC, mD)</span>
<span id="cb119-7"><a href="#cb119-7" aria-hidden="true" tabindex="-1"></a>tab<span class="sc">$</span>delta <span class="ot">&lt;-</span> tab<span class="sc">$</span>AIC <span class="sc">-</span> <span class="fu">min</span>(tab<span class="sc">$</span>AIC)</span>
<span id="cb119-8"><a href="#cb119-8" aria-hidden="true" tabindex="-1"></a>tab<span class="sc">$</span>w     <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="sc">-</span>tab<span class="sc">$</span>delta <span class="sc">/</span> <span class="dv">2</span>) <span class="sc">/</span> <span class="fu">sum</span>(<span class="fu">exp</span>(<span class="sc">-</span>tab<span class="sc">$</span>delta <span class="sc">/</span> <span class="dv">2</span>))</span>
<span id="cb119-9"><a href="#cb119-9" aria-hidden="true" tabindex="-1"></a>tab[<span class="fu">order</span>(tab<span class="sc">$</span>AIC), ]</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   df      AIC     delta          w
mA  5 3745.086 0.0000000 0.49239740
mB  6 3745.934 0.8486496 0.32213197
mC  8 3747.997 2.9113243 0.11484966
mD  9 3748.970 3.8839180 0.07062097</code></pre>
</div>
</div>
<p>Il modello più semplice <code>mA</code> resta il preferito (<span class="math inline">\(w \approx 0.49\)</span>), seguito da <code>mB</code> (<span class="math inline">\(\Delta \approx 0.8\)</span>): un delta sotto 2 indica che i due modelli sono sostanzialmente equivalenti, e in questi casi conviene la <strong>parsimonia</strong>. Né l’età né la condizione lavorativa della madre migliorano la capacità predittiva abbastanza da giustificare i parametri aggiuntivi.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mA)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/sol-es10-diag-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_predictions</span>(mA)</span></code><button title="Copia negli appunti" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bayes_files/figure-html/sol-es10-ppc-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Possibile conclusione: “Tra i modelli considerati, quello con QI della madre, diploma e loro interazione risulta il migliore (AIC = 3745.1, <span class="math inline">\(w = 0.49\)</span>); l’aggiunta di età e condizione lavorativa della madre non migliora la capacità predittiva (<span class="math inline">\(\Delta\text{AIC} &lt; 4\)</span>, a fronte di più parametri). Il modello spiega circa il 23% della variabilità dei punteggi, con un errore medio di previsione di circa 18 punti.”</p>
</div>
</div>
</div>
</section>
</section>
<section id="riferimenti-bibliografici" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Riferimenti bibliografici</h1>
<p><strong>Testi di riferimento:</strong></p>
<ul>
<li>Fox, J. (1997). <em>Applied Regression Analysis, Linear Models, and Related Methods</em>. SAGE.</li>
<li>Fox, J. (2002). <em>An R and S-Plus Companion to Applied Regression</em>. SAGE.</li>
<li>Gelman, A., Hill, J., Vehtari, A. (2020). <em>Regression and Other Stories</em>. Cambridge University Press.</li>
</ul>
<p><strong>In italiano:</strong></p>
<ul>
<li>Bortot, P., Ventura, L., Salvan, A. (2000). <em>Inferenza Statistica: Applicazioni con S-PLUS e R</em>. Cedam, Padova.</li>
<li>Grigoletto, M., Ventura, L., Pauli, F. (2017). <em>Modello lineare. Teoria e applicazioni con R</em>. Giappichelli, Torino.</li>
<li>Pastore, M. (2015). <em>Analisi dei dati in psicologia (con applicazioni in R)</em>. Il Mulino, Bologna.</li>
</ul>
<p><strong>Sul confronto fra modelli:</strong></p>
<ul>
<li>Burnham, K. P., Anderson, D. R. (2002). <em>Model Selection and Multimodel Inference</em>. Springer.</li>
<li>Wagenmakers, E.-J., Farrell, S. (2004). AIC model selection using Akaike weights. <em>Psychonomic Bulletin &amp; Review</em>, 11, 192–196.</li>
</ul>
<p><strong>Pacchetti R utilizzati in questa dispensa:</strong></p>
<ul>
<li><strong>ggplot2</strong> (Wickham, 2016) — grafici;</li>
<li><strong>sjPlot</strong> (Lüdecke, 2023) — visualizzazione degli effetti dei modelli;</li>
<li><strong>effects</strong> (Fox &amp; Weisberg, 2019) — visualizzazione degli effetti dei modelli;</li>
<li><strong>performance</strong> (Lüdecke et al., 2021) — predictive check e diagnostica;</li>
<li><strong>MuMIn</strong> (Bartoń, 2020) — selezione di modelli.</li>
</ul>
<hr>
<p><em>Materiale didattico adattato dalle slide del Prof.&nbsp;Massimiliano Pastore.</em></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiato!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiato!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>PSQT - FISPPA - UNIPD</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>