{
  "hash": "ee5c0a1fcc03508cf60923da57eb4cd4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Introduzione alla statistica Bayesiana\"\nsubtitle: \"Dispensa del corso\"\nauthor: \"Margherita Calderan\"\ndate: last-modified\ndate-format: \"D MMMM YYYY\"\nnumber-sections: true\n---\n\n::: {.callout-tip icon=false title=\"📌 Come usare questa dispensa\"}\n\nQuesto documento raccoglie tutto il materiale della lezione. Parte del materiale didattico è stato adattato dalle slide del Prof. [Massimiliano Pastore](https://dpss.psy.unipd.it/~massimiliano.pastore/index.html) (a.a. 2024/2025) e dal corso che abbiamo tenuto alla Scuola Estiva di Metodologia AIP. Eventuali errori sono da attribuire alla sottoscritta (ovviamente).\n\nPrima di iniziare:\n\n1. installate i pacchetti necessari:\n   `install.packages(c(\"rstanarm\", \"bayesplot\", \"HDInterval\", \"loo\", \"BayesFactor\", \"brms\", \"bridgesampling\"))`\n2. per le ultime parti servono i file [kidiq.csv](dati/kidiq.csv) (lo stesso\n   della [dispensa sui modelli lineari](modelli-lineari.qmd)) e\n   [teddy_child.csv](dati/teddy_child.csv), salvati in una cartella `dati` dentro la vostra cartella di lavoro.\n:::\n\n# I due approcci all'inferenza\n\n## Popolazione e campione\n\nL'**inferenza statistica** è l'insieme delle operazioni che, a partire dai dati\nosservati, producono stime e affermazioni di incertezza sui parametri di una\npopolazione o di un processo sottostante (Gelman, Hill & Vehtari, 2020).\n\nI concetti di partenza sono due:\n\n- un **parametro** è una caratteristica della popolazione, espressa da un valore\n  (di solito numerico e **incognito**). I parametri si indicano con lettere greche:\n  $\\mu$, $\\sigma^2$, $\\theta$, $\\beta$...\n- una **statistica** è un valore calcolato su un campione di ampiezza $n$ estratto\n  dalla popolazione. Le statistiche si indicano con lettere latine ($\\bar{x}$, $s^2$,\n  $p$) e vengono usate come *stimatori* dei parametri incogniti.\n\nNoi vorremmo conoscere la popolazione, ma possiamo osservare solo uno o (nei casi\npiù fortunati) più campioni: tutta l'inferenza consiste nel risalire dal campione\nalla popolazione, quantificando l'incertezza di questo salto.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Codice del grafico\"}\npar(mfrow = c(1, 2), mar = c(0.5, 0.5, 2.5, 0.5))\n\n# il problema diretto: dalla popolazione ai campioni\nplot(NA, xlim = c(0, 10), ylim = c(0, 10), axes = FALSE, asp = 1,\n     xlab = \"\", ylab = \"\", main = \"Campionare: molti campioni possibili\")\nsymbols(3, 6, circles = 2.4, add = TRUE, inches = FALSE,\n        bg = \"royalblue3\", fg = \"royalblue4\")\ntext(3, 6, expression(Omega), col = \"white\", cex = 3)\ncx <- c(7.5, 8.3, 7.2, 5.6)          # centri dei campioni\ncy <- c(8.4, 5.9, 3.4, 1.6)\nraggio <- c(0.5, 0.9, 0.45, 0.3)     # campioni di ampiezza diversa\ncolore <- c(\"slategrey\", \"royalblue\", \"lightsteelblue\", \"indianred\")\narrows(c(5.1, 5.4, 4.9, 3.9), c(7.0, 6.0, 4.9, 3.8),\n       c(6.7, 7.1, 6.4, 5.1), c(8.0, 5.9, 3.9, 2.1), length = 0.1, lwd = 2)\nfor (i in 1:4) {\n  symbols(cx[i], cy[i], circles = raggio[i], add = TRUE, inches = FALSE,\n          bg = colore[i])\n  text(cx[i] + raggio[i] + 0.4, cy[i] + raggio[i] + 0.3, bquote(X[.(i)]))\n}\n\n# il problema inverso: dal campione alla popolazione\nplot(NA, xlim = c(0, 10), ylim = c(0, 10), axes = FALSE, asp = 1,\n     xlab = \"\", ylab = \"\", main = \"Inferire: dal campione alla popolazione\")\nsymbols(4, 6.5, circles = 2.4, add = TRUE, inches = FALSE, bg = \"grey85\")\ntext(4, 6.5, \"???\", cex = 2.5)\nsymbols(7.2, 1.8, circles = 0.45, add = TRUE, inches = FALSE, bg = \"royalblue\")\ntext(8.1, 2.2, expression(X[1]))\narrows(6.7, 2.5, 5.5, 4.6, length = 0.1, lwd = 2)\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/diagramma-inferenza-1.png){width=864}\n:::\n:::\n\n\nVediamolo in R: due campioni dalla stessa popolazione danno medie diverse, e\nripetendo l'estrazione mille volte otteniamo la **distribuzione campionaria**\ndella media:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(rnorm(30, mean = 100, sd = 15));mean(rnorm(30, mean = 100, sd = 15))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 98.97612\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 97.16568\n```\n\n\n:::\n\n```{.r .cell-code}\nmedie = replicate(n = 1000, mean(rnorm(30, mean = 100, sd = 15)))\nhist(medie, main = \"Distribuzione campionaria della media\")\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\nOgni campione dà una statistica un po' diversa: questa variabilità da campione a\ncampione è esattamente l'incertezza che l'inferenza deve quantificare.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(medie)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.750311\n```\n\n\n:::\n:::\n\n\n\n\n\nI due approcci principali per farlo sono quello **frequentista** e quello\n**bayesiano**. Prima di introdurre il secondo, ripassiamo brevemente il primo.\n\n## Un problema concreto {#sec-problema}\n\n> Vogliamo stimare la proporzione di studenti dei corsi della Scuola di Psicologia\n> a cui piace la statistica.\n\nUsiamo i dati di un questionario rilevato all'inizio di un corso di Analisi dei Dati (prof. Pastore): su $n = 315$ rispondenti, a 75 la statistica piace.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_tot   <- 315\nn_piace <- 75\nn_piace / n_tot     # proporzione campionaria\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2380952\n```\n\n\n:::\n:::\n\n\nLa proporzione campionaria è circa 0.24 (il 24%). Ma questa è una *statistica*: che\ncosa possiamo dire del *parametro*, cioè della proporzione $\\pi$ nella popolazione\ndi tutti gli studenti?\n\n## L'approccio NHST {#sec-nhst}\n\nL'approccio frequentista **Null Hypothesis Significance\nTesting** (NHST) procede così:\n\n1. si definisce un'**ipotesi nulla**, ad esempio: la proporzione di studenti a cui\n   piace la statistica è uguale a quella a cui non piace,\n   $$H_0: \\pi = 0.5$$\n   e un'ipotesi alternativa, ad esempio $H_1: \\pi < 0.5$;\n2. si calcola una **statistica test** sui dati osservati;\n3. conoscendo la **distribuzione campionaria** della statistica test *sotto*\n   $H_0$, si calcola la probabilità di osservare un risultato uguale o più estremo\n   di quello ottenuto: il **p-value**;\n4. se il p-value è inferiore a una soglia prefissata ($\\alpha = 0.05$), si rigetta\n   $H_0$; altrimenti no.\n\nVediamolo sui nostri dati. Se $H_0$ fosse vera, il numero di studenti a cui piace\nla statistica in un campione di 315 seguirebbe una distribuzione binomiale con\n$\\pi = 0.5$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nS <- 0:315   # spazio campionario\n# probabilita di ciascun risultato sotto H0\nP <- dbinom(S, 315, prob = 0.5)  \n\nplot(S, P, type = \"h\",\n     xlab = \"Numero di studenti a cui piace, su 315\",\n     ylab = expression(f(x~\"|\"~H[0])))\npoints(75, 0, pch = 19, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/nhst-h0-1.png){width=672}\n:::\n:::\n\n\nIl punto rosso è il risultato osservato: 75. La probabilità di osservare 75 *o\nmeno* successi, se $H_0$ fosse vera, è\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbinom(75, 315, prob = 0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.397657e-21\n```\n\n\n:::\n:::\n\n\nun numero microscopico. \n\n## Bayes vs. NHST {#sec-domanda}\n\nI risultati dell'approccio NHST rispondono alla domanda:\n\n> Assumendo che $H_0$ sia vera, qual è la probabilità di osservare valori uguali o\n> più estremi rispetto a quelli rilevati?\n\nIn realtà, la domanda che ci interessa davvero è un'altra:\n\n> Dati i valori osservati, qual è la probabilità che la mia ipotesi sia vera?\n\nNon è la stessa cosa. Nel primo caso stiamo calcolando $P(R\\,|\\,H_0)$, la probabilità del risultato condizionata all'ipotesi; nel secondo $P(H_0\\,|\\,R)$, la probabilità dell'ipotesi condizionata al risultato (una **probabilità a posteriori**). E in generale\n\n$$\nP(R\\,|\\,H_0) \\neq P(H_0\\,|\\,R)\n$$\n\nIl legame tra le due probabilità è definito dal **teorema di Bayes**:\n\n$$\nP(H_0\\,|\\,R) = \\frac{P(H_0)\\,P(R\\,|\\,H_0)}\n{P(H_0)\\,P(R\\,|\\,H_0) + P(H_1)\\,P(R\\,|\\,H_1)}\n$$\n\ndove $P(H_0)$ è la **probabilità a priori** di $H_0$, cioè quanto era plausibile\nl'ipotesi *prima* di vedere il risultato.\n\n## Esempio schizofrenia {#sec-cohen}\n\nL'incidenza della schizofrenia negli adulti è circa del 2%. Supponiamo di avere un\ntest diagnostico che individua il 95% dei soggetti realmente schizofrenici\n(sensibilità) e il 97% dei soggetti sani (specificità). Indichiamo:\n\n- $H_0$: il soggetto è sano; $H_1$: il soggetto è schizofrenico;\n- $R$: il test risulta positivo.\n\nLe probabilità in gioco sono:\n\n$$\nP(H_0) = 0.98 \\qquad P(H_1) = 0.02 \\qquad\nP(R\\,|\\,H_0) = 0.03 \\qquad P(R\\,|\\,H_1) = 0.95\n$$\n\n\n> Qual'è la probabilità che il soggetto sia sano, *dato*\nil test positivo?\n\n\n\n\nNotate che $P(R\\,|\\,H_0) = 0.03 < 0.05$: in logica NHST, davanti a un test\npositivo rigetteremmo l'ipotesi che il soggetto sia sano. Applichiamo invece il\nteorema di Bayes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npH0 <- 0.98; pH1 <- 0.02\npR_H0 <- 0.03; pR_H1 <- 0.95\n\npH0 * pR_H0 / (pH0 * pR_H0 + pH1 * pR_H1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.607438\n```\n\n\n:::\n:::\n\n\n$$\nP(H_0\\,|\\,R) = \\frac{0.98 \\times 0.03}{0.98 \\times 0.03 + 0.02 \\times 0.95} \\approx 0.61\n$$\n\nNonostante il $P(R\\,|\\,H_0) = 0.03$, la probabilità che il soggetto sia sano, *dato*\nil test positivo, è del 61%! La differenza la fa la probabilità a priori: la\nschizofrenia è rara, quindi tra i positivi al test i falsi allarmi sono la\nmaggioranza.\n\nIl modo più intuitivo di vederlo è con le **frequenze naturali**: su 10000\npersone, 200 sono schizofreniche e 9800 sane. Il test ne segnala positive\n$200 \\times 0.95 = 190$ tra le malate e $9800 \\times 0.03 = 294$ tra le sane. Tra i\n$190 + 294 = 484$ positivi, i sani sono $294/484 \\approx 0.61$.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Codice del grafico\"}\npar(mar = c(0.5, 0.5, 0.5, 0.5))\nplot(NA, xlim = c(0, 10), ylim = c(0, 10), axes = FALSE, xlab = \"\", ylab = \"\")\n\n# rami dell'albero\nsegments(5, 8.25, 2.5, 6.75);  segments(5, 8.25, 7.5, 6.75)\nsegments(2.5, 5.25, 1, 3.25);  segments(2.5, 5.25, 4, 3.25)\nsegments(7.5, 5.25, 6, 3.25);  segments(7.5, 5.25, 9, 3.25)\n\n# nodi\nbox_x <- c(5, 2.5, 7.5, 1, 4, 6, 9)\nbox_y <- c(9, 6, 6, 2.5, 2.5, 2.5, 2.5)\netichetta <- c(\"10000\\npersone\", \"200\\nmalati\", \"9800\\nsani\",\n               \"190\\ntest +\", \"10\\ntest -\", \"294\\ntest +\", \"9506\\ntest -\")\ncolore <- c(\"grey90\", \"khaki\", \"grey80\",\n            \"palegreen3\", \"lightblue\", \"steelblue1\", \"olivedrab3\")\nfor (i in 1:7) {\n  rect(box_x[i] - 0.85, box_y[i] - 0.75, box_x[i] + 0.85, box_y[i] + 0.75,\n       col = colore[i], border = \"grey40\")\n  text(box_x[i], box_y[i], etichetta[i], cex = 0.9)\n}\n\n# probabilita sui rami\ntext(3.1, 7.8, \"prev = 2%\", cex = 0.85)\ntext(6.8, 7.8, \"98%\", cex = 0.85)\ntext(1.2, 4.5, \"sens = 95%\", cex = 0.85)\ntext(3.6, 4.5, \"5%\", cex = 0.85)\ntext(6.3, 4.5, \"3%\", cex = 0.85)\ntext(8.9, 4.5, \"spec = 97%\", cex = 0.85)\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/albero-frequenze-1.png){width=672}\n:::\n:::\n\n\nI positivi al test sono le due caselle \"test +\": $190 + 294 = 484$, di cui 294\nsani. La proporzione di positivi che *non* sono malati è $294/484 \\approx 0.61$.\n\n::: {.callout-note icon=false title=\"✏️ Esercizio 1 — Il teorema di Bayes in ambulatorio\"}\nLo stesso test viene ora usato in un ambulatorio specialistico, dove la\nprevalenza della schizofrenia tra chi arriva è del 20% (non del 2%).\n\na. Ricalcolate $P(H_0\\,|\\,R)$ con il teorema di Bayes.\nb. Verificate il risultato con le frequenze naturali (partite da 10000 persone).\nc. Che cosa concludete sul ruolo della probabilità a priori?\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Soluzione — Esercizio 1\"}\n\n::: {.cell}\n\n```{.r .cell-code}\npH0 <- 0.80; pH1 <- 0.20\npH0 * 0.03 / (pH0 * 0.03 + pH1 * 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1121495\n```\n\n\n:::\n:::\n\n\na. $P(H_0\\,|\\,R) \\approx 0.11$: ora un test positivo indica malattia con\n   probabilità circa 0.89.\nb. Su 10000 persone: 2000 malate, 8000 sane. Positivi: $2000 \\times 0.95 = 1900$\n   malati e $8000 \\times 0.03 = 240$ sani. Tra i 2140 positivi, i sani sono\n   $240/2140 \\approx 0.11$.\nc. Lo **stesso risultato** (test positivo, stessa sensibilità e specificità) porta\n   a conclusioni molto diverse a seconda di quanto era plausibile l'ipotesi prima\n   di raccogliere il dato. \n:::\n\n\n## L'approccio Bayesiano {#sec-idea-bayes}\n\nLa differenza fondamentale tra i due approcci sta nel modo di trattare i parametri\nincogniti:\n\n- nell'approccio **frequentista** i parametri sono **quantità fisse**: $\\pi$ ha un\n  valore vero (ignoto), e non ha senso parlare della sua probabilità. Per questo il\n  p-value può solo condizionarsi a un valore ipotizzato ($H_0: \\pi = 0.5$);\n- nell'approccio **bayesiano** i parametri sono trattati come **variabili\n  casuali**, con una distribuzione di probabilità che descrive la nostra\n  incertezza. Diventa quindi legittimo (e naturale) calcolare quantità come\n  $P(\\pi < 0.5\\,|\\,\\text{dati})$ o $P(0.2 < \\pi < 0.3\\,|\\,\\text{dati})$.\n\nIl meccanismo è sempre il teorema di Bayes, applicato però al parametro:\n\n$$\np(\\theta\\,|\\,D) = \\frac{p(D\\,|\\,\\theta)\\, p(\\theta)}{p(D)}\n$$\n\nche si legge:\n\n$$\n\\text{posterior} = \\frac{\\text{likelihood} \\times \\text{prior}}{\\text{evidence}}\n$$\n\n- la **prior** $p(\\theta)$ formalizza ciò che sappiamo (o crediamo) sul parametro\n  *prima* di vedere i dati;\n- la **likelihood** $p(D\\,|\\,\\theta)$ dice quanto i dati osservati sono compatibili\n  con ciascun valore del parametro;\n- la **posterior** $p(\\theta\\,|\\,D)$ è il risultato: ciò che sappiamo sul parametro\n  *dopo* aver visto i dati.\n\nL'inferenza bayesiana può essere vista come una **riallocazione di credibilità**\ntra i possibili valori del parametro: i valori consistenti con i dati guadagnano\ncredibilità, quelli inconsistenti la perdono (Kruschke, 2015).\n\n\n# Ripasso di probabilità\n\n## Che cos'è la probabilità\n\nIn termini molto generali, la probabilità è una **misura dell'incertezza**\nassociata al verificarsi di un evento. Dato un fenomeno aleatorio (es. il lancio di\nun dado), l'insieme di tutti i possibili esiti si chiama **spazio campionario**\n$S$; un **evento** è un sottoinsieme di $S$.\n\nPer esempio nel lancio di un dado:\n\n- lo spazio campionario è ....\n- un possibile evento è ....\n- la probabilità che quest'evento si verifichi è ...\n\n---\n\nGli **assiomi** di Kolmogorov:\n\n**1.** Una probabilità non può essere negativa;\n\n**2.** La probabilità dell'intero spazio campionario è 1;\n\n**3.** Per due eventi reciprocamente esclusivi, la probabilità che se ne verifichi uno *o* l'altro è la somma delle due probabilità.\n\n\n## Distribuzioni di probabilità {#sec-distribuzioni}\n\nUna **distribuzione di probabilità** associa a ogni esito dello spazio campionario\nla sua probabilità. Se lo spazio campionario è **discreto** (esiti numerabili: es.\nnumero di errori in un compito) si parla di *funzione di massa* di probabilità; se\nè **continuo** (es. un tempo di reazione) di *funzione di densità*.\n\nAlcune distribuzioni che incontreremo ([overview](https://distribution-explorer.github.io/)):\n\n| Nome | Supporto | Parametri | Media | Varianza |\n|------|----------|-----------|-------|----------|\n| Bernoulli | $x \\in \\{0, 1\\}$ | $\\theta$ | $\\theta$ | $\\theta(1-\\theta)$ |\n| Binomiale | $x \\in \\{0, 1, \\ldots, n\\}$ | $n$, $\\theta$ | $n\\theta$ | $n\\theta(1-\\theta)$ |\n| Poisson | $x \\in \\{0, 1, 2, \\ldots\\}$ | $\\lambda$ | $\\lambda$ | $\\lambda$ |\n| Uniforme | $a \\le x \\le b$ | $a$, $b$ | $(a+b)/2$ | $(b-a)^2/12$ |\n| Normale | $-\\infty < x < +\\infty$ | $\\mu$, $\\sigma$ | $\\mu$ | $\\sigma^2$ |\n| Beta | $0 \\le x \\le 1$ | $a$, $b$ | $a/(a+b)$ | $\\frac{ab}{(a+b)^2(a+b+1)}$ |\n\n\n## Le distribuzioni in R {#sec-dpqr}\n\nR mette a disposizione, per ogni distribuzione, quattro funzioni con prefissi\ndiversi:\n\n- `d*`: la massa (discreta) o densità (continua) in un punto;\n- `p*`: la probabilità cumulata fino a un quantile;\n- `q*`: il quantile corrispondente a una probabilità cumulata;\n- `r*`: estrazione di campioni casuali dalla distribuzione.\n\nIl suffisso identifica la distribuzione: `binom`, `pois`, `unif`, `norm`, `t`,\n`beta`... Ad esempio `rnorm()` genera campioni da una normale.\n\n**Esempio (Poisson).** Supponiamo che il numero di errori commessi in un compito\ncognitivo segua una Poisson con $\\lambda = 3$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 0:14\nplot(x, dpois(x, lambda = 3), type = \"h\", ylab = \"Pr(x)\",\n     xlab = \"Numero di errori\")\npoints(x, dpois(x, lambda = 3), pch = 19)\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/poisson-plot-1.png){width=672}\n:::\n:::\n\n\nQual è la probabilità che un soggetto commetta esattamente 4 errori? E più di 2?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndpois(4, 3)          # esattamente 4 errori\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1680314\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - ppois(2, 3)      # piu di 2 errori\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5768099\n```\n\n\n:::\n:::\n\n\nE possiamo *simulare* osservazioni, verificando che media e varianza empiriche\nconvergono a $\\lambda$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nerrori <- rpois(100000, 3)\nc(media = mean(errori), varianza = var(errori))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   media varianza \n2.998470 3.015338 \n```\n\n\n:::\n:::\n\n\n::: {.callout-note icon=false title=\"✏️ Esercizio 2 — Distribuzioni in R\"}\nIl tempo (in secondi) impiegato da una cavia per completare un labirinto è\ndistribuito normalmente con media $\\mu = 180$ e deviazione standard $\\sigma = 40$.\n\na. Qual è la probabilità che una cavia impieghi meno di 200 secondi?\nb. Qual è la probabilità che impieghi tra 140 e 220 secondi?\nc. Rappresentate graficamente tre normali con media 180 e deviazione standard\n   20, 40 e 80 (suggerimento: `curve()` con `add = TRUE`).\nd. Quale valore di tempo è superato solo dal 5% delle cavie?\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Soluzione — Esercizio 2\"}\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(200, 180, 40)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6914625\n```\n\n\n:::\n\n```{.r .cell-code}\npnorm(220, 180, 40) - pnorm(140, 180, 40)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6826895\n```\n\n\n:::\n\n```{.r .cell-code}\ncurve(dnorm(x, 180, 20), from = 180 - 4 * 80, to = 180 + 4 * 80,\n      ylab = \"f(x)\", xlab = \"Tempo (secondi)\")\ncurve(dnorm(x, 180, 40), add = TRUE, col = \"blue\")\ncurve(dnorm(x, 180, 80), add = TRUE, col = \"red\")\nlegend(\"topleft\", legend = c(\"sd = 20\", \"sd = 40\", \"sd = 80\"),\n       col = c(\"black\", \"blue\", \"red\"), lty = 1, bty = \"n\")\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/sol-es2-1.png){width=672}\n:::\n\n```{.r .cell-code}\nqnorm(0.95, 180, 40)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 245.7941\n```\n\n\n:::\n:::\n\n\na. $P(X < 200) \\approx 0.69$.\nb. $P(140 < X < 220) \\approx 0.68$ (la classica regola \"circa due terzi entro una\n   deviazione standard\").\nc. Al crescere di $\\sigma$ la curva si abbassa e si allarga: l'area totale resta 1.\nd. Il 95° percentile è circa 246 secondi.\n:::\n\n## Probabilità congiunte, marginali e condizionate {#sec-congiunte}\n\nSpesso ci interessa la probabilità del verificarsi *insieme* di due (o più)\neventi. Costruiamo un esempio semplice: lanciamo una moneta equa **tre volte**.\n\n> Qual'è lo spazio campionario?\n\n\nLo spazio campionario ha 8 sequenze equiprobabili (TTT, TTC, TCT, ...). Definiamo due variabili casuali:\n\n- $X$ = numero di teste (0, 1, 2 o 3);\n- $Y$ = numero di *cambi* testa/croce nella sequenza (0, 1 o 2). Ad esempio la\n  sequenza TCT contiene 2 cambi, la sequenza TTT nessuno.\n\nElencando le 8 sequenze si ottiene la **distribuzione congiunta**\n$Pr(X = x, Y = y)$:\n\n|  | $X=0$ | $X=1$ | $X=2$ | $X=3$ | totale |\n|---|---|---|---|---|---|\n| $Y=0$ | 1/8 | 0 | 0 | 1/8 | **2/8** |\n| $Y=1$ | 0 | 2/8 | 2/8 | 0 | **4/8** |\n| $Y=2$ | 0 | 1/8 | 1/8 | 0 | **2/8** |\n| totale | **1/8** | **3/8** | **3/8** | **1/8** | 1 |\n\nE se volessimo la probabilità di un valore di $X$ *da solo* — per esempio\n$Pr(X = 1)$, \"esattamente una testa\", senza badare ai cambi? Guardando la colonna\n$X = 1$ della tabella: una sequenza con una sola testa può avere 1 cambio\n*oppure* 2 cambi. Sono casi che si escludono a vicenda, quindi (terzo assioma di\nKolmogorov) le loro probabilità si **sommano**:\n\n$$\nPr(X = 1) =\n\\underbrace{Pr(X = 1, Y = 0)}_{0} +\n\\underbrace{Pr(X = 1, Y = 1)}_{2/8} +\n\\underbrace{Pr(X = 1, Y = 2)}_{1/8} = \\frac{3}{8}\n$$\n\nche è esattamente il totale della colonna. Le distribuzioni ottenute così — i\ntotali di riga e di colonna — si chiamano **distribuzioni marginali**: ciascuna descrive una variabile per conto suo, qualunque sia il valore dell'altra. In generale, per ottenere la marginale di $X$ si somma la congiunta su tutti i valori di $Y$ (si dice \"marginalizzare rispetto a $Y$\"):\n\n$$\nPr(x) = \\sum_y Pr(x, y)\n$$\n\nLa **probabilità condizionata** risponde invece a domande del tipo: qual è la\nprobabilità che la sequenza abbia 1 cambio, *sapendo* che ha 1 testa? Si calcola\nrestringendo lo spazio ai soli casi compatibili con la condizione:\n\n$$\nPr(y\\,|\\,x) = \\frac{Pr(x, y)}{Pr(x)}\n$$\n\nNel nostro esempio:\n\n$$\nPr(Y = 1\\,|\\,X = 1) = \\frac{2/8}{3/8} = \\frac{2}{3} \\qquad\nPr(X = 1\\,|\\,Y = 1) = \\frac{2/8}{4/8} = \\frac{1}{2}\n$$\n\nDi nuovo: $Pr(y\\,|\\,x) \\neq Pr(x\\,|\\,y)$. \n\nDue variabili si dicono **indipendenti** se e solo se $Pr(y\\,|\\,x) = Pr(y)$ per\nogni $x$ e $y$ o, equivalentemente, se la congiunta è il prodotto delle marginali:\n$Pr(x, y) = Pr(x)\\,Pr(y)$.\n\n::: {.callout-note icon=false title=\"✏️ Esercizio 3 — Lancio di due dadi\"}\n\nSi consideri il lancio di due dadi equilibrati. Siano X e Y le variabili aleatorie che rappresentano rispettivamente il risultato del primo e del secondo dado.\n\n1. Calcolare la probabilità congiunta che X = 3 e Y = 5.\n\n2. Calcolare la probabilità che Y = 5 dato che X = 3.\n\n3. Sono X e Y variabili indipendenti? Giustificare la risposta.\n\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Soluzione — Esercizio 3\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calcolare la probabilità congiunta che X = 3 e Y = 5.\n(1/6) * (1/6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02777778\n```\n\n\n:::\n\n```{.r .cell-code}\n# Calcolare la probabilità che Y = 5 dato che X = 3.\n(1/6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1666667\n```\n\n\n:::\n\n```{.r .cell-code}\n# X e Y sono indipendenti perché il risultato di un dado \n# non influenza il risultato dell'altro dado\n```\n:::\n\n\n:::\n\n## Da dove viene il teorema di Bayes {#sec-derivazione}\n\nIl teorema di Bayes è una conseguenza diretta della definizione di\nprobabilità condizionata. Scriviamola nei due sensi:\n\n$$\nPr(y\\,|\\,x) = \\frac{Pr(x, y)}{Pr(x)} \\qquad\nPr(x\\,|\\,y) = \\frac{Pr(x, y)}{Pr(y)}\n$$\n\nRicavando $Pr(x, y)$ da entrambe e uguagliando:\n\n$$\nPr(y\\,|\\,x)\\,Pr(x) = Pr(x\\,|\\,y)\\,Pr(y)\n$$\n\ne dividendo per $Pr(x)$:\n\n$$\nPr(y\\,|\\,x) = \\frac{Pr(x\\,|\\,y)\\,Pr(y)}{Pr(x)}\n$$\n\nQuesto è il teorema di Bayes. \n\n# La verosimiglianza {#sec-verosimiglianza}\n\nIl secondo ingrediente della formula di Bayes è la **likelihood** (verosimiglianza)\n$p(D\\,|\\,\\theta)$. L'idea, passo per passo:\n\n1. abbiamo un **campione di dati**;\n2. **ipotizziamo** che provenga da una certa distribuzione — il \"processo\n   generatore dei dati\" — ad esempio una normale con $\\mu = 10$ e $\\sigma = 1.5$;\n3. con quella distribuzione, calcoliamo la **densità di ciascun punto** osservato.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- c(7.9, 9.4, 10.1, 10.8, 12.3)   # il nostro piccolo campione\ndnorm(y, mean = 10, sd = 1.5)        # densita di ogni punto se Y ~ N(10, 1.5^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09981831 0.24551343 0.26537115 0.23070260 0.08208835\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Codice del grafico\"}\ncurve(dnorm(x, 10, 1.5), from = 5, to = 15, lwd = 2,\n      xlab = \"y\", ylab = \"f(y)\", ylim = c(0, 0.3))\nd <- dnorm(y, 10, 1.5)\nsegments(y, 0, y, d, col = \"red\", lty = 2)\npoints(y, rep(0, length(y)), pch = 19)\npoints(y, d, pch = 19, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/lik-idea-1.png){width=672}\n:::\n:::\n\n\nLe cinque densità dicono quanto ciascun punto è \"plausibile\" sotto la distribuzione\nipotizzata. Ma il campione è uno solo: i punti sono stati osservati **insieme**, e\nla probabilità di eventi congiunti indipendenti — lo abbiamo appena ripassato — si\nottiene **moltiplicando**:\n\n$$\n\\mathcal{L}(\\theta) = \\prod_i f(y_i\\,|\\,\\theta)\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprod(dnorm(y, 10, 1.5))               # verosimiglianza\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.000123161\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(dnorm(y, 10, 1.5, log = TRUE))    # log-verosimiglianza\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -9.002018\n```\n\n\n:::\n:::\n\n\nIl prodotto di tante densità è un numero piccolissimo: per questo si lavora quasi\nsempre con la **log-verosimiglianza**, che trasforma il prodotto in una somma.\n\nIl numero appena calcolato dipende dall'ipotesi fatta ($\\mu = 10$). Ma potevamo\nipotizzare qualunque altro valore: proviamoli *tutti* (con $\\sigma$ fissata, per\nsemplicità). Quella che otteniamo è la **funzione di verosimiglianza**\n$\\mathcal{L}(\\mu)$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu_griglia <- seq(7, 13, by = 0.05)\nlogL <- numeric(length(mu_griglia))\nfor (i in 1:length(mu_griglia)) {\n  logL[i] <- sum(dnorm(y, mu_griglia[i], 1.5, log = TRUE))\n}\nplot(mu_griglia, logL, type = \"l\", lwd = 2,\n     xlab = expression(mu), ylab = \"log-likelihood\")\nabline(v = mean(y), lty = 2, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/lik-funzione-1.png){width=672}\n:::\n:::\n\n\nLa curva ha un massimo, e il massimo cade esattamente sulla **media campionaria**\n(linea rossa): tra tutte le normali candidate, quella centrata su $\\bar{y}$ è la\npiù compatibile con i dati. Questo è il principio della **massima verosimiglianza**\n(*maximum likelihood*).\n\n\n::: {.callout-note icon=false title=\"✏️ Esercizio 4 — La verosimiglianza del sondaggio\"}\nTornate ai dati della @sec-problema (75 successi su 315).\n\na. Costruite una griglia di valori di $\\theta$ da 0 a 1 (by = 0.001) e calcolate\n   la verosimiglianza binomiale di ciascun valore con\n   `dbinom(75, 315, prob = theta)`.\nb. Rappresentatela graficamente.\nc. Per quale valore di $\\theta$ la verosimiglianza è massima? Confrontatelo con la\n   proporzione campionaria.\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Soluzione — Esercizio 4\"}\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta <- seq(0, 1, by = 0.001)\nL <- dbinom(75, 315, prob = theta)\n\nplot(theta, L, type = \"l\", lwd = 2,\n     xlab = expression(theta), ylab = \"Likelihood\")\nabline(v = theta[which.max(L)], lty = 2, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/sol-es4-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntheta[which.max(L)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.238\n```\n\n\n:::\n\n```{.r .cell-code}\n75 / 315\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2380952\n```\n\n\n:::\n:::\n\n\nIl massimo cade su $\\theta = 0.238$, esattamente la proporzione campionaria: la\nstima di massima verosimiglianza di una proporzione è la proporzione osservata.\nNotate anche che la curva è *stretta*: con $n = 315$ i dati sono molto informativi\ne i valori di $\\theta$ lontani da 0.24 sono praticamente incompatibili con quanto\nosservato.\n:::\n\n# L'aggiornamento bayesiano: il caso binomiale {#sec-binomiale}\n\n## Un esempio con prior discreta {#sec-kiwi}\n\nUn ornitologo vuole stimare la proporzione $\\theta$ di maschi in una popolazione di\nkiwi. Il modello delle osservazioni è una Bernoulli: ogni animale osservato è\nmaschio con probabilità $\\theta$ e femmina con probabilità $1 - \\theta$, in modo\nindipendente dagli altri. Osservando $N$ animali di cui $z$ maschi, la\nverosimiglianza è\n\n$$\np(D\\,|\\,\\theta) = \\theta^{z}\\,(1 - \\theta)^{N - z}\n$$\n\nPer iniziare, supponiamo (irrealisticamente) che $\\theta$ possa assumere **solo tre\nvalori**: 0.25, 0.5, 0.75. Le nostre credenze a priori: il valore più plausibile è\n0.5 (probabilità 0.5), gli altri due si dividono il resto (0.25 ciascuno).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta <- c(0.25, 0.50, 0.75)          # valori possibili del parametro\nprior <- c(0.25, 0.50, 0.25)          # probabilita a priori\n\nplot(theta, prior, type = \"h\", lwd = 4, xlim = c(0, 1), ylim = c(0, 1),\n     xlab = expression(theta), ylab = expression(p(theta)), main = \"Prior\")\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\nOsserviamo 9 animali: 2 maschi e 7 femmine. Calcoliamo la posterior seguendo esattamente il teorema di Bayes:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# dati: 2 maschi su 9 animali\nz <- 2; N <- 9\nlike <- theta^z * (1 - theta)^(N - z) # verosimiglianza di ciascun theta\n\npD <- sum(like * prior)  # evidence: p(D) normalizzazione\npost <- (like * prior) / pD # teorema di Bayes\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Codice del grafico\"}\npar(mfrow = c(1, 3), mar = c(4, 4, 3, 1))\nplot(theta, prior, type = \"h\", lwd = 4, xlim = c(0, 1), ylim = c(0, 1),\n     xlab = expression(theta), ylab = expression(p(theta)), main = \"Prior\")\nplot(theta, like, type = \"h\", lwd = 4, xlim = c(0, 1),\n     xlab = expression(theta), ylab = expression(p(D~\"|\"~theta)),\n     main = \"Likelihood\")\nplot(theta, post, type = \"h\", lwd = 4, xlim = c(0, 1), ylim = c(0, 1),\n     xlab = expression(theta), ylab = expression(p(theta~\"|\"~D)),\n     main = \"Posterior\")\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/kiwi-plot-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(data.frame(theta, prior, like, post), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  theta prior   like   post\n1  0.25  0.25 0.0083 0.6792\n2  0.50  0.50 0.0020 0.3180\n3  0.75  0.25 0.0000 0.0028\n```\n\n\n:::\n:::\n\n\nLeggiamo il risultato. A priori credevamo soprattutto in $\\theta = 0.5$; i dati (2\nmaschi su 9) sono molto più compatibili con $\\theta = 0.25$; la posterior\nrialloca la credibilità di conseguenza: $\\theta = 0.25$ passa da 0.25 a 0.68,\n$\\theta = 0.5$ scende da 0.50 a 0.32, e $\\theta = 0.75$ diventa praticamente\nimpossibile.\n\nNotate tre cose:\n\n- il denominatore $p(D) = \\sum_\\theta p(D\\,|\\,\\theta)\\,p(\\theta)$ serve solo a far\n  sommare la posterior a 1: per questo spesso si scrive\n  $\\text{posterior} \\propto \\text{prior} \\times \\text{likelihood}$;\n- la posterior è un **compromesso** tra prior e likelihood;\n- potremmo ora usare la posterior come *nuova prior* e raccogliere altri dati:\n  l'aggiornamento bayesiano è intrinsecamente **sequenziale**.\n\n::: {.callout-note icon=false title=\"✏️ Esercizio 5 — Il sondaggio con prior a griglia\"}\nTorniamo al sondaggio sulla statistica (75 su 315). Questa volta, invece della sola\n$H_0: \\pi = 0.5$, formalizziamo delle credenze a priori più articolate su 11 valori\npossibili di $\\theta$: $0, 0.1, 0.2, \\ldots, 1$. Immaginando di aver chiesto in\naula, le probabilità a priori raccolte sono:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta <- seq(0, 1, by = 0.1); # possibili alori di pi\nprior <- c(1, 3, 0, 4, 0, 0, 0, 1, 0, 0, 0) / 9 #credenze\ncbind(theta, prior)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      theta     prior\n [1,]   0.0 0.1111111\n [2,]   0.1 0.3333333\n [3,]   0.2 0.0000000\n [4,]   0.3 0.4444444\n [5,]   0.4 0.0000000\n [6,]   0.5 0.0000000\n [7,]   0.6 0.0000000\n [8,]   0.7 0.1111111\n [9,]   0.8 0.0000000\n[10,]   0.9 0.0000000\n[11,]   1.0 0.0000000\n```\n\n\n:::\n:::\n\n\n\na. Calcolate la likelihood di ciascun valore: $p(D\\,|\\,\\theta) = \\theta^{75}(1-\\theta)^{240}$.\nb. Calcolate $p(D)$ e la posterior; rappresentate prior, likelihood e posterior.\nc. Che cosa è successo alle credenze a priori? \n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Soluzione — Esercizio 5\"}\n\n::: {.cell}\n\n```{.r .cell-code}\ntheta <- seq(0, 1, by = 0.1)\nprior <- c(1, 3, 0, 4, 0, 0, 0, 1, 0, 0, 0) / 9\n\nlike <- theta^75 * (1 - theta)^240\npD   <- sum(like * prior)\npost <- like * prior / pD\nround(post, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 0 0 0 1 0 0 0 0 0 0 0\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 3), mar = c(4, 4, 3, 1))\nplot(theta, prior, type = \"h\", lwd = 4, ylim = c(0, 1),\n     xlab = expression(theta), ylab = expression(p(theta)), main = \"Prior\")\nplot(theta, like, type = \"h\", lwd = 4,\n     xlab = expression(theta), ylab = expression(p(D~\"|\"~theta)),\n     main = \"Likelihood\")\nplot(theta, post, type = \"h\", lwd = 4, ylim = c(0, 1),\n     xlab = expression(theta), ylab = expression(p(theta~\"|\"~D)),\n     main = \"Posterior\")\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/sol-es5-1.png){width=864}\n:::\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\n```\n:::\n\n\nCon $n = 315$ la likelihood è estremamente concentrata attorno a 0.24 (lo abbiamo\nvisto nell'Esercizio 4): tra gli 11 valori candidati, solo $\\theta = 0.3$ e (molto\nmeno) $\\theta = 0.2$ hanno una verosimiglianza non trascurabile, e la prior\nassegnava a 0.3 il peso maggiore. La posterior si concentra quindi quasi tutta su\n0.3: con molti dati, la likelihood domina la prior. Il limite qui è la griglia\ntroppo povera: il valore \"vero\" (circa 0.24) non era nemmeno tra i candidati.\n:::\n\n## La distribuzione Beta {#sec-beta}\n\nUna proporzione è una variabile **continua** in $[0, 1]$, quindi la scelta naturale è una distribuzione di\nprobabilità continua su $[0, 1]$. La famiglia standard è la **distribuzione Beta**:\n\n$$\np(\\theta) = \\text{Beta}(a, b) = \\frac{\\Gamma(a + b)}{\\Gamma(a)\\Gamma(b)}\\,\n\\theta^{a-1}(1 - \\theta)^{b-1}\n$$\n\nI due parametri $a$ e $b$ controllano forma e concentrazione. Un modo pratico di\ninterpretarli: $a - 1$ \"successi immaginari\" e $b - 1$ \"insuccessi immaginari\" già\nosservati prima di iniziare; la media è $a/(a+b)$.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Codice del grafico\"}\ncurve(dbeta(x, 1, 1), from = 0, to = 1, lwd = 2, ylim = c(0, 4.5),\n      xlab = expression(theta), ylab = expression(p(theta)))\ncurve(dbeta(x, 0.5, 0.5), add = TRUE, lwd = 2, col = \"grey50\")\ncurve(dbeta(x, 3, 3),     add = TRUE, lwd = 2, col = \"blue\")\ncurve(dbeta(x, 10, 15),   add = TRUE, lwd = 2, col = \"red\")\nlegend(\"top\", bty = \"n\", lwd = 2,\n       col = c(\"black\", \"grey50\", \"blue\", \"red\"),\n       legend = c(\"Beta(1, 1)\", \"Beta(0.5, 0.5)\", \"Beta(3, 3)\", \"Beta(10, 15)\"))\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/beta-famiglia-1.png){width=672}\n:::\n:::\n\n\n- $\\text{Beta}(1, 1)$ è la **uniforme**: massima incertezza, ogni proporzione è\n  ugualmente plausibile a priori;\n- $\\text{Beta}(3, 3)$: crediamo blandamente che $\\theta$ sia vicino a 0.5;\n- $\\text{Beta}(10, 15)$: crediamo con una certa forza che $\\theta$ sia attorno a\n  0.4;\n- più $a + b$ è grande, più la prior è **informativa** (concentrata).\n\n## La Beta-binomiale {#sec-coniugazione}\n\nSe\n\n- la prior è $p(\\theta) = \\text{Beta}(a, b)$, e\n- i dati sono $s$ successi e $f$ insuccessi,\n\nallora la posterior è ancora una Beta, con parametri aggiornati:\n\n$$\np(\\theta\\,|\\,D) = \\text{Beta}(a + s,\\; b + f)\n$$\n\nBasta *sommare* i successi osservati al primo parametro e gli insuccessi al\nsecondo. Quando prior e posterior appartengono alla stessa famiglia si parla di\n**prior coniugata**: la Beta è la coniugata della verosimiglianza binomiale.\n\nImmaginiamo di osservare un kiwi (animale) alla volta. La sequenza osservata dall'ornitologo era F, F, F, F, M, F, M, F, F: partendo dalla prior uniforme\n$\\text{Beta}(1, 1)$, dopo ogni osservazione la posterior\n$\\text{Beta}(1 + m,\\, 1 + f)$ diventa la prior per l'osservazione successiva:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Codice del grafico\"}\nsequenza <- c(0, 0, 0, 0, 1, 0, 1, 0, 0)     # 1 = maschio, 0 = femmina\nm <- 0; f <- 0\npar(mfrow = c(3, 3), mar = c(2, 2, 2.5, 1))\nfor (i in 1:9) {\n  if (sequenza[i] == 1) m <- m + 1 else f <- f + 1\n  curve(dbeta(x, 1 + m, 1 + f), from = 0, to = 1, lwd = 2,\n        xlab = \"\", ylab = \"\",\n        main = paste0(\"oss. \", i, \": \", ifelse(sequenza[i] == 1, \"M\", \"F\"),\n                      \"  (m=\", m, \", f=\", f, \")\"))\n}\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/kiwi-sequenziale-1.png){width=672}\n:::\n:::\n\n\nOgni femmina sposta la distribuzione verso sinistra. Il risultato dopo 9 osservazioni è $\\text{Beta}(3, 8)$ — esattamente\nquello che si ottiene aggiornando in un colpo solo con $s = 2$ e $f = 7$:\nnell'aggiornamento bayesiano l'ordine delle osservazioni non conta, e la posterior di oggi è la prior di domani.\n\n## Riassumere la posterior {#sec-riassumere}\n\nLa posterior **è** il risultato dell'analisi bayesiana: una distribuzione completa,\nnon un singolo numero. Il nostro compito è *riassumerla* in modo utile. Le sintesi\nprincipali sono di tre tipi.\n\n**1. Stime puntuali.** Per la $\\text{Beta}(3, 8)$ dei kiwi:\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <- 3; b <- 8\nc(map     = (a - 1) / (a + b - 2),    # moda (maximum a posteriori)\n  mediana = qbeta(0.5, a, b),\n  media   = a / (a + b))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      map   mediana     media \n0.2222222 0.2585747 0.2727273 \n```\n\n\n:::\n:::\n\n\nMAP (il valore più probabile), mediana e media. Se la distribuzione è asimmetrica —\ncome qui — le tre misure differiscono; con distribuzioni simmetriche coincidono.\n\n**2. Intervalli.** Un intervallo di **credibilità** (*credible interval*) al 90%\nè un intervallo che contiene il parametro con probabilità 0.9, *dato ciò che\nabbiamo osservato*. Il modo più semplice è usare i quantili della posterior:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqbeta(c(0.05, 0.95), 3, 8)     # intervallo quantile-based al 90%\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.08726443 0.50690130\n```\n\n\n:::\n:::\n\n\nUn'alternativa è l'intervallo **HPD** (*Highest Posterior Density*, o HPDI): il\npiù *stretto* intervallo che contiene il 90% di probabilità. Con distribuzioni\nasimmetriche i due non coincidono:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(HDInterval)\nset.seed(11)\ncampioni_post <- rbeta(100000, 3, 8)\nhdi(campioni_post, credMass = 0.90)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    lower     upper \n0.0646122 0.4707343 \nattr(,\"credMass\")\n[1] 0.9\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve(dbeta(x, 3, 8))\nabline(v = hdi(campioni_post, credMass = 0.90), col = \"green\")\nabline(v = qbeta(c(0.05, 0.95), 3, 8), col = \"red\")\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n**3. Probabilità di ipotesi.** Qualunque affermazione su $\\theta$ ha ora una\nprobabilità, calcolabile come area sotto la posterior. La proporzione di maschi è\ninferiore a 0.5?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbeta(0.5, 3, 8)          # Pr(theta < 0.5 | D)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9453125\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - pbeta(0.5, 3, 8)      # Pr(theta > 0.5 | D)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.0546875\n```\n\n\n:::\n:::\n\n\n::: {.callout-important}\nConfrontate con l'intervallo di **confidenza** frequentista: \"se ripetessimo il\ncampionamento infinite volte, il 95% degli intervalli così costruiti conterrebbe il\nvalore vero\". Sul *singolo* intervallo calcolato non è ammessa alcuna affermazione\nprobabilistica: il parametro ci sta dentro oppure no. L'intervallo di credibilità\ndice invece esattamente ciò che tutti vorrebbero dire: \"il parametro sta qui dentro\ncon probabilità 0.95, dati i dati\". \n:::\n\n## Quanto conta la prior? {#sec-prior-dati}\n\nLa posterior è un compromesso tra prior e dati. Vediamo come cambia il compromesso\nal variare dei due. Prima: stessi dati (2 su 9), prior sempre più informative (attorno a 0.50):\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nprior_a <- c(1, 10, 50)       # tre prior: Beta(1,1), Beta(10,10), Beta(50,50)\nprior_b <- c(1, 10, 50)\n\npar(mfrow = c(1, 3), mar = c(4, 4, 3, 1))\nfor (i in 1:3) {\n  a <- prior_a[i]; b <- prior_b[i]\n  curve(dbeta(x, a + 2, b + 7), from = 0, to = 1, lwd = 2, col = \"red\",\n        xlab = expression(theta), ylab = \"densita di probabilita\",\n        main = paste0(\"Beta(\", a, \", \", b, \") + dati\"), ylim = c(0, 8))\n  curve(dbeta(x, a, b), add = TRUE, lwd = 2, lty = 2)\n  abline(v = 0.2222222, col = \"blue\")\n  legend(\"topright\", bty = \"n\", lwd = 2, lty = c(2, 1),\n         col = c(\"black\", \"red\"), legend = c(\"prior\", \"posterior\"))\n}\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/prior-informativa-1.png){width=864}\n:::\n:::\n\n\nCon la prior uniforme la posterior segue i dati $\\text{Beta}(1,1)$; con $\\text{Beta}(50, 50)$ — che equivale a *98 osservazioni immaginarie* bilanciate — 9 animali osservati spostano pochissimo. \n\nStessa prior $\\text{Beta}(10, 10)$, dati sempre più numerosi con la\nstessa proporzione osservata:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nz <- c(2, 20, 200)          # maschi osservati\nN <- c(9, 90, 900)          # animali osservati\n\npar(mfrow = c(1, 3), mar = c(4, 4, 3, 1))\nfor (i in 1:3) {\n  curve(dbeta(x, 10 + z[i], 10 + N[i] - z[i]), from = 0, to = 1, lwd = 2,\n        col = \"red\", xlab = expression(theta), ylab = \"densita di probabilita\",\n        main = paste0(z[i], \" maschi su \", N[i]))\n  curve(dbeta(x, 10, 10), from = 0, to = 1, lwd = 2,lty = 2, add = TRUE,\n        col = \"black\", xlab = expression(theta), ylab = \"densita di probabilita\")\n  abline(v = 0.2222222, col = \"blue\")\n}\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/dati-crescenti-1.png){width=864}\n:::\n:::\n\n\nAll'aumentare di $n$ la posterior si stringe attorno alla proporzione osservata:\n**con molti dati la likelihood domina**, e la scelta della prior diventa sempre\nmeno rilevante. Con pochi dati, viceversa, la prior conta molto — ci torneremo\nnella @sec-prior-scelta.\n\n## Prevedere nuovi dati: la distribuzione predittiva {#sec-predittiva}\n\nStimare i parametri non è l'unico obiettivo dell'inferenza: spesso vogliamo\n**prevedere le prossime osservazioni**. Un esempio classico (Hoff, 2009): a 129\ndonne di 65 anni o più viene chiesto se si sentono generalmente felici; 118\nrispondono di sì. Con prior uniforme, la posterior è\n$\\text{Beta}(1 + 118,\\; 1 + 11) = \\text{Beta}(119, 12)$.\n\nQual è la probabilità che la **prossima** intervistata si dichiari felice?  La risposta bayesiana media su tutta la posterior (abbiamo incertezza sul vero valore di $\\theta$) e, nel modello binomiale, il risultato è proprio la media a posteriori:\n\n$$\nPr(\\tilde{y} = 1\\,|\\,D) = \\int \\theta\\; p(\\theta\\,|\\,D)\\, d\\theta = E(\\theta\\,|\\,D)\n= \\frac{119}{131} \\approx 0.91\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#se la mia posterior è una beta(119,12)\npost <- rbeta(1e4, 119, 12)\n# la media ci dà la probabilità che la prox sia felice\nmean(post) # che si può ottenere analiticamente con \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9086567\n```\n\n\n:::\n\n```{.r .cell-code}\n119/131\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9083969\n```\n\n\n:::\n:::\n\n\n\nE se intervistassimo **altre 20 donne**, quante si dichiarerebbero felici? La\nrisposta è un'intera distribuzione — la **distribuzione predittiva a posteriori**\n(*posterior predictive distribution*) — che possiamo ottenere per simulazione,\npropagando l'incertezza in due passi: estraggo un valore di $\\theta$ dalla\nposterior e, con quel $\\theta$, simulo un nuovo campione:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(9)\ntheta_draw <- rbeta(100000, 119, 12)  # incertezza su theta\n# nuovi dati simulati\nz_nuove <- rbinom(100000, size = 20, prob = theta_draw) \n\nplot(table(z_nuove) / 100000, lwd = 3,\n     xlab = \"Numero di donne felici su 20 nuove interviste\",\n     ylab = \"Probabilita\")\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/felicita-predittiva-1.png){width=672}\n:::\n\n```{.r .cell-code}\nmean(z_nuove >= 18)     # Pr(almeno 18 su 20 | D)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.71757\n```\n\n\n:::\n:::\n\n\n\n\n::: {.callout-note}\nQuesta è la logica del **posterior predictive check** che conosciamo già dai\nmodelli lineari (`check_predictions()`) e che ritroveremo con `pp_check()`:\nsimulare dati dalla distribuzione predittiva e confrontarli con quelli osservati.\nSe il modello è buono, i dati veri devono sembrare \"uno dei tanti\" dataset\nsimulati.\n:::\n\n::: {.callout-note icon=false title=\"✏️ Esercizio 6 — Il sondaggio\"}\nRiprendiamo il sondaggio della @sec-problema: 75 successi su 315,\nprior uniforme $\\text{Beta}(1, 1)$.\n\na. Scrivete la posterior di $\\theta$.\nb. Calcolate media e mediana della posterior.\nc. Calcolate l'intervallo di credibilità al 95% (quantile-based) e confrontatelo\n   con l'intervallo di confidenza di `binom.test(75, 315)`: sono simili? La loro\n   *interpretazione* è la stessa?\nd. Calcolate $Pr(\\theta \\ge 0.5\\,|\\,D)$ e $Pr(\\theta < 0.3\\,|\\,D)$.\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Soluzione — Esercizio 6\"}\n\n::: {.cell}\n\n```{.r .cell-code}\na <- 1 + 75; b <- 1 + 240\n\nc(media   = a / (a + b),\n  mediana = qbeta(0.5, a, b),\n  map     = (a - 1) / (a + b - 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    media   mediana       map \n0.2397476 0.2391998 0.2380952 \n```\n\n\n:::\n\n```{.r .cell-code}\nqbeta(c(0.025, 0.975), a, b)                # credible interval 95%\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1944296 0.2881756\n```\n\n\n:::\n\n```{.r .cell-code}\nbinom.test(75, 315)$conf.int                # confidence interval 95%\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1921321 0.2890593\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n\n```{.r .cell-code}\n1 - pbeta(0.5, a, b)                        # Pr(theta >= 0.5 | D)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\npbeta(0.3, a, b)                            # Pr(theta < 0.3 | D)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9920782\n```\n\n\n:::\n:::\n\n\na. $\\text{Beta}(1 + 75,\\; 1 + 240) = \\text{Beta}(76, 241)$.\nb. Media, mediana e MAP sono tutte attorno a 0.24: con $n = 315$ la posterior è\n   quasi simmetrica.\nc. Numericamente quasi identici (con $n$ grande e prior uniforme succede spesso),\n   ma l'interpretazione è diversa: solo per l'intervallo di credibilità possiamo\n   dire che $\\theta$ vi appartiene con probabilità 0.95.\nd. $Pr(\\theta \\ge 0.5\\,|\\,D)$ è praticamente 0; $Pr(\\theta < 0.3\\,|\\,D) \\approx 0.99$.\n:::\n\n# Il caso normale {#sec-normale}\n\nIl problema di inferenza ora ha **due parametri**: la media $\\mu$ e la deviazione standard $\\sigma$.\n\n$$\ny_i \\sim \\mathcal{N}(\\mu, \\sigma)\n$$\n\n## I dati: un sospetto deficit cognitivo\n\nAbbiamo valutato le funzioni cognitive di 10 pazienti con un test standardizzato\n(nella popolazione generale: media 100, deviazione standard 15). C'è il sospetto di\nun deficit cognitivo. I punteggi osservati:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- c(73, 101, 74, 76, 112, 71, 71, 75, 97, 67)\nc(media = mean(y), sd = sd(y), n = length(y))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   media       sd        n \n81.70000 15.57098 10.00000 \n```\n\n\n:::\n:::\n\n\nLa domanda: che cosa possiamo dire di $\\mu$, la media della popolazione da cui\nprovengono questi pazienti? In particolare: quanto è probabile che $\\mu < 90$?\n\n## Caso 1: $\\sigma$ nota — la coniugazione normale-normale {#sec-normale-normale}\n\nCominciamo dal caso semplice in cui assumiamo $\\sigma = 15$ nota (quella del test)\ne stimiamo solo $\\mu$. Il modello bayesiano completo:\n\n$$\n\\mu \\sim \\mathcal{N}(100, 10) \\qquad\ny_i \\sim \\mathcal{N}(\\mu, 15)\n$$\n\nLa prior $\\mathcal{N}(100, 10)$ dice: prima di vedere i dati, il valore più\nplausibile per $\\mu$ è quello della popolazione generale (100), ma con incertezza\nsostanziale (deviazione standard 10).\n\n**prior normale + likelihood normale = posterior normale**. Le formule di aggiornamento sono più leggibili in termini di **precisione**, cioè il reciproco della varianza ($1/\\tau^2$): le precisioni si *sommano*,\n\n$$\n\\frac{1}{\\tau_1^2} = \\frac{1}{\\tau_0^2} + \\frac{n}{\\sigma^2}\n$$\n\ne la media a posteriori è una **media pesata** tra media della prior e media\ncampionaria, con pesi proporzionali alle rispettive precisioni:\n\n$$\n\\mu_1 = \\frac{\\dfrac{1}{\\tau_0^2}\\,\\mu_0 + \\dfrac{n}{\\sigma^2}\\,\\bar{y}}\n{\\dfrac{1}{\\tau_0^2} + \\dfrac{n}{\\sigma^2}}\n$$\n\nCalcoliamola a mano:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu0  <- 100; tau0 <- 10        # prior\nsigma <- 15                    # ds nota\nn <- length(y); ybar <- mean(y)\n\nprec_prior <- 1 / tau0^2       # precisione della prior\nprec_dati  <- n / sigma^2      # precisione dei dati\n\nmu1  <- (prec_prior * mu0 + prec_dati * ybar) / (prec_prior + prec_dati)\ntau1 <- sqrt(1 / (prec_prior + prec_dati))\nc(media_post = mu1, ds_post = tau1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmedia_post    ds_post \n 85.061224   4.285714 \n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nmu_griglia <- seq(70, 110, by = 0.1)\n\nplot(mu_griglia, dnorm(mu_griglia, mu1, tau1), type = \"l\", lwd = 4, col = \"blue\",\n     xlab = expression(mu), ylab = expression(p(mu~\"|\"~D)))\ncurve(dnorm(x, 100, 10), add = TRUE, lwd = 2, lty = 2)\nabline(v = mean(y), col = \"red\", add = TRUE)\nlegend(\"topleft\", bty = \"n\", lwd = c(4, 2, 2), lty = c(1, 1, 2),\n       col = c(\"blue\", \"black\"),\n       legend = c(\"posterior\", \"prior\"))\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/normale-plot-1.png){width=672}\n:::\n:::\n\n\nOsservate la posizione della posterior: la media campionaria è 81.7, la prior era\ncentrata su 100, la posterior si piazza a 85.1 circa — *tra* le due,\nma molto più vicina ai dati, perché con $n = 10$ la precisione dei dati\n($10/225 \\approx 0.044$) è oltre quattro volte quella della prior ($0.01$). Questo\n\"tiro verso la prior\" si chiama **shrinkage**: con pochi dati la stima viene\nregolarizzata verso ciò che è plausibile a priori, con molti dati sparisce.\n\n> Quanto è probabile che $\\mu < 90$?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(90, mu1, tau1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8754177\n```\n\n\n:::\n:::\n\n\n\n## Caso 2: $\\mu$ e $\\sigma$ entrambi ignoti {#sec-griglia-2d}\n\nNel caso realistico anche $\\sigma$ è ignota. Il modello diventa:\n\n$$\n\\mu \\sim \\mathcal{N}(100, 10) \\qquad\n\\sigma \\sim \\text{Uniforme}(0, 40) \\qquad\ny_i \\sim \\mathcal{N}(\\mu, \\sigma)\n$$\n\nLa posterior ora è una distribuzione **congiunta bidimensionale**\n$p(\\mu, \\sigma\\,|\\,D)$ e non ha una forma analitica comoda. Calcoliamo prior × likelihood su una griglia di *coppie*\n$(\\mu, \\sigma)$.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nmu_griglia    <- seq(65, 110, length.out = 200)\nsigma_griglia <- seq(5, 40, length.out = 200)\n\nPOST <- matrix(NA, nrow = 200, ncol = 200)   # righe: mu; colonne: sigma\nfor (i in 1:200) {\n  for (j in 1:200) {\n    prior_ij  <- dnorm(mu_griglia[i], 100, 10) * dunif(sigma_griglia[j], 0, 40)\n    like_ij   <- prod(dnorm(y, mu_griglia[i], sigma_griglia[j]))\n    POST[i, j] <- prior_ij * like_ij\n  }\n}\nPOST <- POST / sum(POST)                     # normalizzo\n\ncontour(mu_griglia, sigma_griglia, POST,\n        xlab = expression(mu), ylab = expression(sigma), drawlabels = FALSE)\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/griglia-2d-1.png){width=672}\n:::\n:::\n\n\nLe curve di livello mostrano la regione di coppie $(\\mu, \\sigma)$ credibili. Per\nottenere le distribuzioni **marginali** dei singoli parametri basta sommare\nsull'altro (esattamente come nella tabella della @sec-congiunte):\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\npost_mu    <- rowSums(POST)      # marginalizzo su sigma\npost_sigma <- colSums(POST)      # marginalizzo su mu\n\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\nplot(mu_griglia, post_mu, type = \"l\", lwd = 2,\n     xlab = expression(mu), ylab = expression(p(mu~\"|\"~D)))\nplot(sigma_griglia, post_sigma, type = \"l\", lwd = 2,\n     xlab = expression(sigma), ylab = expression(p(sigma~\"|\"~D)))\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/griglia-2d-marginali-1.png){width=768}\n:::\n:::\n\n\n\n\n# Campionare dalla posterior: MCMC {#sec-mcmc}\n\n## Perché campionare\n\nSe non conosciamo la forma analitica di una distribuzione, possiamo\n**approssimarla estraendo campioni da essa**. Con abbastanza campioni,\nricostruiamo la densità, la media dei campioni stima la media, i\nquantili stimano i quantili, e ogni probabilità diventa una semplice *proporzione di campioni*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(15)\nnumerosita <- c(10, 100, 1000, 100000)\n\npar(mfrow = c(2, 2), mar = c(4, 4, 3, 1))\nfor (n in numerosita) {\n  campioni <- rbeta(n, 12, 4)     # campiono dalla posterior Beta(12, 4)\n  hist(campioni, freq = FALSE, breaks = 30, xlim = c(0, 1),\n       main = paste(\"n =\", n), xlab = expression(theta), ylab = \"densita\")\n  curve(dbeta(x, 12, 4), add = TRUE, lwd = 2, col = \"red\")\n}\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/sampling-idea-1.png){width=672}\n:::\n:::\n\n\n(La curva rossa è la $\\text{Beta}(12, 4)$, cioè la posterior dell'accuratezza di\nun soggetto con prior uniforme e 11 risposte corrette su 14 prove: con 100000\ncampioni l'istogramma la ricalca perfettamente.)\n\nQui abbiamo potuto usare `rbeta()` perché la posterior era nota. Il problema vero\nè: come si campiona da una posterior di cui conosciamo solo\n$\\text{prior} \\times \\text{likelihood}$, a meno di una costante? La risposta sono\ngli algoritmi **MCMC** (*Markov Chain Monte Carlo*): costruiscono una \"catena\" di\nvalori che si muove nello spazio dei parametri e che, a regime, visita ogni regione\ncon frequenza proporzionale alla sua probabilità a posteriori. I campioni MCMC\nhanno però una particolarità: ogni passo dipende dal precedente (per questo\n\"catena\"), quindi i campioni sono **correlati tra loro** — ne riparleremo tra\npoco a proposito di diagnostiche.\n\n\n![Immagine realizzata dal prof. Pastore](img/mc-pastore.png)\n\n> Lambert, B. (2018). A Student’s Guide to Bayesian Statistics. London, UK: SAGE;\n\n\n## I software {#sec-software}\n\nStoricamente: **BUGS** (anni '90), poi **JAGS**, oggi soprattutto **Stan** — che\nprende il nome da Stanislaw Ulam, coinventore dei metodi Monte Carlo, e usa un\nalgoritmo MCMC moderno ed efficiente (NUTS, *No-U-Turn Sampler*). In R ci sono\ndiversi livelli di accesso a Stan:\n\n- **rstan** / **cmdstanr**: si scrive il modello direttamente nel linguaggio Stan\n  (massima flessibilità);\n- **rstanarm**: modelli di regressione *precompilati*, sintassi identica a\n  `lm()`/`glm()` — immediato;\n- **brms**: sintassi tipo `lm()`, genera e compila codice Stan su misura; il più\n  flessibile tra quelli \"a formula\".\n\nIn questa dispensa usiamo soprattutto **rstanarm**: la funzione `stan_glm()` è\nl'equivalente bayesiano di `lm()`/`glm()`, e non richiede di compilare nulla. A\nfine capitolo proveremo la stessa analisi con **brms**.\n\n## Un confronto tra due gruppi {#sec-due-gruppi}\n\n16 adolescenti (8 maschi e 8 femmine) valutati sulla\npropensione al gioco d'azzardo (punteggi più alti = maggiore propensione). Ci\nchiediamo se ci sia una differenza di genere.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nYm <- c(8.8, 19.3, 15.7, 14.6, 8.2, 7.6, 8.7, 8.4)     # maschi\nYf <- c(4.8, 10.6, 11.7, 10.1, 4.8, 8.2, 8.5, 6.8)     # femmine\n\ngioco <- data.frame(sesso     = rep(c(\"f\", \"m\"), each = 8),\n                    punteggio = c(Yf, Ym))\ntapply(gioco$punteggio, gioco$sesso, mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      f       m \n 8.1875 11.4125 \n```\n\n\n:::\n:::\n\n\nL'approccio NHST è il test $t$ (che, come sappiamo dalla dispensa sui modelli\nlineari, è un modello lineare con un predittore dicotomico):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(Ym, Yf, alternative = \"greater\", var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  Ym and Yf\nt = 1.7712, df = 14, p-value = 0.04914\nalternative hypothesis: true difference in means is greater than 0\n95 percent confidence interval:\n 0.01800657        Inf\nsample estimates:\nmean of x mean of y \n  11.4125    8.1875 \n```\n\n\n:::\n:::\n\n\n$p = 0.049$: \"significativo\" per un soffio. Tutto quello che possiamo dire è:\nrigettiamo $H_0$ al 5%.\n\nVersione bayesiana dello *stesso* modello lineare, con `stan_glm()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rstanarm)\nfit_gioco <- stan_glm(punteggio ~ sesso, data = gioco, seed = 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_gioco, digits = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Info:\n function:     stan_glm\n family:       gaussian [identity]\n formula:      punteggio ~ sesso\n algorithm:    sampling\n sample:       4000 (posterior sample size)\n priors:       see help('prior_summary')\n observations: 16\n predictors:   2\n\nEstimates:\n              mean   sd   10%   50%   90%\n(Intercept) 8.17   1.40 6.37  8.18  9.92 \nsessom      3.24   1.98 0.71  3.27  5.73 \nsigma       3.84   0.76 2.97  3.71  4.87 \n\nFit Diagnostics:\n           mean   sd    10%   50%   90%\nmean_PPD  9.78   1.39  8.02  9.81 11.51\n\nThe mean_ppd is the sample average posterior predictive distribution of the outcome variable (for details see help('summary.stanreg')).\n\nMCMC diagnostics\n              mcse Rhat n_eff\n(Intercept)   0.03 1.00 3061 \nsessom        0.04 1.00 2858 \nsigma         0.01 1.00 2694 \nmean_PPD      0.02 1.00 3496 \nlog-posterior 0.03 1.00 1652 \n\nFor each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains (at convergence Rhat=1).\n```\n\n\n:::\n:::\n\n\nLa sintassi è identica a `lm()`; dietro le quinte, Stan ha campionato dalla\nposterior congiunta di tutti i parametri: intercetta (la media delle femmine),\ncoefficiente `sessom` (la differenza maschi − femmine, chiamiamola $\\delta$) e\n`sigma`. Di default vengono lanciate 4 catene da 2000 iterazioni, di cui le prime\n1000 di riscaldamento (*warmup*) vengono scartate: restano $4 \\times 1000 = 4000$\ndraws dalla posterior.\n\n## Le diagnostiche MCMC {#sec-diagnostiche}\n\nPrima di interpretare i risultati dobbiamo chiederci: **il campionamento ha\nfunzionato?** Le quantità da guardare (nel blocco `MCMC diagnostics` del summary):\n\n- **Rhat**: si lanciano più catene in parallelo, da punti di partenza diversi, e\n  si confrontano. Se tutte hanno esplorato la stessa regione, $\\hat{R} \\approx 1$\n  (idealmente $\\le 1.01$): convergenza raggiunta. Se $\\hat{R} > 1$, i risultati non\n  sono affidabili;\n- **n_eff** (*effective sample size*): i draws MCMC sono correlati, quindi 4000\n  draws non valgono 4000 campioni indipendenti — ne \"valgono\" n_eff. Più è alto,\n  più le stime sono precise (indicativamente, almeno qualche centinaio);\n- il **trace plot**: l'evoluzione di ciascuna catena nel tempo. Se le catene si\n  sovrappongono oscillando attorno allo stesso valore — il classico \"bruco pelosetto\"\n  (*fuzzy caterpillar*) — è un buon segno:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(bayesplot)\nmcmc_trace(fit_gioco, pars = c(\"sessom\", \"sigma\"))\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/gioco-trace-1.png){width=672}\n:::\n:::\n\n\nQui è tutto in ordine: Rhat = 1, n_eff alti, catene ben mescolate.\n\n## Usare la posterior {#sec-usare-posterior}\n\nEstraiamo le draws e trattiamoli per quello che sono: 4000 valori plausibili di ciascun parametro, con frequenza proporzionale alla loro credibilità a posteriori.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPOST <- as.data.frame(fit_gioco)\nhead(round(POST, 2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  (Intercept) sessom sigma\n1        7.45   5.86  4.06\n2        7.64   2.59  4.47\n3       11.25   0.45  4.64\n4       10.92   0.20  4.65\n5        6.19   4.43  3.27\n6       11.72   0.86  3.90\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(POST)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4000    3\n```\n\n\n:::\n:::\n\n\nLa distribuzione a posteriori della differenza $\\delta$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcmc_areas(fit_gioco, pars = \"sessom\", prob = 0.90)\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/gioco-post-delta-1.png){width=672}\n:::\n:::\n\n\nE ogni ipotesi che ci interessa diventa una proporzione di draws:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(POST$sessom > 0)              # Pr(delta > 0 | D)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.947\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(POST$sessom > 2)              # Pr(delta > 2 | D)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.74025\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(POST$sessom > 2 & POST$sessom < 4)   # Pr(2 < delta < 4 | D)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3915\n```\n\n\n:::\n:::\n\n\nConfrontate con l'output del test $t$: là un p-value e una decisione binaria; qui\nla probabilità che la differenza sia positiva (circa 0.95), che superi 2 punti\n(circa 0.74), che stia in qualunque intervallo ci interessi. Con un metodo\nbayesiano possiamo calcolare $Pr(\\delta > 0\\,|\\,D)$; con NHST questa probabilità\nnon esiste: $H_1$ è vera oppure falsa, punto.\n\n::: {.callout-note icon=false title=\"✏️ Esercizio 8 — Interrogare la posterior\"}\nSempre sul modello `fit_gioco`:\n\na. calcolate l'intervallo di credibilità HPD al 89% per $\\delta$ con `hdi()`\n   (pacchetto HDInterval) applicato a `POST$sessom`;\nb. calcolate $Pr(\\delta > 5\\,|\\,D)$: una differenza di almeno 5 punti è credibile?\nc. calcolate la probabilità che la deviazione standard residua sia maggiore di 4;\nd. confrontate `posterior_interval(fit_gioco, prob = 0.89)` con il risultato di\n   (a): perché non coincidono esattamente?\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Soluzione — Esercizio 8\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nhdi(POST$sessom, credMass = 0.89)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    lower     upper \n0.1144126 6.4475471 \nattr(,\"credMass\")\n[1] 0.89\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(POST$sessom > 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1755\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(POST$sigma > 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.36025\n```\n\n\n:::\n\n```{.r .cell-code}\nposterior_interval(fit_gioco, prob = 0.89)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  5.5%     94.5%\n(Intercept) 5.88130759 10.338268\nsessom      0.04732611  6.407685\nsigma       2.83561721  5.227360\n```\n\n\n:::\n:::\n\n\na. L'HPD al 89% va da circa 0.1 a circa 6.4: la differenza è credibilmente\n   positiva ma la sua entità è stimata con molta incertezza ($n = 16$!).\nb. $Pr(\\delta > 5\\,|\\,D) \\approx 0.18$: possibile ma poco probabile.\nc. Circa 0.36: anche su $\\sigma$ abbiamo un'intera distribuzione, non un numero.\nd. `posterior_interval()` usa i quantili centrali (5.5% e 94.5%), non l'HPD: con\n   posterior leggermente asimmetriche i due intervalli differiscono un po'. Con\n   distribuzioni simmetriche coincidono.\n:::\n\n## La stessa analisi con `brms` {#sec-brms}\n\nPrima di passare alle applicazioni, rifacciamo lo stesso modello con **brms**. A\ndifferenza di rstanarm, brms genera e **compila** codice Stan su misura.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(brms)\nfit_gioco_brm <- brm(punteggio ~ sesso, data = gioco, seed = 1,\n                     file = \"objects/fit_gioco_brm\",\n                     file_refit = \"on_change\")\n```\n:::\n\n\nL'argomento `file` salva il modello compilato e stimato in un file `.rds` (qui in\nuna cartella `objects`): alle esecuzioni successive brms lo ricarica invece di\nricompilare; con `file_refit = \"on_change\"` ristima solo se modello, dati o prior\nsono cambiati.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_gioco_brm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: punteggio ~ sesso \n   Data: gioco (Number of observations: 16) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept     8.04      1.33     5.45    10.69 1.00     2628     2165\nsessom        3.18      1.93    -0.63     7.07 1.00     2633     2659\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     3.74      0.70     2.64     5.33 1.00     2745     2266\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\nRitroviamo tutte le quantità note: stime (`Estimate`), intervalli di credibilità\n(`l-95% CI`, `u-95% CI`), `Rhat` e le due versioni dell'ESS. In più, per\ninterrogare la posterior c'è la comoda funzione `hypothesis()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhypothesis(fit_gioco_brm, \"sessom > 0\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHypothesis Tests for class b:\n    Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio Post.Prob Star\n1 (sessom) > 0     3.18      1.93     0.01     6.36         19      0.95     \n---\n'CI': 90%-CI for one-sided and 95%-CI for two-sided hypotheses.\n'*': For one-sided hypotheses, the posterior probability exceeds 95%;\nfor two-sided hypotheses, the value tested against lies outside the 95%-CI.\nPosterior probabilities of point hypotheses assume equal prior probabilities.\n```\n\n\n:::\n:::\n\n\n`Post.Prob` è la nostra $Pr(\\delta > 0\\,|\\,D)$, calcolata come proporzione di\ndraws esattamente come l'abbiamo calcolata a mano; `Evid.Ratio` è il rapporto\n$Pr/(1 - Pr)$, cioè gli *odds* a posteriori dell'ipotesi.\n\nE le prior? A differenza di rstanarm — che le sceglie deboli e riscalate sui\ndati — con brms vanno controllate. `get_prior()` mostra le prior in uso (o\nquelle che verrebbero usate, se chiamata su formula e dati prima di stimare):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_prior(fit_gioco_brm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  prior     class   coef group resp dpar nlpar lb ub\n                 (flat)         b                                   \n                 (flat)         b sessom                            \n student_t(3, 8.6, 2.5) Intercept                                   \n   student_t(3, 0, 2.5)     sigma                               0   \n       source\n      default\n (vectorized)\n      default\n      default\n```\n\n\n:::\n:::\n\n\nOgni riga è una prior; le colonne principali si leggono così:\n\n- **`prior`** → la distribuzione assegnata al parametro; `(flat)` = prior piatta\n  (vedi sotto);\n- **`class`** → la categoria di parametro: `b` per i coefficienti dei predittori\n  (le \"pendenze\"), `Intercept` per l'intercetta, `sigma` per la deviazione\n  standard residua;\n- **`coef`** → il coefficiente specifico dentro la classe; se vuoto, la prior\n  vale per *tutti* i coefficienti di quella classe;\n- **`lb`**, **`ub`** → *lower/upper bound*, i limiti del parametro (`sigma` ha\n  `lb = 0`: giustamente, una deviazione standard non può essere negativa);\n- **`source`** → `default` (scelta da brms) oppure `user` (specificata da voi).\n\n::: {.callout-note collapse=\"true\"}\n### La prior `(flat)`\n\nUna prior *flat* (piatta) assegna la stessa credibilità a qualunque valore del\nparametro, da $-\\infty$ a $+\\infty$. È detta **impropria**: non è una vera\ndistribuzione di probabilità, perché l'area sotto la curva è infinita. In\npratica equivale a dire \"non ho alcuna informazione a priori\", lasciando che\nsiano interamente i dati a determinare la stima. È il default di brms per la\nclasse `b`. Funziona, ma una prior anche solo debolmente informativa è quasi\nsempre preferibile (@sec-prior-scelta) — e per il Bayes Factor le prior piatte\nsono proprio inammissibili (@sec-bridge).\n:::\n\n::: {.callout-important}\n### Ma che cos'è quella prior sull'intercetta?\n\nPer rendere il campionamento più efficiente, brms **centra internamente i\npredittori** attorno alla loro media. Di conseguenza la prior su `Intercept` non\nriguarda il valore atteso della risposta quando i predittori valgono 0, ma\nquando sono **al loro valore medio** — per questo il default è una Student-t\ncentrata sulla mediana della risposta. Il centraggio è solo interno:\nl'intercetta e i coefficienti che leggete nel `summary()` finale sono riportati\nsulla scala originale.\n:::\n\nLe prior si impostano con `set_prior()`: lo vedremo tra poco, e il modo giusto\ndi *sceglierle* e collaudarle è il tema della @sec-prior-scelta. Ultima\ndifferenza pratica da ricordare: in `pp_check()` l'argomento per il numero di\nsimulazioni si chiama `ndraws`, non `nreps`.\n\n# Applicazioni {#sec-applicazioni}\n\n## Il t-test ripensato: la ROPE {#sec-rope}\n\nUno psicologo valuta se una nuova tecnica di meditazione riduca lo stress: 60\nsoggetti, 30 di controllo e 30 in trattamento. Simuliamo dati con esattamente le\nstatistiche dello studio (controllo: media 80.8, ds 10.05; trattamento: media\n75.6, ds 14.76):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS)\nset.seed(1515)\ncontrollo   <- as.vector(mvrnorm(30, mu = 80.8, Sigma = 10.05^2, empirical = FALSE))\ntrattamento <- as.vector(mvrnorm(30, mu = 75.6, Sigma = 14.76^2, empirical = FALSE))\n\nmeditazione <- data.frame(gruppo = rep(c(\"controllo\", \"trattamento\"), each = 30),\n                          stress = c(controllo, trattamento))\n```\n:::\n\n\nIl test $t$ classico:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(stress ~ gruppo, data = meditazione,\n       alternative = \"greater\", var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  stress by gruppo\nt = 0.98462, df = 58, p-value = 0.1645\nalternative hypothesis: true difference in means between group controllo and group trattamento is greater than 0\n95 percent confidence interval:\n -2.550206       Inf\nsample estimates:\n  mean in group controllo mean in group trattamento \n                 81.39569                  77.74037 \n```\n\n\n:::\n:::\n\n\n$p \\approx 0.06$: non significativo. Fine dell'analisi? In ottica bayesiana\npossiamo fare un ragionamento più fine. Supponiamo che il trattamento, *per essere\nutile in pratica*, debba produrre una riduzione di **almeno 5 punti**: differenze\ntra $-5$ e 0 sono \"sostanzialmente nulle\". L'intervallo $[-5, 0]$ è la nostra\n**ROPE** (*Region Of Practical Equivalence*; Kruschke, 2015).\n\nStimiamo il modello con una prior debolmente informativa e scettica sulla\ndifferenza ($\\delta \\sim \\mathcal{N}(0, 5)$: a priori, riduzioni e aumenti\nugualmente plausibili, per lo più entro ±10 punti):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_med <- stan_glm(stress ~ gruppo, data = meditazione,\n                    prior = normal(location = 0, scale = 5),\n                    seed = 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPOST <- as.data.frame(fit_med)\ndelta <- POST$gruppotrattamento          # differenza trattamento - controllo\n\nplot(density(delta), lwd = 2, main = \"\",\n     xlab = expression(delta), ylab = expression(p(delta~\"|\"~D)))\nabline(v = c(-5, 0), lty = 3)\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/meditazione-rope-1.png){width=672}\n:::\n\n```{.r .cell-code}\nc(riduzione_utile = mean(delta < -5),          # sotto la ROPE\n  equivalenza     = mean(delta >= -5 & delta <= 0),\n  peggioramento   = mean(delta > 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nriduzione_utile     equivalenza   peggioramento \n          0.184           0.604           0.212 \n```\n\n\n:::\n:::\n\n\nInvece di \"non significativo\", la conclusione diventa: con probabilità circa 0.3\nil trattamento produce una riduzione praticamente rilevante, con probabilità circa\n0.6 una differenza trascurabile, e un peggioramento è poco credibile. Il quadro è\nonesto: i dati non bastano a decidere, e servono più osservazioni — che è\nun'informazione ben diversa da \"rigettiamo/non rigettiamo\".\n\n::: {.callout-note}\nA differenza di NHST, il metodo bayesiano permette anche di **accettare**\nun'ipotesi di equivalenza: se la posterior finisse quasi tutta *dentro* la ROPE,\nconcluderemmo che la differenza è praticamente nulla — cosa che un p-value alto\nnon autorizza mai a dire.\n:::\n\n## Più di due gruppi: l'ANOVA bayesiana {#sec-anova}\n\nUn esperimento sul ragionamento nei bambini (scala 0–15) con tre condizioni:\ncontrollo, rinforzo negativo, rinforzo positivo ($n = 20$ per gruppo).\n\nCosa ci aspettiamo?\n\n$$\n\\mu_0 \\sim \\mathcal{N}(6, 3) \\qquad\n\\mu_{neg} - \\mu_0 \\sim \\mathcal{N}(2, 3) \\qquad\n\\mu_{pos} - \\mu_0 \\sim \\mathcal{N}(5, 3)\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(8)\ncontrollo <- as.vector(mvrnorm(20, mu = 5.9, Sigma = 1.7^2, empirical = TRUE))\nnegativo  <- as.vector(mvrnorm(20, mu = 7.0, Sigma = 1.8^2, empirical = TRUE))\npositivo  <- as.vector(mvrnorm(20, mu = 9.3, Sigma = 1.8^2, empirical = TRUE))\n\nrinforzo <- data.frame(\n  condizione = factor(rep(c(\"controllo\", \"negativo\", \"positivo\"), each = 20)),\n  punteggio  = c(controllo, negativo, positivo))\n\nplot(punteggio ~ condizione, data = rinforzo,\n     xlab = \"Condizione\", ylab = \"Punteggio di ragionamento\")\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/rinforzo-dati-1.png){width=672}\n:::\n:::\n\n\nStimiamo il modello nullo e il modello con la condizione sperimentale (le prior\nsui due coefficienti vanno passate come vettori, nell'ordine dei livelli):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_rinf0 <- stan_glm(punteggio ~ 1, data = rinforzo, seed = 1)\n\nfit_rinf1 <- stan_glm(punteggio ~ condizione, data = rinforzo,\n                      prior_intercept = normal(6, 3),\n                      # prior sullo 0\n                      prior = normal(location = c(0, 0), \n                                     scale = c(3, 3)),\n                      seed = 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(posterior_interval(fit_rinf1, prob = 0.95), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    2.5% 97.5%\n(Intercept)         5.18  6.74\ncondizionenegativo -0.04  2.05\ncondizionepositivo  2.22  4.35\nsigma               1.50  2.16\n```\n\n\n:::\n:::\n\n\nIl **posterior predictive check** — l'equivalente bayesiano del\n`check_predictions()` che conosciamo — confronta i dati osservati con dataset\nsimulati dal modello (qui usando, per ogni simulazione, un diverso draw dei\nparametri, incertezza inclusa):\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(fit_rinf1, nreps = 30)\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/rinforzo-ppcheck-1.png){width=672}\n:::\n:::\n\n\nE la variabilità spiegata ha la sua versione bayesiana: non un numero, ma una\ndistribuzione.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(bayes_R2(fit_rinf1), probs = c(0.05, 0.5, 0.95))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       5%       50%       95% \n0.2288157 0.3797361 0.5131506 \n```\n\n\n:::\n:::\n\n\n**Confronto tra modelli.** Nella dispensa sui modelli lineari abbiamo usato AIC e\npesi di Akaike; l'analogo bayesiano moderno è la **LOO cross-validation**\n(*leave-one-out*, pacchetto loo), che stima la capacità predittiva del modello su\ndati nuovi (elpd, *expected log predictive density*):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(loo)\nloo0 <- loo(fit_rinf0)\nloo1 <- loo(fit_rinf1)\nloo_compare(loo0, loo1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          elpd_diff se_diff\nfit_rinf1   0.0       0.0  \nfit_rinf0 -13.4       4.5  \n```\n\n\n:::\n:::\n\n\nCome per l'AIC, il confronto penalizza automaticamente la\ncomplessità inutile.\n\n\n## Di nuovo `kidiq` {#sec-kidiq}\n\nIl modello è: `kid_score ~ mom_iq * mom_hs`, stimato là con `lm()`, diventa:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkidiq <- read.csv(\"dati/kidiq.csv\")\nkidiq$mom_hs <- factor(kidiq$mom_hs)\n\nfit_kidiq <- stan_glm(kid_score ~ mom_iq * mom_hs, data = kidiq, seed = 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm4 <- lm(kid_score ~ mom_iq * mom_hs, data = kidiq)\nround(cbind(lm = coef(m4), stan_glm = coef(fit_kidiq)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   lm stan_glm\n(Intercept)    -11.48    -9.70\nmom_iq           0.97     0.95\nmom_hs1         51.27    49.21\nmom_iq:mom_hs1  -0.48    -0.46\n```\n\n\n:::\n:::\n\n\nCon $n = 434$ e prior deboli (i default di rstanarm sono prior debolmente\ninformative, riscalate sui dati: guardate `prior_summary(fit_kidiq)`), le stime\nsono molto vicine a quelle di `lm()` — come deve essere. Le piccole differenze sui\ncoefficienti più grandi (intercetta e `mom_hs1`) sono il leggero shrinkage\nesercitato dalla prior. Quello che cambia davvero è ciò che possiamo *dire*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPOST <- as.data.frame(fit_kidiq)\nmean(POST$`mom_iq:mom_hs1` < 0)      # Pr(interazione < 0 | D)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9985\n```\n\n\n:::\n:::\n\n\nLa probabilità che l'interazione sia negativa (cioè che l'effetto del QI della\nmadre sia più debole tra le diplomate) è 0.999, praticamente certa: un'affermazione\ndiretta, senza passare per \"rigettiamo l'ipotesi che l'interazione sia zero\".\n\n::: {.callout-note icon=false title=\"✏️ Esercizio 9 — La vostra prima regressione bayesiana\"}\nStimate con `stan_glm()` il modello additivo `kid_score ~ mom_iq + mom_hs`.\n\na. Controllate le diagnostiche (Rhat, n_eff, trace plot): il campionamento ha\n   funzionato?\nb. Confrontate le stime con quelle di `lm()`.\nc. Calcolate l'intervallo di credibilità al 95% per il coefficiente di `mom_hs1` e\n   $Pr(\\beta_{hs} > 5\\,|\\,D)$: a parità di QI, quanto è credibile che il diploma\n   della madre \"valga\" più di 5 punti?\nd. Eseguite il posterior predictive check con `pp_check()`.\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Soluzione — Esercizio 9\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_add <- stan_glm(kid_score ~ mom_iq + mom_hs, data = kidiq, seed = 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_add, digits = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Info:\n function:     stan_glm\n family:       gaussian [identity]\n formula:      kid_score ~ mom_iq + mom_hs\n algorithm:    sampling\n sample:       4000 (posterior sample size)\n priors:       see help('prior_summary')\n observations: 434\n predictors:   3\n\nEstimates:\n              mean   sd    10%   50%   90%\n(Intercept) 25.74   5.85 18.30 25.72 33.46\nmom_iq       0.56   0.06  0.49  0.56  0.64\nmom_hs1      5.97   2.21  3.12  6.03  8.81\nsigma       18.18   0.62 17.42 18.16 18.99\n\nFit Diagnostics:\n           mean   sd    10%   50%   90%\nmean_PPD 86.81   1.23 85.23 86.82 88.39\n\nThe mean_ppd is the sample average posterior predictive distribution of the outcome variable (for details see help('summary.stanreg')).\n\nMCMC diagnostics\n              mcse Rhat n_eff\n(Intercept)   0.08 1.00 4750 \nmom_iq        0.00 1.00 4418 \nmom_hs1       0.03 1.00 4400 \nsigma         0.01 1.00 4948 \nmean_PPD      0.02 1.00 4514 \nlog-posterior 0.03 1.00 1904 \n\nFor each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains (at convergence Rhat=1).\n```\n\n\n:::\n\n```{.r .cell-code}\nround(cbind(lm = coef(lm(kid_score ~ mom_iq + mom_hs, data = kidiq)),\n            stan_glm = coef(fit_add)), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               lm stan_glm\n(Intercept) 25.73    25.72\nmom_iq       0.56     0.56\nmom_hs1      5.95     6.03\n```\n\n\n:::\n\n```{.r .cell-code}\nposterior_interval(fit_add, prob = 0.95, pars = \"mom_hs1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            2.5%    97.5%\nmom_hs1 1.629229 10.19254\n```\n\n\n:::\n\n```{.r .cell-code}\nPOST <- as.data.frame(fit_add)\nmean(POST$mom_hs1 > 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.67225\n```\n\n\n:::\n\n```{.r .cell-code}\npp_check(fit_add, nreps = 30)\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/sol-es9-output-1.png){width=672}\n:::\n:::\n\n\na. Rhat = 1 e n_eff nell'ordine delle migliaia: tutto bene.\nb. Le stime sono praticamente identiche a `lm()` ($n$ grande, prior deboli).\nc. L'intervallo al 95% va da circa 1.6 a circa 10.2; $Pr(\\beta_{hs} > 5) \\approx 0.67$:\n   più probabile che no, ma tutt'altro che certo — l'intervallo è largo.\nd. Le curve simulate seguono bene la distribuzione osservata, come per il modello\n   frequentista della dispensa sui modelli lineari.\n:::\n\n::: {.callout-note icon=false title=\"✏️ Esercizio 10 — Un'analisi completa\"}\nTornate all'esperimento sul rinforzo (@sec-anova) e completate l'analisi:\n\na. dalla posterior di `fit_rinf1`, calcolate la distribuzione della differenza\n   **positivo − negativo** (differenza tra i due coefficienti) e il suo intervallo\n   di credibilità al 90%;\nb. calcolate $Pr(\\mu_{pos} > \\mu_{neg}\\,|\\,D)$;\nc. definite una ROPE per questa differenza, ad esempio $[-1, 1]$ punti\n   (\"praticamente equivalenti\"), e calcolate la probabilità che la differenza le\n   sia esterna (a destra);\nd. scrivete due righe di conclusioneche riportino stime, intervalli e probabilità.\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Soluzione — Esercizio 10\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nPOST <- as.data.frame(fit_rinf1)\ndelta_pos_neg <- POST$condizionepositivo - POST$condizionenegativo\n\nplot(density(delta_pos_neg), lwd = 2, main = \"\",\n     xlab = \"Differenza positivo - negativo\", ylab = \"densita di probabilita\")\nabline(v = c(-1, 1), lty = 3)\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/sol-es10-1.png){width=672}\n:::\n\n```{.r .cell-code}\nquantile(delta_pos_neg, probs = c(0.05, 0.5, 0.95))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      5%      50%      95% \n1.385533 2.253097 3.163649 \n```\n\n\n:::\n\n```{.r .cell-code}\nmean(delta_pos_neg > 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(delta_pos_neg > 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9905\n```\n\n\n:::\n:::\n\n\na. L'intervallo al 90% va da circa 1.4 a circa 3.2 punti.\nb. Praticamente 1: che il rinforzo positivo superi quello negativo è pressoché\n   certo, dati questi dati (e queste prior).\nc. $Pr(\\delta > 1\\,|\\,D) \\approx 0.99$: la differenza non solo è positiva, ma è\n   credibilmente *rilevante* secondo la soglia che ci siamo dati.\nd. Ad esempio: \"il rinforzo positivo produce punteggi di ragionamento superiori al\n   rinforzo negativo di 2.3 punti (mediana a posteriori; intervallo di credibilità\n   al 90% [1.4; 3.2]); la probabilità che la differenza superi la soglia di\n   rilevanza pratica di 1 punto è 0.99. Il modello con la condizione sperimentale\n   mostra inoltre una capacità predittiva nettamente superiore al modello nullo\n   (confronto LOO).\"\n:::\n\n# Quantificare l'evidenza: il Bayes Factor {#sec-bf}\n\nFinora abbiamo usato la posterior per fare affermazioni sui **parametri**\n($Pr(\\delta > 0\\,|\\,D)$, intervalli, ROPE) e la LOO per confrontare la capacità\n**predittiva** dei modelli. C'è una terza domanda possibile: *di quanto i dati\nspostano l'evidenza tra due ipotesi?*\n\nIl **Bayes Factor** (BF) è un **rapporto di verosimiglianza** (*likelihood\nratio*): misura il supporto relativo che l'**evidenza** fornisce a due ipotesi in\ncompetizione, $H_0$ e $H_1$.\n\nIl rapporto tra la probabilità a posteriori di $H_0$ vs. $H_1$, si ottiene\nmoltiplicando **prior odds** delle ipotesi ed il **Bayes Factor**:\n\n$$\n\\frac{p(H_0|D)}{p(H_1|D)} = \\frac{p(D|H_0)}{p(D|H_1)} \\times \\frac{p(H_0)}{p(H_1)}\n$$\n\nLa formula si può quindi parafrasare così:\n\n$$\n\\text{posterior odds} = \\text{Bayes Factor} \\times \\text{prior odds}\n$$\n\nLa probabilità a posteriori di ciascuna ipotesi, dati i dati, è quindi:\n\n$$\np(H_0|D) = \\frac{p(D|H_0) \\times p(H_0)}{p(D|H_1) \\times p(H_1) + p(D|H_0) \\times p(H_0)}\n$$\n\n![La logica del Bayes Factor (da Keysers, Gazzola & Wagenmakers, 2020). In alto:\nle distribuzioni dei valori di $t$ *previste* da $H_0$ (rosso) e da $H_1$ (blu).\nAl centro: il BF è il rapporto tra le **altezze** delle due curve nel punto\nrealmente osservato $t_1$ — notate la differenza con il p-value, che è l'*area*\noltre $t_1$ sotto la sola $H_0$ (in giallo nel primo pannello). In basso: la\nscala dell'evidenza.](img/figBF.png)\n\nChe cosa sono $p(D\\,|\\,H_0)$ e $p(D\\,|\\,H_1)$? Se l'ipotesi fissa il parametro a\nun valore preciso (es. $H_0: \\theta = 0.5$), è la solita verosimiglianza. Se\ninvece l'ipotesi lascia il parametro libero con una prior (es.\n$H_1: \\theta \\sim \\text{Beta}(1, 1)$), è la **verosimiglianza marginale**: la\nmedia della likelihood pesata con la prior,\n\n$$\np(D\\,|\\,H) = \\int p(D\\,|\\,\\theta, H)\\, p(\\theta\\,|\\,H)\\, d\\theta\n$$\n\n\nCalcolare il BF può essere difficile in certe situazioni: l'integrale della verosimiglianza marginale raramente ha una forma chiusa. Vediamo i due strumenti principali.\n\n## Stimare il BF: il bridge sampling {#sec-bridge}\n\nNel caso generale — un modello di regressione con i suoi coefficienti e la sua\n$\\sigma$ — la verosimiglianza marginale è un integrale su *tutti* i parametri e\nva **stimata** con metodi dedicati. Lo standard attuale è il **bridge sampling**\n(pacchetto bridgesampling; Gronau et al., 2020).\n\nCon brms servono due accorgimenti: stimare i modelli con\n`save_pars = save_pars(all = TRUE)` (il bridge sampling ha bisogno di tutti i\ndraws) e usare **prior proprie** su tutti i parametri — con le prior piatte di\ndefault sui coefficienti la verosimiglianza marginale non esiste nemmeno.\nConfrontiamo, per la meditazione (@sec-rope), il modello con il gruppo contro il\nmodello nullo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_med_h1 <- brm(stress ~ gruppo, data = meditazione,\n                  prior = set_prior(\"normal(0, 5)\", class = \"b\"),\n                  save_pars = save_pars(all = TRUE),\n                  iter = 4000, seed = 1,\n                  file = \"objects/fit_med_h1\", file_refit = \"on_change\")\n\nfit_med_h0 <- brm(stress ~ 1, data = meditazione,\n                  save_pars = save_pars(all = TRUE),\n                  iter = 4000, seed = 1,\n                  file = \"objects/fit_med_h0\", file_refit = \"on_change\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbayes_factor(fit_med_h1, fit_med_h0, silent = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstimated Bayes factor in favor of fit_med_h1 over fit_med_h0: 0.81800\n```\n\n\n:::\n:::\n\n\n$BF_{10} \\approx 1.3$: evidenza \"aneddotica\", i dati della meditazione non\nspostano quasi nulla — coerente con l'analisi ROPE, che lasciava aperte tutte le\npossibilità (ma ora sappiamo anche *quantificare* quel \"non sappiamo\"). Per un\ncaso particolare ma importantissimo — l'ipotesi **puntuale annidata**, come\n$\\delta = 0$ dentro il modello completo — esiste però una scorciatoia che non\nrichiede di stimare nessun integrale.\n\n## Il rapporto di Savage-Dickey {#sec-savage-dickey}\n\nQuando $H_0$ è un caso particolare di $H_1$ (un'ipotesi *puntuale* annidata:\n$\\theta = 0.5$ dentro \"$\\theta$ libera\", oppure $\\delta = 0$ dentro\n\"$\\delta \\sim \\mathcal{N}(0, 5)$\"), il BF si ottiene confrontando prior e\nposterior **nel punto nullo**:\n\n$$\nBF_{01} = \\frac{p(\\theta_0\\,|\\,D, H_1)}{p(\\theta_0\\,|\\,H_1)}\n$$\n\nL'intuizione: se i dati hanno *allontanato* la densità da $\\theta_0$ (posterior\npiù bassa della prior in quel punto), sono evidenza contro $H_0$; se l'hanno\n*concentrata* su $\\theta_0$, sono evidenza a favore.\n\nVediamolo sui kiwi: $H_0: \\theta = 0.5$ (popolazione bilanciata) contro\n$H_1: \\theta \\sim \\text{Beta}(1, 1)$. Prior e posterior sono note —\n$\\text{Beta}(1, 1)$ e $\\text{Beta}(3, 8)$ — quindi bastano due `dbeta()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbeta(0.5, 3, 8) / dbeta(0.5, 1, 1)     # BF01\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.703125\n```\n\n\n:::\n:::\n\n\n$BF_{01} = 0.70$, cioè $BF_{10} \\approx 1.4$: con 9 animali i dati non\ndistinguono le due ipotesi (evidenza debole, guardate la scala).\n\nE se avessimo osservato una perfetta parità, 45 maschi su 90? La posterior\nsarebbe $\\text{Beta}(46, 46)$, *concentrata* proprio sul punto nullo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbeta(0.5, 46, 46) / dbeta(0.5, 1, 1)   # BF01\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.632272\n```\n\n\n:::\n:::\n\n\n$BF_{01} \\approx 7.6$: evidenza moderata **a favore** dell'ipotesi nulla.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Codice del grafico\"}\npar(mfrow = c(1, 2), mar = c(4, 4, 3, 1))\n# caso 1: 2 maschi su 9\ncurve(dbeta(x, 3, 8), from = 0, to = 1, lwd = 2, col = \"red\", ylim = c(0, 8),\n      xlab = expression(theta), ylab = \"densita di probabilita\",\n      main = \"2 maschi su 9: BF01 = 0.70\")\ncurve(dbeta(x, 1, 1), add = TRUE, lwd = 2, lty = 2)\npoints(c(0.5, 0.5), c(dbeta(0.5, 1, 1), dbeta(0.5, 3, 8)), pch = 19)\nlegend(\"topright\", bty = \"n\", lwd = 2, lty = c(2, 1), col = c(\"black\", \"red\"),\n       legend = c(\"prior\", \"posterior\"))\n# caso 2: 45 maschi su 90\ncurve(dbeta(x, 46, 46), from = 0, to = 1, lwd = 2, col = \"red\", ylim = c(0, 8),\n      xlab = expression(theta), ylab = \"densita di probabilita\",\n      main = \"45 maschi su 90: BF01 = 7.6\")\ncurve(dbeta(x, 1, 1), add = TRUE, lwd = 2, lty = 2)\npoints(c(0.5, 0.5), c(dbeta(0.5, 1, 1), dbeta(0.5, 46, 46)), pch = 19)\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/sd-visual-1.png){width=768}\n:::\n:::\n\n\nA sinistra i dati hanno abbassato la densità nel punto nullo (evidenza debole contro $H_0$), a destra l'hanno alzata di quasi 8 volte (evidenza a favore).\n\nE per la meditazione? L'ipotesi $\\delta = 0$ è annidata nel modello con prior\n$\\mathcal{N}(0, 5)$: il Savage-Dickey stima lo stesso BF del bridge sampling —\ne brms lo calcola da solo con `hypothesis()`, come vedrete nell'Esercizio 11.\n\n\n::: {.callout-note icon=false title=\"✏️ Esercizio 11 — Il Savage-Dickey con brms\"}\nAnche `brms` sa calcolare il Bayes Factor con il rapporto di Savage-Dickey.\nTornate ai dati della meditazione (@sec-rope) e testate l'ipotesi puntuale\n$\\delta = 0$:\n\na. stimate il modello con brms, con prior $\\mathcal{N}(0, 5)$ sul coefficiente\n   e l'argomento `sample_prior = TRUE` (per il Savage-Dickey servono anche i\n   campioni dalla prior);\nb. calcolate il BF con `hypothesis(fit, \"gruppotrattamento = 0\")`: per le\n   ipotesi *puntuali*, `Evid.Ratio` è il $BF_{01}$ di Savage-Dickey;\nc. guardate `plot(hypothesis(...))`: che cosa mostra?\nd. interpretate il risultato e confrontatelo con l'analisi ROPE della @sec-rope:\n   le due conclusioni sono coerenti?\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Soluzione — Esercizio 11\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_med_brm <- brm(stress ~ gruppo, data = meditazione,\n                   prior = set_prior(\"normal(0, 5)\", class = \"b\",\n                                     coef = \"gruppotrattamento\"),\n                   sample_prior = TRUE, seed = 1,\n                   file = \"objects/fit_med_brm\",\n                   file_refit = \"on_change\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nh <- hypothesis(fit_med_brm, \"gruppotrattamento = 0\")\nh\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHypothesis Tests for class b:\n               Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio\n1 (gruppotrattamento) = 0    -2.36      2.96    -8.19     3.44       1.18\n  Post.Prob Star\n1      0.54     \n---\n'CI': 90%-CI for one-sided and 95%-CI for two-sided hypotheses.\n'*': For one-sided hypotheses, the posterior probability exceeds 95%;\nfor two-sided hypotheses, the value tested against lies outside the 95%-CI.\nPosterior probabilities of point hypotheses assume equal prior probabilities.\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(h)\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/sol-es13-output-1.png){width=672}\n:::\n:::\n\n\nb. `Evid.Ratio` è poco sotto 1: i dati sono leggermente *contro* l'ipotesi nulla\n   ($BF_{10} = 1/BF_{01}$ poco sopra 1), ma siamo in piena zona \"evidenza\n   debole\": i dati non discriminano tra \"nessun effetto\" e \"un effetto\".\nc. Il grafico mostra prior e posterior di $\\delta$ sovrapposte: il Savage-Dickey\n   è il rapporto tra le loro altezze nel punto $\\delta = 0$, ed è visibilmente\n   vicino a 1.\nd. È la stessa conclusione dell'analisi ROPE, vista dall'angolo del test: là\n   dicevamo \"i dati non bastano a decidere tra riduzione utile ed equivalenza\",\n   qui \"i dati non spostano l'evidenza tra $H_0$ e $H_1$\". Con $n = 60$ e un\n   effetto piccolo, nessuno strumento può inventarsi l'informazione che non c'è —\n   ma entrambi, a differenza del p-value, lo *dicono* esplicitamente. Notate\n   infine che $BF_{01} \\approx 0.74$ equivale a $BF_{10} \\approx 1.35$: in\n   accordo (a meno dell'errore di stima) con il bridge sampling della\n   @sec-bridge — due stimatori della stessa quantità.\n:::\n\n# Scegliere le prior {#sec-prior-scelta}\n\nLe prior sono la forza dell'approccio bayesiano — permettono di incorporare\nconoscenza, regolarizzano le stime, rendono possibili modelli complessi — ma vanno\nscelte con consapevolezza: una prior mal calibrata può produrre veri e propri\nerrori inferenziali. Tre regole pratiche (adattate dalle\n[raccomandazioni del team di Stan](https://github.com/stan-dev/stan/wiki/prior-choice-recommendations)):\n\n1. **Debolmente informative è meglio di non informative.** Una prior debolmente\n   informativa esclude valori assurdi del parametro senza sbilanciare la stima\n   (es. $\\mathcal{N}(0, 5)$ per una differenza che sulla scala della variabile non\n   può ragionevolmente superare ±15). Le prior piatte \"per prudenza\" in realtà\n   dicono che un coefficiente di 10 e uno di 10 milioni sono ugualmente plausibili:\n   non è prudenza, è un'affermazione estrema.\n2. **Debolmente informative è meglio di troppo informative.** Perdere un po' di\n   precisione con una prior un po' troppo larga costa meno che escludere per\n   errore regioni plausibili con una prior troppo stretta.\n3. **Con** $n$ **piccolo, la prior va dichiarata e messa alla prova.** Lo abbiamo\n   visto nell'Esercizio 7: con 10 osservazioni, prior diverse producono conclusioni\n   diverse. In questi casi si fa una **sensitivity analysis**: si ristima il\n   modello con prior più e meno informative e si verifica quanto cambiano le\n   conclusioni.\n\n## Il ruolo della scala: quanto è informativa una prior? {#sec-prior-sd}\n\nMa che cosa vuol dire, in concreto, \"debolmente informativa\"? Una prior normale su un coefficiente ha due parametri: la **media** (dove crediamo stia il valore — quasi sempre 0, per scetticismo: nessuna direzione privilegiata) e la **deviazione standard**, che decide *quanto lontano da zero siamo disposti a\ncredere*. La regola pratica è quella dei due sd: una $\\mathcal{N}(0, sd)$ dice che il coefficiente sta tra $-2 \\cdot sd$ e $+2 \\cdot sd$ con probabilità circa 0.98.\n\nTorniamo alla differenza di stress tra trattamento e controllo della @sec-rope (punteggi di stress attorno a 60–100). Tre prior candidate per $\\delta$:\n\n- $\\mathcal{N}(0, 1)$: differenza entro ±2 punti al 95% — prior **fortemente scettica**: esclude in partenza quasi ogni effetto interessante;\n- $\\mathcal{N}(0, 5)$: entro ±10 punti — **debolmente informativa** su questa\n  scala: lascia spazio a ogni effetto realistico ed esclude solo gli assurdi (è\n  quella che abbiamo usato nella @sec-rope);\n- $\\mathcal{N}(0, 50)$: entro ±100 punti — di fatto **piatta** sulla scala del\n  problema.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Codice del grafico\"}\ncurve(dnorm(x, 0, 1), from = -30, to = 30, lwd = 2,\n      xlab = expression(delta), ylab = expression(p(delta)))\ncurve(dnorm(x, 0, 5), add = TRUE, lwd = 2, col = \"blue\")\ncurve(dnorm(x, 0, 50), add = TRUE, lwd = 2, col = \"red\")\nlegend(\"topright\", bty = \"n\", lwd = 2, col = c(\"black\", \"blue\", \"red\"),\n       legend = c(\"Normal(0, 1)\", \"Normal(0, 5)\", \"Normal(0, 50)\"))\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/prior-sd-curve-1.png){width=672}\n:::\n:::\n\n\nPer rendersi conto di che cosa \"crede\" ciascuna prior, basta calcolare quanta probabilità assegna a un effetto più grande di 10 punti (in una direzione o nell'altra):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd_prior <- c(1, 5, 50)\nround(2 * pnorm(-10, mean = 0, sd = sd_prior), 3)   # Pr(|delta| > 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.000 0.046 0.841\n```\n\n\n:::\n:::\n\n\nPer la prior stretta un effetto oltre i 10 punti è praticamente impossibile; per quella debolmente informativa è raro ma contemplato (5%); per quella vaga è\nquasi l'aspettativa di default (84%). \n\n## La sensitivity analysis {#sec-sensitivity}\n\nMettiamo alla prova le tre prior sull'esempio della meditazione, stimando tre volte lo stesso modello con brms. Ripassiamo la sintassi di `set_prior()`: si passa la distribuzione (come stringa) e si dice a che cosa si applica:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_stretta <- set_prior(\"normal(0, 1)\",             # la distribuzione\n                           class = \"b\",                # classe: coefficienti\n                           coef = \"gruppotrattamento\") # quale coefficiente\n\nprior_media <- set_prior(\"normal(0, 5)\",  class = \"b\", coef = \"gruppotrattamento\")\nprior_vaga  <- set_prior(\"normal(0, 50)\", class = \"b\", coef = \"gruppotrattamento\")\n\nfit_med_stretta <- brm(stress ~ gruppo, data = meditazione,\n                       prior = prior_stretta, seed = 1,\n                       file = \"objects/fit_med_stretta\",\n                       file_refit = \"on_change\")\nfit_med_media   <- brm(stress ~ gruppo, data = meditazione,\n                       prior = prior_media, seed = 1,\n                       file = \"objects/fit_med_media\",\n                       file_refit = \"on_change\")\nfit_med_vaga    <- brm(stress ~ gruppo, data = meditazione,\n                       prior = prior_vaga, seed = 1,\n                       file = \"objects/fit_med_vaga\",\n                       file_refit = \"on_change\")\n```\n:::\n\n\nConfrontiamo prior e posterior della differenza nei tre scenari (la linea\npunteggiata verticale è la differenza osservata nei dati, -3.6553226):\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Codice del grafico\"}\nscala <- c(1, 5, 50)\nfits  <- list(fit_med_stretta, fit_med_media, fit_med_vaga)\n\npar(mfrow = c(1, 3), mar = c(4, 4, 3, 1))\nfor (k in 1:3) {\n  draws <- as.data.frame(fits[[k]])$b_gruppotrattamento\n  plot(density(draws), lwd = 2, col = \"red\", xlim = c(-16, 10),\n       ylim = c(0, 0.45), main = paste0(\"Normal(0, \", scala[k], \")\"),\n       xlab = expression(delta), ylab = \"densita di probabilita\")\n  curve(dnorm(x, 0, scala[k]), add = TRUE, lwd = 2, lty = 2)\n  abline(v = mean(meditazione$stress[meditazione$gruppo==\"trattamento\"])-mean(meditazione$stress[meditazione$gruppo==\"controllo\"]), lty = 3)\n  if (k == 1) legend(\"topleft\", bty = \"n\", lwd = 2, lty = c(2, 1),\n                     col = c(\"black\", \"red\"),\n                     legend = c(\"prior\", \"posterior\"))\n}\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/sensitivity-plot-1.png){width=864}\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Codice del grafico\"}\npar(mfrow = c(1, 1))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrbind(stretta = fixef(fit_med_stretta)[\"gruppotrattamento\", ],\n      media   = fixef(fit_med_media)[\"gruppotrattamento\", ],\n      vaga    = fixef(fit_med_vaga)[\"gruppotrattamento\", ])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Estimate Est.Error       Q2.5    Q97.5\nstretta -0.2681217 0.9652494  -2.141901 1.648798\nmedia   -2.3531791 3.0074206  -8.071360 3.521712\nvaga    -3.6905588 3.7355269 -10.890718 3.590522\n```\n\n\n:::\n:::\n\n\nCon la prior\nstrettissima $\\mathcal{N}(0, 1)$ vince la prior: la posterior le resta\nincollata e la stima viene schiacciata quasi a zero ($n = 60$ non basta a farle\n\"cambiare idea\"). \n\n## Il prior predictive check {#sec-prior-predictive}\n\nLe regole aiutano, ma come si fa a *vedere* se le prior scelte sono sensate?\nL'idea è la stessa della distribuzione predittiva (@sec-predittiva), con la\nprior al posto della posterior: **simulare dati dal modello prima di avergli mostrato quelli veri**. \n\nSe il modello, con le nostre prior, genera dati assurdi,\nle prior vanno riviste. In brms basta l'argomento `sample_prior = \"only\"`: il modello viene \"stimato\" ignorando completamente i dati.\n\nSimuliamo uno studio ($n = 70$) in cui la depressione dipende da gruppo, età e ansia — e siccome i dati li generiamo noi, conosciamo i coefficienti **veri**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1555)\nn <- 70\nansia  <- rnorm(n)\neta    <- scale(round(runif(n, 18, 50)))[,1]\ngruppo <- rep(c(\"g1\", \"g2\"), length.out = n)\n\ndepressione <- 0.3 + 0.01 * eta + 0.5 * ansia +\n               0.3 * ifelse(gruppo == \"g1\", 0, 1) + rnorm(n)\ndat_dep <- data.frame(depressione, gruppo, eta, ansia)\nrange(depressione)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -3.154986  3.804394\n```\n\n\n:::\n:::\n\n\nProviamo come prior $\\mathcal{N}(0, 1)$ su tutti i coefficienti.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_1 <- set_prior(\"normal(0, 1)\", class = \"b\")\n\nfit_prior_1 <- brm(depressione ~ gruppo + eta + ansia, data = dat_dep,\n                   prior = prior_1, sample_prior = \"only\", seed = 1,\n                   file = \"objects/fit_prior_1\", file_refit = \"on_change\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(fit_prior_1, ndraws = 100)\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/ppc-prior-1-check-1.png){width=672}\n:::\n:::\n\n\nI dati veri (curva scura) stanno tra circa −2 e 5; il modello, prima di vederli, prevedeva tranquillamente valori di decine di punti. Riproviamo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_2 <- c(\n  set_prior(\"normal(0, 0.5)\", class = \"b\", coef = \"gruppog2\"),\n  set_prior(\"normal(0, 0.05)\", class = \"b\", coef = \"eta\"),\n  set_prior(\"normal(0, 0.5)\", class = \"b\", coef = \"ansia\"),\n  set_prior(\"normal(0, 2)\", class = \"sigma\"))\n\nfit_prior_2 <- brm(depressione ~ gruppo + eta + ansia, data = dat_dep,\n                   prior = prior_2, sample_prior = \"only\", seed = 1,\n                   file = \"objects/fit_prior_2\", file_refit = \"on_change\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(fit_prior_2, ndraws = 100)\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/ppc-prior-2-check-1.png){width=672}\n:::\n:::\n\n\nOra le previsioni a priori coprono un range plausibile senza essere incollate ai\ndati: prior **debolmente informative** fatte bene. Possiamo stimare il modello\nvero e proprio con queste prior:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_dep <- brm(depressione ~ gruppo + eta + ansia, data = dat_dep,\n               prior = prior_2, seed = 1,\n               file = \"objects/fit_dep\", file_refit = \"on_change\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(fixef(fit_dep), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Estimate Est.Error  Q2.5 Q97.5\nIntercept     0.01      0.18 -0.35  0.36\ngruppog2      0.54      0.24  0.07  1.02\neta           0.01      0.05 -0.08  0.11\nansia         0.65      0.13  0.40  0.91\n```\n\n\n:::\n:::\n\n\n> Cosa concludereste?\n\n\n## Parameter recovery {#sec-recovery}\n\nCon dati simulati possiamo fare un controllo impossibile con i dati veri:\nverificare che il modello **recuperi i parametri usati per generare i dati**. Se\nnon ci riesce con i dati \"puliti\" di una simulazione, non c'è motivo di fidarsi\ndi quello che dirà sui dati veri: è un collaudo standard quando si mette in\npiedi un modello nuovo.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nveri <- c(0.3, 0.3, 0.01, 0.5, 1)   # intercetta, gruppo, eta, ansia, sigma\ndraws <- data.frame(fit_dep)[, 1:5]\ncolnames(draws)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"b_Intercept\" \"b_gruppog2\"  \"b_eta\"       \"b_ansia\"     \"sigma\"      \n```\n\n\n:::\n\n```{.r .cell-code}\nmcmc_recover_intervals(draws, true = veri, prob = 0.80, prob_outer = 0.95)\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/recovery-1.png){width=672}\n:::\n:::\n\n\nI triangoli chiari sono i valori veri, i punti scuri le stime con i loro\nintervalli di credibilità (80% e 95%): tutti i valori veri cadono negli\nintervalli al 95%. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_3 <- c(\n  set_prior(\"normal(0, 0.25)\", class = \"b\", coef = \"gruppog2\"),\n  set_prior(\"normal(0, 0.05)\", class = \"b\", coef = \"eta\"),\n  set_prior(\"normal(0, 0.25)\", class = \"b\", coef = \"ansia\"),\n  set_prior(\"normal(0, 2)\", class = \"sigma\"))\n\nfit_dep2 <- brm(depressione ~ gruppo + eta + ansia, data = dat_dep,\n               prior = prior_3, seed = 1,\n               file = \"objects/fit_dep2\", file_refit = \"on_change\")\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndraws <- data.frame(fit_dep2)[, 1:5]\ncolnames(draws)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"b_Intercept\" \"b_gruppog2\"  \"b_eta\"       \"b_ansia\"     \"sigma\"      \n```\n\n\n:::\n\n```{.r .cell-code}\nmcmc_recover_intervals(draws, true = veri, prob = 0.80, prob_outer = 0.95)\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/recovery2-1.png){width=672}\n:::\n\n```{.r .cell-code}\nround(fixef(fit_dep2), 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Estimate Est.Error  Q2.5 Q97.5\nIntercept     0.14      0.17 -0.20  0.48\ngruppog2      0.31      0.19 -0.05  0.67\neta           0.02      0.05 -0.08  0.11\nansia         0.53      0.12  0.29  0.75\n```\n\n\n:::\n:::\n\n\n\n#  Esercizio - GLM {#sec-glm}\n\n\n::: {.callout-note icon=false title=\"✏️ Esercizio 12 — Una regressione logistica\"}\nIl dataset [teddy_child.csv](dati/teddy_child.csv) contiene dati su 379 genitori; tra le variabili ci sono `Depression_pp` (depressione post-partum: Yes/No) e `Parental_stress` (stress genitoriale). Vogliamo modellare la **probabilità** di depressione in funzione dello stress.\n\na. Caricate i dati e convertite la risposta in 0/1:\n   `teddy$dep01 <- ifelse(teddy$Depression_pp == \"Yes\", 1, 0)`.\nb. Una risposta 0/1 non può essere normale: la famiglia giusta è la Bernoulli, con il *link* logit che collega la probabilità (tra 0 e 1) alla scala lineare dei predittori. Stimate con brms il modello `dep01 ~ Parental_stress` con\n   `family = bernoulli(link = \"logit\")` (e `file =`, come sempre).\nc. Guardate il `summary()`: diagnostiche a parte, su che scala sono i\n   coefficienti? Il coefficiente dello stress è credibilmente positivo?\n   (`hypothesis()`)\nd. Rendete i risultati interpretabili: `exp()` del coefficiente è l'**odds ratio** per +1 punto di stress; `conditional_effects(fit)` mostra l'effetto\n   direttamente sulla scala della probabilità.\ne. Provate `pp_check(fit, ndraws = 30)`: che aspetto hanno i dati simulati da\n   un modello Bernoulli? Il density overlay è ancora lo strumento giusto?\n:::\n\n::: {.callout-tip collapse=\"true\" title=\"Soluzione — Esercizio 12\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nteddy <- read.csv(\"dati/teddy_child.csv\")\nteddy$dep01 <- ifelse(teddy$Depression_pp == \"Yes\", 1, 0)\n\nfit_teddy <- brm(dep01 ~ Parental_stress, data = teddy,\n                 family = bernoulli(link = \"logit\"), seed = 1,\n                 file = \"objects/fit_teddy\", file_refit = \"on_change\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_teddy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: bernoulli \n  Links: mu = logit \nFormula: dep01 ~ Parental_stress \n   Data: teddy (Number of observations: 379) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n                Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept          -4.31      0.70    -5.75    -2.96 1.00     2882     2309\nParental_stress     0.04      0.01     0.02     0.06 1.00     3172     2686\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n\n```{.r .cell-code}\nhypothesis(fit_teddy, \"Parental_stress > 0\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHypothesis Tests for class b:\n             Hypothesis Estimate Est.Error CI.Lower CI.Upper Evid.Ratio\n1 (Parental_stress) > 0     0.04      0.01     0.02     0.05       1999\n  Post.Prob Star\n1         1    *\n---\n'CI': 90%-CI for one-sided and 95%-CI for two-sided hypotheses.\n'*': For one-sided hypotheses, the posterior probability exceeds 95%;\nfor two-sided hypotheses, the value tested against lies outside the 95%-CI.\nPosterior probabilities of point hypotheses assume equal prior probabilities.\n```\n\n\n:::\n\n```{.r .cell-code}\nPOST <- as.data.frame(fit_teddy)\nquantile(exp(POST$b_Parental_stress), probs = c(0.025, 0.5, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    2.5%      50%    97.5% \n1.016115 1.036545 1.057465 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconditional_effects(fit_teddy)\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/sol-es12-effects-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(fit_teddy, ndraws = 30)\n```\n\n::: {.cell-output-display}\n![](bayes_files/figure-html/sol-es12-ppcheck-1.png){width=672}\n:::\n:::\n\n\nc. Le stime sono sulla scala dei **log-odds** (il link logit): non si\n   interpretano direttamente. Il coefficiente dello stress è credibilmente\n   positivo: $Pr(\\beta > 0\\,|\\,D)$ è praticamente 1.\nd. L'odds ratio dice di quanto si *moltiplicano* gli odds di depressione per\n   ogni punto di stress in più: qui la mediana è circa 1.04 (+4% di odds per\n   punto, intervallo al 95% da +2% a +6%). `conditional_effects()` traduce\n   tutto nella scala che interessa davvero: la probabilità di depressione\n   cresce sensibilmente lungo il range dello stress osservato.\ne. I dati simulati da una Bernoulli sono fatti solo di 0 e 1: il density\n   overlay mostra due picchi e serve a poco. Per i GLM esistono predictive\n   check dedicati (es. per proporzioni o per classi): li vedremo nella lezione\n   sui GLM. La logica però non cambia — ed è questo il punto: **prior,\n   diagnostiche, posterior, `hypothesis()`, predictive check funzionano\n   identici** qualunque sia la famiglia. Cambia la distribuzione, non la\n   logica bayesiana.\n:::\n\n# Riepilogo finale\n\nIl percorso completo di un'analisi bayesiana:\n\n1. **modello delle osservazioni**: quale distribuzione genera i dati?\n   (binomiale, normale, ...);\n2. **prior**: che cosa è plausibile per i parametri prima dei dati? Con che forza?\n3. **posterior** via teorema di Bayes — analitica nei casi coniugati\n   (Beta-binomiale, normale-normale), via MCMC in tutti gli altri;\n4. **diagnostiche**: Rhat, n_eff, trace plot (il campionamento ha funzionato?),\n   posterior predictive check (il modello descrive i dati?);\n5. **sintesi**: stime puntuali, intervalli di credibilità (quantile o HPD),\n   probabilità delle ipotesi di interesse, eventualmente ROPE;\n6. **previsione**: la distribuzione predittiva per nuovi dati (@sec-predittiva),\n   di cui il predictive check è l'uso diagnostico;\n7. **confronto**: tra modelli in termini predittivi (LOO) o di evidenza relativa\n   (Bayes Factor);\n8. **robustezza**: sensitivity analysis sulle prior — obbligatoria con campioni\n   piccoli e ogni volta che si riporta un Bayes Factor.\n\n\n\n# Riferimenti bibliografici\n\n**Testi di riferimento:**\n\n- Gelman, A., Carlin, J. B., Stern, H. S., Dunson, D.B., Vehtari, A., Rubin, D. B. (2014). *Bayesian Data Analysis* (3rd ed.). Chapman & Hall/CRC.\n- Hoff, P. D. (2009). *A First Course in Bayesian Statistical Methods*. Springer.\n- Kruschke, J. (2015). *Doing Bayesian Data Analysis: A Tutorial with R, JAGS, and Stan* (2nd ed.). Academic Press.\n- Lambert, B. (2018). *A Student's Guide to Bayesian Statistics*. SAGE.\n- McElreath, R. (2020). *Statistical Rethinking: A Bayesian Course with Examples in R and Stan* (2nd ed.). CRC Press.\n- Lee, M. D., Wagenmakers, E.-J. (2014). *Bayesian Cognitive Modeling: A Practical Course*. Cambridge University Press.\n\n**Articoli:**\n\n- Cohen, J. (1994). The earth is round (p < .05). *American Psychologist*, 49, 997–1003.\n- Etz, A., Vandekerckhove, J. (2018). Introduction to Bayesian inference for psychology. *Psychonomic Bulletin & Review*, 25, 5–34.\n- Gigerenzer, G., Krauss, S., Vitouch, O. (2004). The null ritual. In D. Kaplan (Ed.), *The Sage Handbook of Quantitative Methodology for the Social Sciences* (pp. 391–408). Sage.\n- Kass, R. E., Raftery, A. E. (1995). Bayes factors. *Journal of the American Statistical Association*, 90, 773–795.\n- Keysers, C., Gazzola, V., Wagenmakers, E.-J. (2020). Using Bayes factor hypothesis testing in neuroscience to establish evidence of absence. *Nature Neuroscience*, 23, 788–799.\n- Kruschke, J. K., Liddell, T. M. (2018). The Bayesian New Statistics: Hypothesis testing, estimation, meta-analysis, and power analysis from a Bayesian perspective. *Psychonomic Bulletin & Review*, 25, 178–206.\n- Rouder, J. N., Speckman, P. L., Sun, D., Morey, R. D., Iverson, G. (2009). Bayesian t tests for accepting and rejecting the null hypothesis. *Psychonomic Bulletin & Review*, 16, 225–237.\n- Wagenmakers, E.-J. (2007). A practical solution to the pervasive problems of p values. *Psychonomic Bulletin & Review*, 14, 779–804.\n- Wasserstein, R. L., Schirm, A. L., Lazar, N. A. (2019). Moving to a world beyond \"p < 0.05\". *The American Statistician*, 73, 1–19.\n\n**In italiano:**\n\n- Pastore, M., Altoè, G. (2013). Bayes Factor e p-value: così vicini, così lontani. *Giornale Italiano di Psicologia*, 40, 175–193.\n\n**Pacchetti R utilizzati in questa dispensa:**\n\n- **rstanarm** (Goodrich et al., 2024) — regressione bayesiana con Stan, modelli precompilati;\n- **bayesplot** (Gabry & Mahr, 2024) — grafici per modelli bayesiani (trace plot, aree di credibilità);\n- **HDInterval** (Meredith & Kruschke, 2022) — intervalli HPD;\n- **loo** (Vehtari et al., 2024) — confronto di modelli via LOO cross-validation;\n- **BayesFactor** (Morey & Rouder, 2024) — Bayes Factor per i disegni classici (t-test, ANOVA, regressione);\n- **brms** (Bürkner, 2017) — modelli bayesiani con sintassi a formula, codice Stan generato e compilato su misura;\n- **bridgesampling** (Gronau, Singmann & Wagenmakers, 2020) — stima della verosimiglianza marginale dai draws MCMC (usato da `brms::bayes_factor()`);\n- **MASS** (Venables & Ripley, 2002) — simulazione di dati con statistiche fissate.\n\n---\n\n*Materiale didattico adattato dalle slide del Prof. Massimiliano Pastore (con\ncontributi di Gianmarco Altoè).*\n",
    "supporting": [
      "bayes_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}